(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol52 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E1251B").s().p("AgsHCIAAuDIBZAAIAAODg");
	this.shape.setTransform(4.55,45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E1251B").s().p("AqyBuIC+AAIjHgKIDSgBIjcgMIBvgDQAfgEAVgLQAIgEAIgGIAIgJQASgVABgdQgBgfgWgXQgWgXghAAQgOAAgMAFIg2g8QAlgWArAAQBAAAAtAtQAuAuAAA/QAABAguAuQgtAthAAAQg/AAgugtgAq+BRQgFgPgPgBIgDgJIAtAAIAJAJIBGAAIgQAQgAluA8QgTgVAAglQAAgkAYgXQAYgXAjAAQAjAAAUATQAXAUAAAnQAAAlgZAXQgXAXgkAAQgmAAgUgVgAlMgkQgNANAAAXQABAwAnAAQAPAAAMgLQANgNgBgYQAAgvgnAAQgQAAgLALgAGCBIQgJgIAAgOQAAgUATgMQASgKAfAAIAAgGQAAgSgXAAQgSAAgQAJIgDgYQAUgHAVAAQAbAAAMAKQAKAKAAASIABBOIgdAAQAAgLABgJQgEAKgKAGQgKAGgNAAQgQAAgJgIgAGWAtQAAAMAOAAQALAAAHgIQAHgJAAgKIAAgDQgnAAAAASgABbA4QgQgTAAggQgBglAWgXQAXgXAoAAQASAAARAEIgEAgQgPgEgQAAQgUAAgLANQgLAMAAAVQAAAvAsAAQARAAANgGIADAgQgTAHgVAAQgrAAgUgYgAjBA4QgQgTAAggQAAglAWgXQAWgXApAAQASAAARAEIgFAgQgPgEgPAAQgVAAgLANQgLAMAAAVQAAAvAsAAQARAAAMgGIAFAgQgTAHgXAAQgqAAgUgYgAD9BOIAAibIA2gBQA1AAAAAnQAAALgHAKQgGAJgMAEQANAEAIAJQAHAJAAANQAAAUgOAMQgQAQgiAAgAEbAJIAAAsIARABQAPAAAIgHQAIgGgBgLQABgVgiAAgAEbg1IAAAoIANABQAfAAAAgWQAAgUgaAAgAhABOIAAibIA+gBQA5AAAAAnQAAALgHAJQgGAKgLAEQAMADAHAKQAIAJgBAMQAAAVgQANQgSAPgiAAgAgYAwIAOABQAaAAAAgUQAAgSgcAAIgMAAgAgYgwIAAAiIALAAQAbAAAAgTQAAgQgWAAIgQABgAK7BOIgkg5IAAA5IgeAAIAAioIAeAAIAABlIAigvIAlAAIgoAzIAsA/gAJABOIAAhKQAAgSgPAAQgLAAgIALQgJAKABAPIAAA4IgeAAIAAhyIAcAAQAAAMgCAIQANgWAcAAQAiAAAAAkIAABQgArXAzQgJgaAAgZQAAgOADgOIBKAaIAAACQAAAbARAVQgJgUAAgTIAAgJIBRAcIAAAXgAqKgEQAEgRALgQIBBAnIAAAXgAp4gpQALgNARgIIAiAiIAAAcgArcgkQAGgZAPgXIBCApQgMARgCATgArChbQARgXAVgOIA4A6QgQAHgOAPg");
	this.shape_1.setTransform(102.7,45.175);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#FFFFFF","rgba(255,255,255,0)"],[0,1],-119.1,0,111.2,0).s().p("Az8HCIAAuDMAn5AAAIAAODg");
	this.shape_2.setTransform(127.725,45);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F2F2F2").s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_3.setTransform(364.05,45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol52, new cjs.Rectangle(0,0,728.1,90), null);


(lib.Symbol51 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F2F2F2").s().p("AipBsIAAjXIFTAAIAADXg");
	this.shape.setTransform(17,10.75);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,34,21.5);


(lib.Symbol50 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#343433").s().p("AmqADIAAgFINVAAIAAAFg");
	this.shape.setTransform(631.9,-118.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#343433").s().p("AgXAcQgLgLAAgRQAAgQALgLQAKgKAOAAQAOAAAKAKQAKAKAAAQIAAACIg9AAQAAAOAIAJQAIAIAMAAQAQAAAKgNIAEADQgKAQgUAAQgPAAgKgKgAgRgYQgIAHgBANIA1AAQgBgNgHgHQgIgHgLAAQgJAAgIAHg");
	this.shape_1.setTransform(670.65,-123.725);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#343433").s().p("AgOAlIAAhHIAHAAIAAANQACgGAFgFQAGgEAJAAIAAAHQgWAAAAAdIAAAlg");
	this.shape_2.setTransform(665.025,-123.825);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#343433").s().p("AgaAbQgKgLAAgQQAAgQAKgKQALgLAPAAQAQAAALALQAKALAAAPQAAAQgKALQgLALgQAAQgPAAgLgLgAgUgWQgJAJAAANQAAAOAJAIQAIAJAMAAQANAAAIgJQAJgIAAgOQAAgNgIgJQgJgJgNAAQgMAAgIAJg");
	this.shape_3.setTransform(658.25,-123.725);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#343433").s().p("AArAlIAAgrQAAgYgTAAQgJAAgFAHQgGAGAAAMIAAAqIgGAAIAAgtQAAgKgFgGQgGgGgJAAQgIAAgGAHQgGAHAAAKIAAArIgHAAIAAhHIAHAAIAAALQACgFAGgEQAGgEAHAAQASAAAEAOQAGgOASAAQAMAAAHAIQAGAHAAAMIAAAug");
	this.shape_4.setTransform(647.975,-123.825);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#343433").s().p("AgHAXIAAgtIgJAAIAAgGIAJAAIAAgQIAHAAIAAAQIAQAAIAAAGIgQAAIAAAoQAAAMACAEQADAEAJAAIADAAIAAAGIgGAAQgSAAAAgVg");
	this.shape_5.setTransform(636.225,-124.45);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#343433").s().p("AgTAeQgIgIAAgMIAAguIAHAAIAAAtQAAAKAGAGQAGAGAIAAQAJAAAGgHQAGgGAAgLIAAgrIAHAAIAABHIgHAAIAAgLQgDAGgGADQgGAEgHAAQgLAAgHgHg");
	this.shape_6.setTransform(630.575,-123.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#343433").s().p("AgaAbQgKgLAAgQQAAgQAKgKQALgLAPAAQAQAAALALQAKALAAAPQAAAQgKALQgLALgQAAQgPAAgLgLgAgUgWQgJAJAAANQAAAOAJAIQAIAJAMAAQANAAAJgJQAIgIAAgOQAAgNgIgJQgJgJgNAAQgMAAgIAJg");
	this.shape_7.setTransform(622.575,-123.725);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#343433").s().p("AgYApQgKgLAAgQQAAgQAKgLQAJgLAPAAQATAAAJAQIAAgrIAHAAIAABlIgHAAIAAgOQgLAQgQAAQgPAAgKgLgAgTgIQgIAIAAAOQAAAOAIAIQAIAJALAAQANAAAHgJQAIgJAAgNQAAgOgIgJQgIgIgMAAQgLAAgIAJg");
	this.shape_8.setTransform(610.125,-125.075);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#343433").s().p("AAVAlIAAgtQAAgKgGgGQgFgGgJAAQgJAAgGAHQgGAGAAALIAAArIgHAAIAAhHIAHAAIAAALQAHgNAPAAQALAAAHAHQAIAIAAAMIAAAug");
	this.shape_9.setTransform(602.375,-123.825);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#343433").s().p("AgCAxIAAhIIAGAAIAABIgAgFgqQAAgGAFAAQAGAAAAAGQAAAFgGABQgFgBAAgFg");
	this.shape_10.setTransform(597.125,-125);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#343433").s().p("AgVAxIAAhhIArAAIAAAGIgkAAIAAAoIAgAAIAAAFIggAAIAAAug");
	this.shape_11.setTransform(592.625,-125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol50, new cjs.Rectangle(589.2,-130.2,85.39999999999998,11.899999999999991), null);


(lib.Symbol49 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AgjA5IAHgTQANAGAOAAQAZAAAAgTIAAgEQgJAMgRAAQgVAAgMgNQgNgOAAgVQAAgVANgOQANgOAUAAQAKAAAIAFQAHADACAFIAAgKIAYAAIAABQQAAAugyAAQgSAAgQgIgAgQgiQgGAGAAANQAAAMAHAHQAGAHAKABQALgBAGgHQAHgHAAgMQAAgMgHgHQgHgIgLAAQgJAAgHAIg");
	this.shape.setTransform(385.325,-13.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AAQAwIAAg4QAAgHgEgFQgFgEgGAAQgIAAgEAFQgFAEABAIIAAA3IgZAAIAAhcIAYAAIAAALQAIgOARAAQAgAAAAAqIAAA1g");
	this.shape_1.setTransform(375.05,-15.625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgLBBIAAhcIAXAAIAABcgAgJgoQgFgEAAgGQAAgGAFgEQAEgEAFAAQAHAAADAEQAEAEABAGQgBAGgEAEQgDAEgHAAQgFAAgEgEg");
	this.shape_2.setTransform(367.7,-17.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AAOBAIgfgwIAAAwIgZAAIAAh/IAZAAIAABJIAdgmIAcAAIghApIAkAzg");
	this.shape_3.setTransform(361.175,-17.275);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AAQAwIAAg4QAAgHgFgFQgEgEgGAAQgIAAgEAFQgEAEgBAIIAAA3IgYAAIAAhcIAYAAIAAALQAJgOAQAAQAgAAAAAqIAAA1g");
	this.shape_4.setTransform(350.95,-15.625);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#333333").s().p("AgdApQgLgJAAgOQAAgOAKgIQAKgIARAAQAKAAAJAFIAAgGQAAgNgQAAQgMAAgNAGIgKgRQARgLATAAQAoAAAAAkIAAA6IgWAAIgCgGQgHAJgPAAQgPAAgJgIgAgLAIQgEAEAAAFQAAAGAEAEQAFADAGAAQAQAAAAgNQAAgNgQAAQgGAAgFAEg");
	this.shape_5.setTransform(340.925,-15.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#333333").s().p("AgqA+IAAh7IAoAAQASAAALAJQAMAJAAAPQAAASgPAJQATAHAAAUQAAARgNAKQgMAJgSAAgAgQApIAPAAQAHAAAFgFQAGgEAAgIQAAgHgGgEQgFgFgHAAIgPAAgAgQgLIAOAAQAGAAAEgEQAFgEAAgHQAAgGgFgEQgEgEgGAAIgOAAg");
	this.shape_6.setTransform(331.575,-17.075);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#333333").s().p("AgjAfIAPgMQAJAKALAAQAMAAAAgJQAAgEgVgJQgXgIAAgTQAAgNAKgIQAKgHAOAAQAVAAALAQIgQANQgIgJgJAAQgJAAAAAHQAAAGAVAIQAXAIAAASQAAAOgLAIQgKAIgPAAQgYAAgLgSg");
	this.shape_7.setTransform(317.725,-15.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#333333").s().p("AgjAfIAPgMQAJAKAMAAQALAAAAgJQAAgEgVgJQgWgIAAgTQAAgNAKgIQAJgHAOAAQAWAAAKAQIgQANQgIgJgJAAQgJAAAAAHQAAAGAWAIQAWAIAAASQAAANgLAJQgKAIgPAAQgYAAgLgSg");
	this.shape_8.setTransform(309.875,-15.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#333333").s().p("AgfAkQgOgOAAgVQAAgVANgOQANgOATAAQAWAAAMAOQAMANAAAWIAAAFIhCAAQABAKAHAFQAHAHAJAAQAQAAAHgMIAQANQgDAGgJAGQgMAIgPAAQgWAAgNgNgAgNgWQgFAFgBAIIAoAAQgBgIgFgGQgGgEgIAAQgIgBgGAGg");
	this.shape_9.setTransform(300.975,-15.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#333333").s().p("AAQAwIAAg4QAAgHgEgFQgFgEgGAAQgHAAgFAFQgEAEAAAIIAAA3IgZAAIAAhcIAZAAIAAALQAIgOAQAAQAgAAAAAqIAAA1g");
	this.shape_10.setTransform(290.9,-15.625);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#333333").s().p("AgMBBIAAhcIAZAAIAABcgAgKgoQgDgEAAgGQAAgGADgEQAFgEAFAAQAGAAAFAEQADAEAAAGQAAAGgDAEQgFAEgGAAQgFAAgFgEg");
	this.shape_11.setTransform(283.6,-17.325);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#333333").s().p("AgjAfIAPgMQAJAKALAAQAMAAAAgJQAAgEgVgJQgXgIAAgTQAAgNAKgIQAKgHAOAAQAVAAALAQIgQANQgIgJgJAAQgJAAAAAHQAAAGAVAIQAXAIAAASQAAAOgLAIQgKAIgPAAQgYAAgLgSg");
	this.shape_12.setTransform(277.475,-15.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#333333").s().p("AgoAGIAAg1IAZAAIAAA4QAAAHAFAFQAEAFAGAAQAHAAAFgFQAEgFAAgIIAAg3IAZAAIAABcIgYAAIAAgKQgIANgRAAQggAAAAgqg");
	this.shape_13.setTransform(268.55,-15.375);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#333333").s().p("AgqA+IAAh7IAoAAQASAAALAJQAMAJAAAPQAAASgPAJQATAHAAAUQAAARgNAKQgMAJgSAAgAgQApIAPAAQAHAAAFgFQAGgEAAgIQAAgHgGgEQgFgFgHAAIgPAAgAgQgLIAOAAQAGAAAEgEQAFgEAAgHQAAgGgFgEQgEgEgGAAIgOAAg");
	this.shape_14.setTransform(258.725,-17.075);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#333333").s().p("AghAuQgSgSAAgcQAAgbASgSQATgTAbAAQAXAAAPAMIgHAWQgPgKgQAAQgQAAgLAMQgKAMgBAQQABASAKAMQALALAQAAQARAAAPgKIAHAWQgPAMgYAAQgcAAgSgTg");
	this.shape_15.setTransform(243.05,-17.075);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#333333").s().p("AgqA+IAAh7IAoAAQASAAALAJQAMAJAAAPQAAASgPAJQATAHAAAUQAAARgNAKQgMAJgSAAgAgQApIAPAAQAHAAAFgFQAGgEAAgIQAAgHgGgEQgFgFgHAAIgPAAgAgQgLIAOAAQAGAAAEgEQAFgEAAgHQAAgGgFgEQgEgEgGAAIgOAAg");
	this.shape_16.setTransform(232.475,-17.075);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#333333").s().p("AghAuQgSgSAAgcQAAgbATgSQASgTAcAAQAVAAAQAMIgHAWQgPgKgPAAQgQAAgMAMQgLAMAAAQQAAASALAMQAMALAQAAQARAAAOgKIAHAWQgPAMgXAAQgcAAgTgTg");
	this.shape_17.setTransform(221.275,-17.075);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#333333").s().p("AgvAuQgRgSgBgcQABgbARgSQATgTAcAAQAdAAASATQATATAAAaQAAAcgTASQgSATgdAAQgcAAgTgTgAgbgcQgLALAAARQAAASALAMQALALAQAAQARAAALgLQALgMAAgSQAAgQgLgMQgLgMgRAAQgQAAgLAMg");
	this.shape_18.setTransform(208.45,-17.075);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#333333").s().p("AgPAPQgGgGAAgJQAAgIAGgGQAHgHAIAAQAKAAAGAHQAGAGAAAIQAAAJgGAGQgGAHgKAAQgIAAgHgHg");
	this.shape_19.setTransform(461.125,-34.675);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#333333").s().p("AghA/QgLgHgHgKIAWgTQALAPASAAQARAAABgMQAAgHgggNQgggMAAgcQAAgSAOgLQAOgLAUAAQAgAAAPAYIgXASQgLgNgOAAQgNAAAAALQAAAHAfAMQAgAMABAbQAAATgQAMQgOAMgWAAQgSAAgPgIg");
	this.shape_20.setTransform(452.3,-39.575);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#333333").s().p("AggA/QgNgHgFgKIAUgTQANAPARAAQARAAAAgMQAAgHgfgNQgggMAAgcQAAgSAPgLQANgLAVAAQAfAAAPAYIgYASQgLgNgNAAQgNAAAAALQAAAHAgAMQAfAMAAAbQABATgQAMQgPAMgVAAQgTAAgNgIg");
	this.shape_21.setTransform(441,-39.575);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#333333").s().p("AguAzQgTgUAAgeQAAgeASgUQATgVAcAAQAfAAASAUQARATAAAgIAAAIIhfAAQABAOAKAIQAKAJAOAAQAWAAALgRIAXASQgFAKgNAJQgRALgWAAQgfAAgUgUgAgTghQgIAIgBAMIA6AAQgBgNgIgHQgIgHgMAAQgMAAgIAHg");
	this.shape_22.setTransform(428.125,-39.575);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#333333").s().p("AAXBFIAAhRQAAgKgGgHQgHgHgJAAQgKAAgHAHQgGAIAAAKIAABQIgkAAIAAiGIAjAAIAAARQAFgJAJgFQAJgGAMAAQAvAAAAA8IAABNg");
	this.shape_23.setTransform(413.575,-39.75);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#333333").s().p("AgRBeIAAiGIAjAAIAACGgAgOg6QgGgGAAgJQAAgIAGgGQAGgGAIABQAJgBAGAGQAGAGAAAIQAAAJgGAGQgGAGgJAAQgIAAgGgGg");
	this.shape_24.setTransform(403,-42.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#333333").s().p("AgzAuIAVgTQANAPASAAQARAAAAgMQAAgHgggNQgggMAAgcQAAgSAOgLQAPgLATAAQAgAAAPAYIgXASQgKgNgPAAQgNAAAAALQAAAHAfAMQAgAMABAbQAAATgPAMQgPAMgWAAQgiAAgRgZg");
	this.shape_25.setTransform(394.15,-39.575);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#333333").s().p("Ag6AJIAAhNIAkAAIAABRQAAALAHAHQAGAGAJAAQAKAAAHgHQAHgHAAgLIAAhQIAjAAIAACGIgjAAIAAgQQgEAHgJAGQgLAGgLAAQgvAAAAg8g");
	this.shape_26.setTransform(381.275,-39.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#333333").s().p("AgkBOIAAANIghAAIAAi5IAkAAIAABCQADgGAJgFQAMgHAPAAQAdAAASAUQARAUAAAeQAAAfgSAUQgTAUgdAAQgXAAgRgRgAgYgEQgKAKAAATQAAAQAJALQAKALAPAAQAPAAAJgKQAKgLAAgRQAAgSgJgKQgKgLgPAAQgPAAgJAKg");
	this.shape_27.setTransform(366.375,-41.975);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#333333").s().p("AgjBFIAAiGIAjAAIAAAUQAJgXAbAAIAAAkQgkAAAAArIAAA6g");
	this.shape_28.setTransform(347.175,-39.75);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#333333").s().p("Ag6AJIAAhNIAkAAIAABRQgBALAIAHQAFAGAKAAQAKAAAHgHQAGgHAAgLIAAhQIAkAAIAACGIgjAAIAAgQQgMATgXAAQgwAAABg8g");
	this.shape_29.setTransform(334.9,-39.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#333333").s().p("Ag0AzQgUgUAAgeQAAgeAVgUQAVgVAeAAQAfAAAVAVQAVAUAAAeQAAAegVAUQgUAUggAAQgfAAgVgUgAgagbQgLALAAARQAAARALAKQALALAPAAQAQAAALgLQAKgKAAgRQAAgQgKgMQgLgLgQAAQgPAAgLALg");
	this.shape_30.setTransform(319.725,-39.575);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#333333").s().p("AgiBaIATgxIg1iDIAnAAIAeBZIAehZIAmAAIhFC0g");
	this.shape_31.setTransform(304.7,-37.25);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#333333").s().p("Ag0BSIALgcQAQAJAXAAQAkAAAAgaIAAgGQgDAFgJAFQgMAHgOAAQgeAAgSgUQgRgTAAgfQAAgfASgUQATgUAdAAQAOAAAMAHQAJAFAEAGIAAgOIAiAAIAAB0QAABDhIAAQgcAAgWgMgAgXgzQgKALAAASQAAASAKAKQAJAKAPAAQAPAAAKgKQAJgKAAgSQAAgRgJgLQgKgLgQAAQgOAAgJAKg");
	this.shape_32.setTransform(282.925,-37.275);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#333333").s().p("AAXBFIAAhRQAAgKgGgHQgHgHgJAAQgKAAgHAHQgGAIAAAKIAABQIgkAAIAAiGIAjAAIAAARQAFgJAJgFQAJgGAMAAQAvAAAAA8IAABNg");
	this.shape_33.setTransform(268.025,-39.75);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#333333").s().p("AgRBeIAAiGIAjAAIAACGgAgOg6QgGgGAAgJQAAgIAGgGQAGgGAIABQAJgBAGAGQAGAGAAAIQAAAJgGAGQgGAGgJAAQgIAAgGgGg");
	this.shape_34.setTransform(257.45,-42.2);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#333333").s().p("AAYBFIAAhRQgBgKgGgHQgHgHgJAAQgKAAgHAHQgGAIAAAKIAABQIgkAAIAAiGIAjAAIAAARQAFgJAIgFQAKgGAMAAQAwAAAAA8IAABNg");
	this.shape_35.setTransform(247.05,-39.75);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#333333").s().p("AAYBFIAAhRQAAgKgHgHQgHgHgJAAQgKAAgHAHQgGAIAAAKIAABQIgkAAIAAiGIAjAAIAAARQAFgJAJgFQAJgGAMAAQAvAAAAA8IAABNg");
	this.shape_36.setTransform(232.475,-39.75);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#333333").s().p("Ag6AJIAAhNIAkAAIAABRQAAALAHAHQAGAGAJAAQAKAAAHgHQAGgHAAgLIAAhQIAkAAIAACGIgjAAIAAgQQgEAHgJAGQgLAGgLAAQgvAAAAg8g");
	this.shape_37.setTransform(217.925,-39.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#333333").s().p("AgjBFIAAiGIAjAAIAAAUQAJgXAbAAIAAAkQgkAAAAArIAAA6g");
	this.shape_38.setTransform(206.375,-39.75);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#333333").s().p("AAXBFIAAhRQAAgKgGgIQgHgGgJAAQgKAAgHAHQgGAIAAAKIAABQIgkAAIAAiGIAjAAIAAARQAFgJAJgFQAJgGAMAAQAvAAAAA9IAABMg");
	this.shape_39.setTransform(404.425,-65.75);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#333333").s().p("AgRBeIAAiGIAjAAIAACGgAgOg6QgGgGAAgJQAAgIAGgGQAGgFAIAAQAJAAAGAFQAGAGAAAIQAAAJgGAGQgGAGgJAAQgIAAgGgGg");
	this.shape_40.setTransform(393.85,-68.2);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#333333").s().p("Ag6AJIAAhNIAkAAIAABRQAAALAHAHQAGAGAJAAQAKAAAHgHQAHgHAAgLIAAhQIAjAAIAACGIgjAAIAAgQQgLATgYAAQgvAAAAg8g");
	this.shape_41.setTransform(376.975,-65.4);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#333333").s().p("AgzAzQgVgUAAgeQAAgeAVgUQAVgVAeAAQAfAAAVAVQAVAUAAAeQAAAegVAUQgUAUggAAQgfAAgUgUgAgagbQgLALAAARQAAARALAKQALALAPAAQAQAAALgLQALgKAAgRQAAgQgLgMQgLgLgQAAQgPAAgLALg");
	this.shape_42.setTransform(361.8,-65.575);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#333333").s().p("AgiBaIATgxIg1iDIAnAAIAeBYIAehYIAlAAIhEC0g");
	this.shape_43.setTransform(346.8,-63.25);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#333333").s().p("Ag0BSIALgcQAQAJAXAAQAkAAAAgaIAAgGQgOARgYAAQgeAAgSgUQgRgTAAgfQAAgfASgUQATgUAdAAQAZAAAOASIAAgOIAiAAIAAB0QAABDhIAAQgcAAgWgMgAgYgzQgJALAAASQAAASAKAKQAJAKAOAAQAQAAAKgKQAJgKAAgSQAAgRgJgLQgKgLgQAAQgOAAgKAKg");
	this.shape_44.setTransform(325.025,-63.275);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#333333").s().p("AAXBFIAAhRQAAgKgGgIQgHgGgJAAQgKAAgHAHQgGAIAAAKIAABQIgkAAIAAiGIAjAAIAAARQAFgJAJgFQAJgGAMAAQAvAAAAA9IAABMg");
	this.shape_45.setTransform(310.125,-65.75);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#333333").s().p("AgRBeIAAiGIAjAAIAACGgAgOg6QgGgGAAgJQAAgIAGgGQAGgFAIAAQAJAAAGAFQAGAGAAAIQAAAJgGAGQgGAGgJAAQgIAAgGgGg");
	this.shape_46.setTransform(299.55,-68.2);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#333333").s().p("AgMBFQgLgOAAgbIAAg0IgOAAIAAgdIAOAAIAAgcIAjAAIAAAcIAZAAIAAAdIgZAAIAAAzQAAAPAFAFQAEAEALAAIAGAAIAAAeQgFABgKABQgXAAgMgOg");
	this.shape_47.setTransform(291.825,-66.9);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#333333").s().p("AgjBFIAAiGIAjAAIAAAUQAJgXAbAAIAAAkQgkAAAAArIAAA6g");
	this.shape_48.setTransform(282.625,-65.75);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#333333").s().p("Ag0AzQgUgUAAgeQAAgeAVgUQAVgVAeAAQAfAAAVAVQAVAUAAAeQAAAegUAUQgVAUggAAQgfAAgVgUgAgagbQgKALAAARQAAARAKAKQALALAPAAQAQAAALgLQAKgKAAgRQAAgQgKgMQgLgLgQAAQgPAAgLALg");
	this.shape_49.setTransform(269.6,-65.575);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#333333").s().p("AhFBdIAAi2IAhAAIAAAOQAQgRAYAAQAdAAATAUQASATAAAfQAAAfgRAUQgSATgdAAQgOAAgNgHQgIgEgEgGIAAA+gAgZgxQgJALAAAQQAAATAKAJQAJALAPAAQAPAAAKgLQAJgKAAgSQAAgSgKgKQgJgLgPAAQgPAAgKAMg");
	this.shape_50.setTransform(253.925,-63.325);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#333333").s().p("AhFBdIAAi2IAiAAIAAAOQAEgFAIgFQANgHAOAAQAdAAATAUQASATAAAfQAAAfgRAUQgSATgdAAQgOAAgNgHQgIgEgEgGIAAA+gAgZgxQgJALAAAQQAAATAKAJQAJALAPAAQAPAAAKgLQAJgKAAgSQAAgSgKgKQgJgLgPAAQgPAAgKAMg");
	this.shape_51.setTransform(237.775,-63.325);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#333333").s().p("Ag6AJIAAhNIAkAAIAABRQAAALAGAHQAHAGAJAAQAKAAAHgHQAGgHAAgLIAAhQIAkAAIAACGIgjAAIAAgQQgMATgXAAQgvAAAAg8g");
	this.shape_52.setTransform(222.125,-65.4);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#333333").s().p("AgqBOQgMgKgGgQIAfgPQAKAXAVAAQAVAAAAgSQAAgMgmgVQgngSAAggQAAgXAPgOQAQgOAZAAQAYgBAQAPQALALAFAOIgeAOQgJgUgSAAQgIAAgFAFQgFAFAAAHQAAAMAmAUQAoARAAAfQAAAZgQAPQgRAPgcABQgZgBgRgPg");
	this.shape_53.setTransform(207.975,-67.85);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol49, new cjs.Rectangle(201.9,-77.5,261.5,70.1), null);


(lib.Symbol48 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AB7AjIAAghIgWgkIAJAAIARAeIARgeIAJAAIgWAkIAAAhgABbAjIgJgWIgbAAIgIAWIgJAAIAbhFIAIAAIAaBFgABQAFIgLgeIgLAeIAWAAgAAAAjIAAhFIAIAAIAAA+IAaAAIAAAHgAgyAjIAAhFIATAAQAKAAAGAFQAFAGAAAJQAAAGgCAFQgDADgFADQgEADgHgBIgLAAIAAAegAgqgBIALAAQAGABADgEQAEgDAAgHQAAgGgEgDQgDgEgGAAIgLAAgAhhAjIAAhFIAhAAIAAAHIgZAAIAAAXIAWAAIAAAHIgWAAIAAAZIAaAAIAAAHgAh0AjIgQgfIgMAAIAAAfIgIAAIAAhFIASAAQALAAAFAFQAGAFAAAKIgCAIQgBADgDADQgCABgEACIARAggAiQgCIAKAAQAGAAAEgCQADgEAAgGQAAgGgDgDQgDgEgIAAIgJAAg");
	this.shape.setTransform(434.475,-49.05);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol48, new cjs.Rectangle(419.2,-52.5,30.600000000000023,7), null);


(lib.Symbol33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#343433").s().p("AivB+IAUg1Ig4iOIApAAIAhBeIAiheIAnAAIhKDDgAd/BGQgSgKgJgRQgKgRAAgWQAAgWAKgRQAIgSARgKQAQgKAVAAQAXAAAQAKQAPAJAJASQAIARAAAXIAAAEIAAAFIhnAAQAAAPALAJQAKAJARAAQAJAAAIgDIAMgHQAEgEACgEIAaAUQgDAFgHAIQgIAHgMAGQgNAGgTAAQgXAAgRgKgAfCgLQgBgOgJgIQgIgIgNAAQgOAAgJAIQgIAJgBANIA/AAIAAAAgAZ6BKQgKgGgGgJQgFgKgDgLQgBgMAAgMIAAhTIAmAAIAABYQAAAMAIAHQAGAHALAAQALAAAIgIQAGgHABgMIAAhXIAmAAIAACRIglAAIAAgRQgDAFgGAFQgGAFgIADQgHADgKAAQgQAAgJgGgAToBGQgSgKgJgRQgJgRgBgWQAAgWAKgRQAJgSAQgKQAQgKAVAAQAXAAAPAKQARAJAIASQAIARAAAXIAAAEIAAAFIhnAAQAAAPALAJQALAJAQAAQAJAAAIgDIAMgHQAFgEABgEIAaAUQgDAFgIAIQgHAHgMAGQgOAGgSAAQgYAAgQgKgAUrgLQgBgOgJgIQgIgIgNAAQgOAAgJAIQgIAJgBANIA/AAIAAAAgAJ7BGQgRgKgJgRQgKgRAAgWQAAgWAKgRQAJgSAQgKQAQgKAVAAQAXAAAPAKQAQAJAJASQAIARAAAXIAAAEIAAAFIhnAAQAAAPALAJQALAJAQAAQAJAAAIgDIAMgHQAEgEADgEIAZAUQgDAFgIAIQgHAHgNAGQgNAGgSAAQgYAAgRgKgAK/gLQgBgOgJgIQgIgIgOAAQgNAAgIAIQgJAJgBANIA/AAIAAAAgACUBKQgKgGgGgJQgFgKgCgLQgCgMAAgMIAAhTIAmAAIAABYQABAMAHAHQAHAHAKAAQAMAAAHgIQAHgHAAgMIAAhXIAmAAIAACRIglAAIAAgRQgDAFgGAFQgFAFgIADQgIADgJAAQgQAAgKgGgAgRBGQgRgKgLgRQgJgRgBgWQAAgWALgRQALgSARgKQARgKAWAAQAXAAARAKQATAKAKASQAKARAAAWQAAAWgKARQgLARgRAKQgRAKgYAAQgXAAgRgKgAgEgbQgMAMAAATQABAMAEAKQAFAJAJAFQAJAGALAAQASgBALgLQALgLAAgTQABgMgGgKQgFgJgJgGQgJgGgMAAQgRABgKALgAo2BGQgRgKgLgRQgJgRgBgWQAAgWALgRQALgSARgKQASgKAWAAQAXAAARAKQATAKAKASQAKARAAAWQAAAWgKARQgLARgRAKQgRAKgYAAQgXAAgSgKgAopgbQgMAMAAATQABAMAEAKQAFAJAKAFQAJAGALAAQASgBALgLQALgLAAgTQABgMgGgKQgFgJgJgGQgJgGgMAAQgRABgLALgAwUBKQgMgGgHgLQgIgLAAgPQABgPAGgKQAIgKAMgGQANgGARgBQALABAJACQAHADAEADIAAgKQAAgKgGgGQgHgFgNgBQgLABgKADIgSAHIgPgbQALgGAPgGQAQgFAQAAQAYAAANAIQAOAHAFANQAGANgBARIAABbIgiAAIgDgJQgFAGgIADQgKAEgMAAQgPAAgNgGgAwBAPQgHAGAAAJQAAAJAHAFQAHAGALAAQAMAAAGgFQAIgGgBgJQABgKgIgFQgGgGgMAAQgMABgGAFgAyaBMQgIgDgGgFIgHgHIAAAPIglAAIAAjJIAmAAIAABHQACgDAGgEQAFgEAKgEQAIgEANAAQAWAAAPAKQAQAKAIARQAJARAAAWQgBAXgIARQgJARgRAKQgQAKgVAAQgNAAgJgEgAycgiQgJAFgEAKQgGAKAAANQABALAEAKQAEAJAJAGQAIAGAMAAQARAAAKgMQALgLgBgTQAAgTgKgMQgKgLgRgBQgLAAgIAFgA5DBGQgRgKgJgRQgJgRgBgWQABgWAIgRQAJgSARgKQAQgKAVAAQAWAAAQAKQARAJAIASQAIARAAAXIAAAEIAAAFIhnAAQABAPAKAJQALAJAQAAQAKAAAHgDIAMgHQAFgEACgEIAZAUQgDAFgIAIQgHAHgNAGQgMAGgTAAQgYAAgRgKgA3/gLQgBgOgIgIQgJgIgOAAQgNAAgIAIQgJAJgBANIA/AAIAAAAgA8yBGQgRgKgLgRQgKgRAAgWQAAgWALgRQAKgSASgKQARgKAWAAQAYAAARAKQASAKAKASQALARAAAWQAAAWgKARQgLARgRAKQgSAKgYAAQgXAAgRgKgA8mgbQgLAMAAATQAAAMAFAKQAFAJAJAFQAJAGALAAQATgBAKgLQALgLABgTQAAgMgGgKQgEgJgKgGQgIgGgNAAQgRABgLALgAYUBAQgMgPAAgeIAAg5IgQAAIAAgfIAQAAIAAgfIAmAAIAAAfIAcAAIAAAfIgcAAIAAA4QAAALACAFQADAGAEACQAGACAHAAIADAAIAEAAIAAAhIgEABIgMAAQgaAAgNgOgAOgBAQgMgPAAgeIAAg5IgQAAIAAgfIAQAAIAAgfIAmAAIAAAfIAcAAIAAAfIgcAAIAAA4QAAALADAFQACAGAEACQAGACAHAAIADAAIAEAAIAAAhIgFABIgLAAQgaAAgNgOgAb9BMIAAiRIAmAAIAAAVQAFgLAKgHQAKgHAPAAIAAAnQgVABgKAMQgIAMgBAVIAABAgAXABMIAAhYQABgMgIgHQgGgHgLAAQgMAAgHAIQgHAHAAAMIAABXIgnAAIAAiRIAmAAIAAARQAEgFAFgFQAFgFAJgDQAHgDAKAAQAPAAAKAGQAKAGAFAJQAGAKACALQACAMAAAMIAABTgARZBMIg0iRIApAAIAiBoIAhhoIAqAAIg1CRgANWBMIgfguIggAuIgpAAIAzhLIgxhGIAsAAIAbAsIAcgsIArAAIgyBGIA0BLgAIbBMIAAhYQAAgMgHgHQgHgHgKAAQgMAAgIAIQgGAHAAAMIAABXIgnAAIAAiRIAmAAIAAARQADgFAGgFQAFgFAIgDQAIgDAJAAQAQAAAKAGQAKAGAFAJQAFAKADALQACAMAAAMIAABTgAEXBMIAAiRIAnAAIAAAVQAFgLAJgHQALgHAOAAIAAAnQgUABgKAMQgJAMAAAVIAABAgAlPBMIAAhYQAAgMgHgHQgHgHgKAAQgMAAgIAIQgGAHgBAMIAABXIgmAAIAAiRIAmAAIAAARQADgFAFgFQAGgFAIgDQAIgDAJAAQAPAAALAGQAJAGAGAJQAFAKADALQACAMAAAMIAABTgArWBMIgyhLIAABLIgmAAIAAjJIAmAAIAAB1IAwg9IArAAIg0BCIA4BPgAuTBMIAAiRIAmAAIAAAVQAFgLAKgHQALgHAOAAIAAAnQgVABgJAMQgKAMABAVIAABAgA0YBMIAAhWQAAgOgGgHQgGgHgLAAQgKAAgHAHQgGAHgBAOIAABWIgmAAIAAhYQAAgMgHgHQgFgHgLAAQgLAAgGAHQgGAHgBAOIAABWIgnAAIAAiRIAnAAIAAARQACgFAFgFQAFgFAIgDQAHgDALAAQANAAALAGQAKAGAFAKQAHgKALgGQALgGAPAAQAQAAALAHQAMAHAFAMQAGAMAAAQIAABfgA+6BMIAAifIguAAIAAgkICDAAIAAAkIgtAAIAACfg");
	this.shape.setTransform(404.9,-32.625);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol33, new cjs.Rectangle(202.4,-45.2,405,25.200000000000003), null);


(lib.Symbol24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#343433").s().p("AdyCBQgPAAgOgEQgOgEgLgFIAMgeIAJAEIAOAEQAJACAKAAQALAAAJgDQAJgCAGgHQAFgGAAgLIAAgHIgGAHQgGAEgJAEQgJAEgNAAQgVAAgPgKQgQgKgJgRQgIgRgBgXQABgWAJgRQAJgRAQgKQAQgKAVAAQAMAAAJAEQAJADAGAFQAGAEACADIAAgPIAkAAIAAB/QAAAbgLAQQgKAQgSAGQgRAHgUAAIgDAAgAdbgcQgKALgBATQABAUAKALQAKALARABQARgBAKgLQAKgLAAgUQAAgSgKgMQgKgLgRgBQgRABgKALgEAjsABLQgLgEgHgHQgHgGgEgGIAWgUQAGAGAIAFQAIAEAMABQAIAAAFgEQAFgDAAgGQAAgHgHgEIgSgHQgKgEgKgFQgKgFgHgJQgHgJAAgQQAAgNAHgKQAHgJAMgGQAMgFAPAAQAOAAAKAEQAKAEAGAGQAGAGAEAGIgaATIgFgGQgEgDgFgDQgFgCgHAAQgHAAgEADQgEADAAAGQAAAHAHAEIARAHQALADAKAFQAKAFAHAIQAHAJAAAPQAAAPgHAKQgHALgNAFQgNAGgQAAQgOAAgLgEgAaGBLQgKgEgIgHQgHgGgEgGIAXgUQAFAGAIAFQAIAEAMABQAJAAAEgEQAFgDAAgGQAAgHgHgEIgRgHQgKgEgLgFQgKgFgHgJQgHgJAAgQQAAgNAHgKQAHgJAMgGQAMgFAPAAQAOAAAKAEQAKAEAHAGQAGAGAEAGIgaATIgGgGQgDgDgFgDQgFgCgHAAQgHAAgEADQgEADAAAGQAAAHAHAEIARAHQAKADAKAFQALAFAHAIQAHAJAAAPQAAAPgIAKQgHALgNAFQgMAGgQAAQgPAAgLgEgAS4BFQgQgKgJgRQgJgRAAgXQAAgWAIgRQAJgRAQgKQAPgKAVAAQANAAAJAEQAJAEAFAEQAGAEACADIAAhHIAmAAIAADJIgkAAIAAgPIgIAHQgFAFgJADQgJAEgNAAQgVAAgQgKgATHgcQgKAMAAATQAAATAKALQAKAMARAAQAMAAAIgGQAJgGAEgJQAFgKAAgLQAAgNgFgKQgFgKgJgFQgIgFgLAAQgRABgKALgAOABJQgMgGgHgLQgIgLAAgPQAAgPAHgKQAHgKANgGQANgGARgBQALABAIACQAIADAEADIAAgKQAAgKgGgGQgHgFgNgBQgLABgKADIgSAHIgPgbQALgGAPgGQAPgFARAAQAXAAAOAIQANAHAGANQAFANAAARIAABbIgiAAIgDgJQgFAGgJADQgJAEgMAAQgPAAgNgGgAOTAOQgHAGAAAJQAAAJAHAFQAHAGALAAQALAAAHgFQAHgGAAgJQAAgKgHgFQgHgGgLAAQgMABgGAFgALBBLQgKgEgIgHQgHgGgEgGIAXgUQAFAGAIAFQAIAEAMABQAJAAAEgEQAFgDAAgGQAAgHgHgEIgRgHQgKgEgLgFQgKgFgHgJQgHgJAAgQQAAgNAHgKQAHgJAMgGQAMgFAPAAQAOAAAKAEQAKAEAHAGQAGAGAEAGIgaATIgGgGQgDgDgFgDQgFgCgHAAQgHAAgEADQgEADAAAGQAAAHAHAEIARAHQAKADAKAFQALAFAHAIQAHAJAAAPQAAAPgIAKQgHALgNAFQgMAGgQAAQgPAAgLgEgAGDBFQgRgKgLgRQgKgRAAgWQAAgWALgRQAKgSASgKQARgKAXAAQAXAAARAKQASAKAKASQALARAAAWQAAAWgKARQgLARgRAKQgSAKgXAAQgXAAgSgKgAGPgcQgLAMAAATQAAAMAFAKQAFAJAJAFQAJAGAMAAQASgBALgLQALgLAAgTQAAgMgFgKQgFgJgJgGQgJgGgMAAQgSABgLALgABABJQgKgGgGgJQgFgKgCgLQgCgMAAgMIAAhTIAmAAIAABYQABAMAHAHQAHAHAKAAQAMAAAHgIQAHgHAAgMIAAhXIAmAAIAACRIglAAIAAgRQgDAFgGAFQgGAFgHADQgIADgKAAQgPAAgKgGgAiqBFQgRgKgLgRQgKgRAAgWQAAgWALgRQAKgSASgKQARgKAXAAQAXAAARAKQASAKAKASQALARAAAWQAAAWgKARQgLARgRAKQgSAKgXAAQgXAAgSgKgAiegcQgLAMAAATQAAAMAFAKQAFAJAJAFQAJAGAMAAQASgBALgLQALgLAAgTQAAgMgFgKQgFgJgJgGQgJgGgMAAQgSABgLALgAkuBLQgLgEgHgHQgHgGgEgGIAWgUQAGAGAIAFQAIAEAMABQAIAAAFgEQAFgDAAgGQAAgHgHgEIgSgHQgKgEgKgFQgKgFgHgJQgHgJAAgQQAAgNAHgKQAHgJAMgGQAMgFAPAAQAOAAAKAEQAKAEAGAGQAGAGAEAGIgaATIgFgGQgEgDgFgDQgFgCgHAAQgHAAgEADQgEADAAAGQAAAHAHAEIARAHQALADAKAFQAKAFAHAIQAHAJAAAPQAAAPgHAKQgHALgNAFQgNAGgQAAQgOAAgLgEgAoaBFQgQgKgJgRQgKgRAAgXQAAgWAJgRQAIgRAQgKQAQgKAVAAQAMAAAJAEQAJAEAGAEQAFAEACADIAAhHIAnAAIAADJIglAAIAAgPIgHAHQgGAFgJADQgJAEgMAAQgVAAgQgKgAoLgcQgLAMAAATQAAATALALQAKAMARAAQALAAAJgGQAIgGAFgJQAEgKAAgLQAAgNgFgKQgFgKgIgFQgJgFgKAAQgRABgKALgAq1BFQgRgKgJgRQgKgRAAgWQAAgWAJgRQAJgSARgKQAQgKAVAAQAWAAAQAKQAQAJAJASQAIARAAAXIAAAEIAAAFIhnAAQAAAPALAJQAKAJARAAQAJAAAIgDIAMgHQAEgEACgEIAaAUQgDAFgIAIQgHAHgNAGQgNAGgSAAQgYAAgRgKgApxgMQgBgOgJgIQgIgIgOAAQgNAAgJAIQgIAJgBANIA/AAIAAAAgAs4BLQgKgEgIgHQgHgGgEgGIAXgUQAFAGAIAFQAIAEAMABQAJAAAEgEQAFgDAAgGQAAgHgHgEIgRgHQgKgEgLgFQgKgFgHgJQgHgJAAgQQAAgNAHgKQAHgJAMgGQAMgFAPAAQAOAAAKAEQAKAEAHAGQAGAGAEAGIgaATIgGgGQgDgDgFgDQgFgCgHAAQgHAAgEADQgEADAAAGQAAAHAHAEIARAHQAKADAKAFQALAFAHAIQAHAJAAAPQAAAPgIAKQgHALgNAFQgMAGgQAAQgPAAgLgEgA0MBFQgSgKgKgRQgKgRAAgWQAAgWAKgRQALgSARgKQASgKAWAAQAXAAASAKQASAKAKASQAKARAAAWQAAAWgKARQgKARgSAKQgRAKgYAAQgXAAgRgKgA0AgcQgLAMgBATQABAMAFAKQAFAJAJAFQAJAGALAAQASgBALgLQALgLABgTQAAgMgGgKQgFgJgJgGQgJgGgMAAQgRABgLALgA3uBLQgKgEgIgHQgHgGgEgGIAXgUQAFAGAIAFQAIAEAMABQAJAAAEgEQAFgDAAgGQAAgHgHgEIgRgHQgKgEgLgFQgKgFgHgJQgHgJAAgQQAAgNAHgKQAHgJAMgGQAMgFAPAAQAOAAAKAEQAKAEAHAGQAGAGAEAGIgaATIgGgGQgDgDgFgDQgFgCgHAAQgHAAgEADQgEADAAAGQAAAHAHAEIARAHQAKADAKAFQALAFAHAIQAHAJAAAPQAAAPgIAKQgHALgNAFQgMAGgQAAQgPAAgLgEgA6FBJQgKgGgFgJQgGgKgCgLQgCgMAAgMIAAhTIAnAAIAABYQAAAMAHAHQAHAHAKAAQAMAAAHgIQAHgHAAgMIAAhXIAnAAIAACRIgmAAIAAgRQgDAFgGAFQgFAFgIADQgIADgJAAQgQAAgKgGgA8IBFQgSgKgKgRQgKgRAAgWQAAgWAKgRQALgSARgKQASgKAWAAQAQAAAMAFQALAFAHAGIgLAgQgEgEgJgFQgIgEgNgBQgMAAgJAGQgJAGgFAKQgFAJAAALQAAATAMAMQALALATABQALgBAIgEIAOgIIAKAfIgLAHQgGAEgJACQgJADgLAAQgXAAgRgKgEghIABFQgSgKgJgRQgJgRgBgWQABgWAJgRQAJgSAQgKQAQgKAVAAQAXAAAQAKQAQAJAIASQAIARAAAXIAAAEIAAAFIhnAAQABAPAKAJQALAJAQAAQAKAAAHgDIAMgHQAFgEACgEIAZAUQgDAFgHAIQgIAHgMAGQgNAGgTAAQgXAAgRgKgEggFgAMQgBgOgIgIQgJgIgNAAQgOAAgIAIQgJAJgBANIA/AAIAAAAgEgkKABCQgXgMgNgXQgOgXAAgeQAAgcANgXQANgXAWgOQAXgNAeAAQAVAAAPAFQAQAGAKAHQAKAIAGAGIgZAaIgKgJQgGgFgLgEQgKgEgOAAQgTAAgOAJQgOAJgIAOQgHAPAAASQAAAUAIAOQAIAOAOAIQAOAIASAAQAOAAAJgDQAKgDAGgEIAIgFIAAgYIglAAIAAghIBKAAIAABNQgKAJgNAHQgMAHgPAFQgPAEgVAAQgcAAgXgNgEAiLAA/QgMgPAAgeIAAg5IgQAAIAAgfIAQAAIAAgfIAmAAIAAAfIAcAAIAAAfIgcAAIAAA4QAAALACAFQADAGAEACQAFACAIAAIADAAIAEAAIAAAhIgFABIgMAAQgaAAgMgOgADTA/QgMgPAAgeIAAg5IgQAAIAAgfIAQAAIAAgfIAmAAIAAAfIAcAAIAAAfIgcAAIAAA4QAAALACAFQADAGAEACQAFACAIAAIADAAIAEAAIAAAhIgFABIgMAAQgaAAgMgOgA14A/QgMgPAAgeIAAg5IgPAAIAAgfIAPAAIAAgfIAnAAIAAAfIAbAAIAAAfIgbAAIAAA4QAAALACAFQACAGAFACQAFACAHAAIAEAAIADAAIAAAhIgEABIgMAAQgaAAgNgOgA+5A/QgMgPAAgeIAAg5IgPAAIAAgfIAPAAIAAgfIAnAAIAAAfIAbAAIAAAfIgbAAIAAA4QAAALACAFQACAGAFACQAFACAHAAIAEAAIADAAIAAAhIgEABIgMAAQgaAAgNgOgEAg3ABLIAAhYQAAgMgHgHQgHgHgKAAQgMAAgHAIQgHAHgBAMIAABXIgmAAIAAjJIAmAAIAABJIAJgKQAFgFAIgDQAIgDAJAAQAQAAAKAGQAKAGAFAJQAGAKACALQACAMAAAMIAABTgAbtBLIAAiRIAmAAIAACRgAYvBLIAAhYQAAgMgHgHQgHgHgKAAQgNAAgHAIQgGAHgBAMIAABXIgmAAIAAiRIAmAAIAAARQADgFAFgFQAGgFAIgDQAHgDAKAAQAPAAAKAGQAKAGAGAJQAFAKADALQACAMAAAMIAABTgAWRBLIAAiRIAmAAIAACRgARaBLIAAhYQAAgMgHgHQgHgHgKAAQgNAAgHAIQgGAHgBAMIAABXIgmAAIAAiRIAmAAIAAARQADgFAFgFQAGgFAIgDQAHgDAKAAQAPAAAKAGQAKAGAGAJQAFAKADALQACAMAAAMIAABTgAJqBLIAAhYQAAgMgHgHQgHgHgKAAQgNAAgHAIQgGAHgBAMIAABXIgmAAIAAiRIAmAAIAAARQADgFAFgFQAGgFAIgDQAHgDAKAAQAPAAAKAGQAKAGAGAJQAFAKADALQACAMAAAMIAABTgAEgBLIAAiRIAnAAIAACRgAgcBLIAAjJIAlAAIAADJgAuQBLIAAiRIAmAAIAACRgAvUBLIAAhWQAAgOgGgHQgGgHgLAAQgLAAgGAHQgHAHAAAOIAABWIgnAAIAAhYQAAgMgGgHQgFgHgLAAQgLAAgGAHQgHAHAAAOIAABWIgnAAIAAiRIAmAAIAAARQADgFAFgFQAFgFAIgDQAHgDAKAAQAOAAALAGQAKAGAFAKQAHgKALgGQALgGAPAAQAQAAALAHQAMAHAFAMQAGAMAAAQIAABfgAbwhaQgGgGAAgJQAAgKAGgGQAGgGAKgBQAKABAGAGQAGAGABAKQgBAJgGAGQgGAGgKABQgKgBgGgGgAWUhaQgGgGAAgJQAAgKAGgGQAGgGAKgBQAKABAGAGQAGAGABAKQgBAJgGAGQgGAGgKABQgKgBgGgGgAEjhaQgGgGAAgJQAAgKAGgGQAHgGAJgBQAKABAHAGQAGAGAAAKQAAAJgGAGQgHAGgKABQgJgBgHgGgAuNhaQgGgGAAgJQAAgKAGgGQAGgGAKgBQAKABAGAGQAGAGABAKQgBAJgGAGQgGAGgKABQgKgBgGgGg");
	this.shape.setTransform(301.425,-31.9233);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol24, new cjs.Rectangle(64.9,-44.8,473.1,25.799999999999997), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#343433").s().p("A1CCBQgPAAgOgEQgOgEgLgFIAMgeIAJAEIAOAEQAJACAKAAQALAAAJgDQAJgCAGgHQAFgGAAgLIAAgHIgGAHQgGAEgJAEQgJAEgNAAQgVAAgPgKQgQgKgJgRQgIgRgBgXQABgWAJgRQAJgRAQgKQAQgKAVAAQAMAAAJAEQAJADAGAFQAGAEACADIAAgPIAkAAIAAB/QAAAbgLAQQgKAQgSAGQgRAHgUAAIgDAAgA1ZgcQgKALgBATQABAUAKALQAKALARABQARgBAKgLQAKgLAAgUQAAgSgKgMQgKgLgRgBQgRABgKALgAi6B9IAUg1Ig4iOIApAAIAhBeIAhheIAoAAIhKDDgEAh7ABIQgHgHAAgKQAAgKAHgHQAGgGALgBQAKABAHAGQAGAHAAAKQAAAKgGAHQgHAHgKAAQgLAAgGgHgAf3BLQgLgEgHgHQgHgGgEgGIAWgUQAGAGAIAFQAIAEAMABQAIAAAFgEQAFgDAAgGQAAgHgHgEIgSgHQgKgEgKgFQgKgFgHgJQgHgJAAgQQAAgNAHgKQAHgJAMgGQAMgFAPAAQAOAAAKAEQAKAEAGAGQAGAGAEAGIgaATIgFgGQgEgDgFgDQgFgCgHAAQgHAAgEADQgEADAAAGQAAAHAHAEIARAHQALADAKAFQAKAFAHAIQAHAJAAAPQAAAPgHAKQgHALgNAFQgNAGgQAAQgOAAgLgEgAd9BLQgLgEgHgHQgHgGgEgGIAWgUQAGAGAIAFQAIAEAMABQAIAAAFgEQAFgDAAgGQAAgHgHgEIgSgHQgKgEgKgFQgKgFgHgJQgHgJAAgQQAAgNAHgKQAHgJAMgGQAMgFAPAAQAOAAAKAEQAKAEAGAGQAGAGAEAGIgaATIgFgGQgEgDgFgDQgFgCgHAAQgHAAgEADQgEADAAAGQAAAHAHAEIARAHQALADAKAFQAKAFAHAIQAHAJAAAPQAAAPgHAKQgHALgNAFQgNAGgQAAQgOAAgLgEgAbpBFQgRgKgJgRQgKgRAAgWQAAgWAJgRQAJgSARgKQAQgKAVAAQAWAAAQAKQAQAJAJASQAIARAAAXIAAAEIAAAFIhnAAQAAAPALAJQAKAJARAAQAJAAAIgDIAMgHQAEgEACgEIAaAUQgDAFgIAIQgHAHgNAGQgNAGgSAAQgYAAgRgKgActgMQgBgOgJgIQgIgIgOAAQgNAAgJAIQgIAJgBANIA/AAIAAAAgAWEBLQgKgEgIgHQgHgGgEgGIAXgUQAFAGAIAFQAIAEAMABQAJAAAEgEQAFgDAAgGQAAgHgHgEIgRgHQgKgEgLgFQgKgFgHgJQgHgJAAgQQAAgNAHgKQAHgJAMgGQAMgFAPAAQAOAAAKAEQAKAEAHAGQAGAGAEAGIgaATIgGgGQgDgDgFgDQgFgCgHAAQgHAAgEADQgEADAAAGQAAAHAHAEIARAHQAKADAKAFQALAFAHAIQAHAJAAAPQAAAPgIAKQgHALgNAFQgMAGgQAAQgPAAgLgEgATtBJQgKgGgFgJQgGgKgCgLQgCgMAAgMIAAhTIAnAAIAABYQAAAMAHAHQAHAHAKAAQAMAAAHgIQAHgHAAgMIAAhXIAnAAIAACRIgmAAIAAgRQgDAFgGAFQgFAFgIADQgIADgJAAQgQAAgKgGgARiBLQgJgDgFgFIgIgHIAAAPIgkAAIAAjJIAmAAIAABHQACgDAGgEQAFgEAJgEQAJgEANAAQAVAAAQAKQAPAKAJARQAIARAAAWQAAAXgJARQgJARgQAKQgQAKgVAAQgNAAgJgEgARggjQgJAFgFAKQgFAKAAANQAAALAFAKQAEAJAJAGQAIAGAMAAQARAAAKgMQAKgLAAgTQAAgTgKgMQgKgLgRgBQgLAAgIAFgAJwBFQgRgKgJgRQgKgRAAgWQAAgWAJgRQAJgSARgKQAQgKAVAAQAWAAAQAKQAQAJAJASQAIARAAAXIAAAEIAAAFIhnAAQAAAPALAJQAKAJARAAQAJAAAIgDIAMgHQAEgEACgEIAaAUQgDAFgIAIQgHAHgNAGQgNAGgSAAQgYAAgRgKgAK0gMQgBgOgJgIQgIgIgOAAQgNAAgJAIQgIAJgBANIA/AAIAAAAgACJBJQgKgGgGgJQgFgKgCgLQgCgMAAgMIAAhTIAmAAIAABYQABAMAHAHQAHAHAKAAQAMAAAHgIQAHgHAAgMIAAhXIAmAAIAACRIglAAIAAgRQgDAFgGAFQgGAFgHADQgIADgKAAQgPAAgKgGgAgcBFQgRgKgLgRQgKgRAAgWQAAgWALgRQAKgSASgKQARgKAWAAQAXAAARAKQASAKAKASQALARAAAWQAAAWgKARQgLARgRAKQgSAKgXAAQgWAAgSgKgAgQgcQgLAMAAATQAAAMAFAKQAFAJAJAFQAIAGAMAAQASgBALgLQALgLAAgTQAAgMgFgKQgFgJgJgGQgJgGgMAAQgRABgLALgApZBJQgMgGgHgLQgIgLAAgPQAAgPAHgKQAHgKANgGQANgGARgBQALABAIACQAIADAEADIAAgKQAAgKgGgGQgHgFgNgBQgLABgKADIgSAHIgPgbQALgGAPgGQAPgFARAAQAXAAAOAIQANAHAGANQAFANAAARIAABbIgiAAIgDgJQgFAGgJADQgJAEgMAAQgPAAgNgGgApGAOQgHAGAAAJQAAAJAHAFQAHAGALAAQALAAAHgFQAHgGAAgJQAAgKgHgFQgHgGgLAAQgMABgGAFgAsvBLQgLgEgHgHQgHgGgEgGIAWgUQAGAGAIAFQAIAEAMABQAIAAAFgEQAFgDAAgGQAAgHgHgEIgSgHQgKgEgKgFQgKgFgHgJQgHgJAAgQQAAgNAHgKQAHgJAMgGQAMgFAPAAQAOAAAKAEQAKAEAGAGQAGAGAEAGIgaATIgFgGQgEgDgFgDQgFgCgHAAQgHAAgEADQgEADAAAGQAAAHAHAEIARAHQALADAKAFQAKAFAHAIQAHAJAAAPQAAAPgHAKQgHALgNAFQgNAGgQAAQgOAAgLgEgAwWBFQgRgKgLgRQgKgRAAgWQAAgWALgRQAKgSASgKQARgKAXAAQAXAAARAKQASAKAKASQALARAAAWQAAAWgKARQgLARgRAKQgSAKgXAAQgXAAgSgKgAwKgcQgLAMAAATQAAAMAFAKQAFAJAJAFQAJAGAMAAQASgBALgLQALgLAAgTQAAgMgFgKQgFgJgJgGQgJgGgMAAQgSABgLALgA+HBFQgRgKgLgRQgKgRAAgWQAAgWALgRQAKgSASgKQARgKAXAAQAXAAARAKQASAKAKASQALARAAAWQAAAWgKARQgLARgRAKQgSAKgXAAQgXAAgSgKgA97gcQgLAMAAATQAAAMAFAKQAFAJAJAFQAJAGAMAAQASgBALgLQALgLAAgTQAAgMgFgKQgFgJgJgGQgJgGgMAAQgSABgLALgEggyABFQgSgKgKgRQgKgRAAgWQAAgWAKgRQALgSARgKQASgKAWAAQAXAAASAKQASAKAKASQAKARAAAWQAAAWgKARQgKARgSAKQgRAKgYAAQgXAAgRgKgEggmgAcQgLAMgBATQABAMAFAKQAFAJAJAFQAJAGALAAQASgBALgLQALgLABgTQAAgMgGgKQgFgJgJgGQgJgGgMAAQgRABgLALgAOVA/QgMgPAAgeIAAg5IgQAAIAAgfIAQAAIAAgfIAmAAIAAAfIAcAAIAAAfIgcAAIAAA4QAAALACAFQADAGAEACQAFACAIAAIADAAIAEAAIAAAhIgFABIgMAAQgaAAgMgOgAlkA/QgMgPAAgeIAAg5IgPAAIAAgfIAPAAIAAgfIAnAAIAAAfIAbAAIAAAfIgbAAIAAA4QAAALACAFQACAGAFACQAFACAHAAIAEAAIADAAIAAAhIgEABIgMAAQgaAAgNgOgAq5A/QgMgPAAgeIAAg5IgQAAIAAgfIAQAAIAAgfIAmAAIAAAfIAcAAIAAAfIgcAAIAAA4QAAALACAFQADAGAEACQAFACAIAAIADAAIAEAAIAAAhIgFABIgMAAQgaAAgMgOgAyBA/QgMgPAAgeIAAg5IgQAAIAAgfIAQAAIAAgfIAmAAIAAAfIAcAAIAAAfIgcAAIAAA4QAAALACAFQADAGAEACQAFACAIAAIADAAIAEAAIAAAhIgFABIgMAAQgaAAgMgOgAaJBLIAAhYQAAgMgHgHQgHgHgKAAQgNAAgHAIQgGAHgBAMIAABXIgmAAIAAiRIAmAAIAAARQADgFAFgFQAGgFAIgDQAHgDAKAAQAPAAAKAGQAKAGAGAJQAFAKADALQACAMAAAMIAABTgAXrBLIAAiRIAmAAIAACRgANLBLIgfguIggAuIgpAAIAzhLIgxhGIArAAIAcAsIAbgsIAsAAIgyBGIA0BLgAIQBLIAAhYQAAgMgHgHQgHgHgKAAQgNAAgHAIQgGAHgBAMIAABXIgmAAIAAiRIAmAAIAAARQADgFAFgFQAGgFAIgDQAHgDAKAAQAPAAAKAGQAKAGAGAJQAFAKADALQACAMAAAMIAABTgAEMBLIAAiRIAmAAIAAAVQAFgLAKgHQALgHAOAAIAAAnQgVABgJAMQgJAMAAAVIAABAgAnYBLIAAiRIAmAAIAAAVQAFgLAKgHQAKgHAPAAIAAAnQgVABgKAMQgJAMAAAVIAABAgA3GBLIAAhYQAAgMgHgHQgHgHgKAAQgNAAgHAIQgGAHgBAMIAABXIgmAAIAAiRIAmAAIAAARQADgFAFgFQAGgFAIgDQAHgDAKAAQAPAAAKAGQAKAGAGAJQAFAKADALQACAMAAAMIAABTgA5kBLIAAiRIAmAAIAACRgA6iBLIgxhLIAABLIgmAAIAAjJIAmAAIAAB1IAwg9IArAAIg0BCIA4BPgEgjMABLIAAjDIAnAAIAACgIBAAAIAAAjgEAh5AAUIAAgOQAAgKAFgJQAEgIAHgHIANgMQAGgGAFgGQAEgHABgIQAAgIgHgHQgGgGgLAAQgHAAgFADQgFADgDAEIgFAHIgfgNQADgIAHgJQAGgJAMgHQALgGASAAQASAAAOAGQAOAHAIANQAIAMAAAQQAAAMgFAKQgEAJgHAHIgOANQgHAGgFAGQgEAGgBAIIAAAMgAXuhaQgGgGAAgJQAAgKAGgGQAGgGAKgBQAKABAGAGQAGAGABAKQgBAJgGAGQgGAGgKABQgKgBgGgGgA5hhaQgGgGAAgJQAAgKAGgGQAGgGAKgBQAKABAGAGQAGAGABAKQgBAJgGAGQgGAGgKABQgKgBgGgGg");
	this.shape.setTransform(420.475,-7.1733);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(195.2,-20,450.59999999999997,25.7), null);


// stage content:
(lib.OCBC_728x90_v3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		if (myCounter<=1){
			this.rplay.addEventListener("click", fl_MouseClickHandler.bind(this));
			
			this.ctaBTN.addEventListener("click", f2_MouseClickHandler.bind(this));
		}
		
		function fl_MouseClickHandler()
		{
			this.gotoAndPlay(1);
		}
		
		function f2_MouseClickHandler()
		{
			window.open(clickTag, "_blank");
		}
	}
	this.frame_348 = function() {
		myCounter++;
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(348).call(this.frame_348).wait(1));

	// Layer_11
	this.rplay = new lib.Symbol51();
	this.rplay.setTransform(680.05,18.25,1.3088,1,0,0,0,17,10.8);
	this.rplay._off = true;
	new cjs.ButtonHelper(this.rplay, 0, 1, 2, false, new lib.Symbol51(), 3);

	this.timeline.addTween(cjs.Tween.get(this.rplay).wait(339).to({_off:false},0).wait(10));

	// Layer_1
	this.ctaBTN = new lib.Symbol51();
	this.ctaBTN.setTransform(364,45.2,21.4108,4.1862,0,0,0,17,10.8);
	new cjs.ButtonHelper(this.ctaBTN, 0, 1, 2, false, new lib.Symbol51(), 3);

	this.timeline.addTween(cjs.Tween.get(this.ctaBTN).wait(349));

	// replay
	this.instance = new lib.Symbol48();
	this.instance.setTransform(264.35,73.8,1,1,0,0,0,17.8,8);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(320).to({_off:false},0).to({alpha:1},19).wait(10));

	// find more
	this.instance_1 = new lib.Symbol50();
	this.instance_1.setTransform(69.1,179.45,1,1,0,0,0,48.8,6.8);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(301).to({_off:false},0).to({alpha:1},19).wait(29));

	// supporting
	this.instance_2 = new lib.Symbol49();
	this.instance_2.setTransform(131.4,125.3,1,1,0,0,0,110.6,35.2);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(282).to({_off:false},0).to({alpha:1},19).wait(48));

	// text3
	this.instance_3 = new lib.Symbol33();
	this.instance_3.setTransform(99.95,152.5,1,1,0,0,0,77.7,58);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(188).to({_off:false},0).to({y:138.5,alpha:1},19,cjs.Ease.quadOut).wait(61).to({alpha:0},14,cjs.Ease.quadOut).to({_off:true},1).wait(66));

	// text2
	this.instance_4 = new lib.Symbol24();
	this.instance_4.setTransform(223.25,150.35,1,1,0,0,0,63.9,58);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(93).to({_off:false},0).to({y:137.55,alpha:1},20,cjs.Ease.quadOut).wait(61).to({alpha:0},13,cjs.Ease.quadOut).to({_off:true},1).wait(161));

	// text1
	this.instance_5 = new lib.Symbol1();
	this.instance_5.setTransform(151,89.9,1,1,0,0,0,121,25);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(11).to({_off:false},0).to({y:79.5,alpha:1},17,cjs.Ease.quadOut).wait(50).to({alpha:0},15,cjs.Ease.quadOut).to({_off:true},1).wait(255));

	// bg
	this.instance_6 = new lib.Symbol52();
	this.instance_6.setTransform(364,45,1,1,0,0,0,364,45);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({alpha:1},11).wait(338));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(364,45,364.1,45);
// library properties:
lib.properties = {
	id: '4C67F3A136A92E4E81338A9018FE5B2A',
	width: 728,
	height: 90,
	fps: 28,
	color: "#F2F2F2",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.StageGL();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['4C67F3A136A92E4E81338A9018FE5B2A'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;