(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol71 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FDC02A").s().p("AALA3IgHgOQgEgLgMgGQgMgHgLABIgQABQgMABgBgCQAAgDAKgFIAPgHQAKgDAHgMQAGgMgBgMIgBgQQgBgLACgBQADAAAFAKIAHAPQAEAKALAGQAMAHAMgBIAQgBQALgCABADQABADgLAFIgOAHQgLADgGAMQgHAMABALIACARQABALgDABIAAAAQgDAAgEgKg");
	this.shape.setTransform(6.4782,6.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol71, new cjs.Rectangle(0,0,13,13), null);


(lib.Symbol70 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FDC02A").s().p("AAABCIgFgSQgDgNgMgLQgMgKgNgCIgTgCQgOgBgBgDQABgEANgCIASgEQANgEALgMQAKgMACgOIACgSQABgOADAAQAEAAACANIAFASQADANAMALQAMAKANACIATACQAOABABAEQAAADgOACIgTAFQgNADgKAMQgLAMgBAOIgCASQgBAOgDAAQgDAAgDgNg");
	this.shape.setTransform(7.95,7.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol70, new cjs.Rectangle(0,0,15.9,15.9), null);


(lib.Symbol69 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FDC02A").s().p("AgfBDQgDgCAEgMIAFgRQADgMgFgOQgFgNgKgHIgPgKQgKgIABgCQACgDAMADIARAFQAMADAOgFQANgFAHgKIAKgOQAIgLACACQADABgDAMIgFARQgDAMAFAOQAFANAKAIIAOAKQALAHgCADQgBADgMgEIgRgFQgMgDgOAFQgNAFgIAKIgKAPQgGAJgDAAIgBAAg");
	this.shape.setTransform(6.6548,6.6452);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol69, new cjs.Rectangle(0,0,13.3,13.3), null);


(lib.Symbol68 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FDC02A").s().p("AgHAsIgBgNQAAgJgIgIQgGgJgKgCIgLgDQgKgBAAgDQAAgCAKgBIAMgBQAKAAAIgHQAJgHACgJIACgNQADgJABABQADAAABAJIABANQABAJAHAIQAGAJAKACIAMACQAJADAAACQAAACgKABIgNABQgIABgJAHQgJAGgCAJIgDANQgBAJgDAAQgCAAgBgKg");
	this.shape.setTransform(5.35,5.3487);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol68, new cjs.Rectangle(0,0,10.7,10.7), null);


(lib.Symbol67 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("ApLGlIAPgnIgphmIAeAAIAXBEIAYhEIAdAAIg2CNgAIsGAQgIgDgFgEQgGgEgCgFIAQgOQAEAEAFAEQAGADAJAAQAGAAADgCQADgDABgEQgBgFgFgDQgEgDgIgCIgOgGQgIgEgFgHQgFgGAAgMQAAgJAFgHQAFgHAJgEQAIgDALAAQAKAAAHADQAHACAFAFIAHAIIgSAOIgEgFIgHgEQgDgBgFAAQgFAAgDACQgDACAAAEQAAAFAFADIANAFIAOAGQAIADAFAHQAFAGAAALQAAAKgGAIQgFAHgJAEQgJAEgLAAQgLAAgHgDgAHVGAQgIgDgFgEQgGgEgCgFIAQgOQAEAEAFAEQAGADAJAAQAGAAADgCQADgDABgEQgBgFgFgDQgEgDgIgCIgOgGQgIgEgFgHQgFgGAAgMQAAgJAFgHQAFgHAJgEQAIgDALAAQAKAAAHADQAHACAFAFIAHAIIgSAOIgEgFIgHgEQgDgBgFAAQgFAAgDACQgDACAAAEQAAAFAFADIANAFIAOAGQAIADAFAHQAFAGAAALQAAAKgGAIQgFAHgJAEQgJAEgLAAQgLAAgHgDgAFrF8QgNgHgGgMQgHgMAAgQQAAgQAHgNQAGgMAMgHQALgHAPAAQAQAAAMAGQALAHAGANQAGAMAAARIAAADIAAADIhKAAQABALAHAHQAIAGALAAQAHAAAGgCIAIgFIAFgFIASANQgCAEgFAGQgGAFgJAEQgJAEgNAAQgRAAgMgHgAGbFBQgBgJgGgGQgGgGgJAAQgKAAgGAGQgGAGgBAJIAtAAIAAAAgABsGAQgIgDgFgEQgFgEgDgFIAQgOQAEAEAGAEQAGADAIAAQAGAAAEgCQADgDAAgEQAAgFgFgDQgFgDgHgCIgPgGQgHgEgFgHQgFgGAAgMQAAgJAFgHQAFgHAIgEQAJgDALAAQAKAAAHADQAHACAEAFIAIAIIgTAOIgEgFIgGgEQgEgBgFAAQgEAAgDACQgDACAAAEQAAAFAFADIAMAFIAPAGQAHADAFAHQAFAGAAALQAAAKgFAIQgFAHgJAEQgKAEgLAAQgKAAgIgDgAAAF/QgGgEgEgHQgEgGgBgJQgCgIAAgIIAAg9IAbAAIAABAQAAAJAFAFQAFAEAHABQAJgBAFgFQAFgFAAgJIAAg/IAbAAIAABpIgbAAIAAgMQgCADgEAEIgJAFQgGACgHAAQgLAAgHgEgAhiGBQgHgDgEgDIgFgFIAAALIgaAAIAAiRIAcAAIAAAzIAFgFQAEgDAGgDQAHgCAJAAQAPAAALAHQALAGAGANQAGAMAAARQAAAQgGAMQgHAMgLAHQgMAHgPAAQgJAAgGgCgAhkEyQgGADgEAHQgDAHAAAKQAAAIADAHQADAHAGAEQAGAEAJAAQAMAAAHgIQAHgIAAgOQAAgOgHgIQgHgJgMAAQgIAAgGAEgAljF/QgHgEgEgHQgEgGgCgJQgBgIAAgIIAAg9IAbAAIAABAQABAJAFAFQAFAEAHABQAIgBAFgFQAFgFAAgJIAAg/IAcAAIAABpIgbAAIAAgMQgCADgEAEIgKAFQgFACgHAAQgLAAgHgEgAnaF8QgMgHgHgMQgIgMAAgQQAAgQAIgNQAHgMANgHQAMgHAQAAQARAAAMAHQANAHAHAMQAIANAAAQQAAAQgHAMQgIAMgMAHQgNAHgRAAQgQAAgNgHgAnRE3QgIAIAAAOQAAAJAEAHQADAGAHAEQAGAEAIAAQANAAAIgIQAIgJAAgNQAAgJgEgHQgDgHgHgEQgGgEgJAAQgMAAgIAJgAEmGBIAAhAQAAgJgFgFQgFgFgHAAQgJABgFAFQgFAFAAAJIAAA/IgcAAIAAhpIAcAAIAAAMQACgDAEgEQAEgDAFgCQAGgCAHAAQALAAAHAEQAHAEAEAHQAEAGABAJQACAIAAAIIAAA9gAC1GBIAAhpIAcAAIAABpgAkGGBIAAhpIAcAAIAAAPQADgIAHgEQAIgFAKAAIAAAcQgPAAgHAJQgGAIAAAQIAAAugAC3EKQgEgEAAgHQAAgHAEgEQAFgFAHAAQAHAAAEAFQAFAEAAAHQAAAHgFAEQgEAFgHAAQgHAAgFgFgAD8CgQgMgHgHgMQgIgMAAgQQAAgQAIgNQAHgMANgHQAMgHAQAAQARAAAMAHQANAHAHAMQAIANAAAQQAAAQgHAMQgIAMgMAHQgNAHgRAAQgQAAgNgHgAEFBbQgIAIAAAOQAAAJAEAHQADAGAHAEQAGAEAIAAQANAAAIgIQAIgJAAgNQAAgJgEgHQgDgHgHgEQgGgEgJAAQgMAAgIAJgAhgCgQgMgHgHgMQgIgMAAgQQAAgQAIgNQAHgMANgHQAMgHAQAAQARAAAMAHQANAHAHAMQAIANAAAQQAAAQgHAMQgIAMgMAHQgNAHgRAAQgQAAgNgHgAhXBbQgIAIAAAOQAAAJAEAHQADAGAHAEQAGAEAIAAQANAAAIgIQAIgJAAgNQAAgJgEgHQgDgHgHgEQgGgEgJAAQgMAAgIAJgAlHCjQgHgEgEgHQgEgGgBgJQgCgIAAgIIAAg9IAcAAIAABAQAAAJAFAFQAFAEAHABQAJgBAFgFQAFgFAAgJIAAg/IAbAAIAABpIgbAAIAAgMQgCADgEAEIgJAFQgGACgHAAQgLAAgHgEgAnvCgQgMgHgHgMQgIgMAAgQQAAgQAIgNQAHgMANgHQAMgHAQAAQARAAAMAHQANAHAHAMQAIANAAAQQAAAQgHAMQgIAMgMAHQgNAHgRAAQgQAAgNgHgAnmBbQgIAIAAAOQAAAJAEAHQADAGAHAEQAGAEAIAAQANAAAIgIQAIgJAAgNQAAgJgEgHQgDgHgHgEQgGgEgJAAQgMAAgIAJgApNCkQgIgDgFgEQgFgEgDgFIAQgOQAEAEAGAEQAGADAIAAQAGAAAEgCQADgDAAgEQAAgFgFgDQgFgDgHgCIgPgGQgHgEgFgHQgFgGAAgMQAAgJAFgHQAFgHAIgEQAJgDALAAQAKAAAHADQAHACAEAFIAIAIIgTAOIgEgFIgGgEQgEgBgFAAQgEAAgDACQgDACAAAEQAAAFAFADIAMAFIAPAGQAHADAFAHQAFAGAAALQAAAKgFAIQgFAHgJAEQgKAEgLAAQgKAAgIgDgAjeCcQgJgLAAgVIAAgpIgLAAIAAgXIAMAAIAAgWIAbAAIAAAWIAUAAIAAAXIgUAAIAAAoQAAAIACAEQABAEAEABQADACAFAAIADAAIACAAIAAAXIgDABIgJAAQgSAAgJgKgAFhClIAAhpIAcAAIAAAPQADgIAHgEQAIgFAKAAIAAAcQgPAAgHAJQgGAIAAAQIAAAugACrClIAAhSIgLAAIAAgXIALAAIAAgEQAAgNAFgIQAGgIAIgEQAJgDAKAAIAGAAIAEABIAAAXIgDAAIgDgBQgHAAgEAEQgDADAAAHIAAADIASAAIAAAXIgSAAIAABSgABEClIAAhAQAAgJgFgFQgFgFgHAAQgJABgFAFQgFAFAAAJIAAA/IgcAAIAAhpIAcAAIAAAMQACgDAEgEQAEgDAFgCQAGgCAHAAQALAAAHAEQAHAEAEAHQAEAGABAJQACAIAAAIIAAA9gAinClIAAhpIAcAAIAABpgAmKClIAAiRIAcAAIAACRgAikAuQgFgEAAgHQAAgHAFgEQAEgFAHAAQAHAAAFAFQAEAEAAAHQAAAHgEAEQgFAFgHAAQgHAAgEgFgAA/g7QgNgHgHgMQgHgMAAgQQAAgQAHgNQAIgMAMgHQANgHAQAAQAQAAANAHQAMAHAIAMQAHANAAAQQAAAQgHAMQgHAMgNAHQgNAHgQAAQgRAAgMgHgABHiAQgHAIgBAOQAAAJAEAHQAEAGAGAEQAHAEAIAAQANAAAIgIQAHgJABgNQAAgJgEgHQgEgHgGgEQgHgEgIAAQgNAAgIAJgAiWg7QgNgHgHgMQgHgMAAgQQAAgQAHgNQAHgMANgHQAMgHAQAAQAMAAAIADQAIAEAFAEIgHAXIgKgHQgGgDgJAAQgJAAgGAEQgHAEgDAHQgEAHAAAJQABANAIAIQAIAJANAAQAIAAAGgDIAKgGIAHAWIgIAFIgLAFQgGABgHAAQgRAAgMgHgAkHg7QgNgHgGgMQgHgMAAgQQAAgQAHgNQAGgMAMgHQALgHAPAAQAQAAAMAGQALAHAGANQAGAMAAARIAAADIAAADIhKAAQABALAHAHQAIAGALAAQAHAAAGgCIAIgFIAFgFIASANQgCAEgFAGQgGAFgJAEQgJAEgNAAQgRAAgMgHgAjXh2QgBgJgGgGQgGgGgJAAQgKAAgGAGQgGAGgBAJIAtAAIAAAAgAnkg7QgMgHgHgMQgIgMAAgQQAAgQAIgNQAHgMANgHQAMgHAQAAQARAAAMAHQANAHAHAMQAIANAAAQQAAAQgHAMQgIAMgMAHQgNAHgRAAQgQAAgNgHgAnbiAQgIAIAAAOQAAAJAEAHQADAGAHAEQAGAEAIAAQANAAAIgIQAIgJAAgNQAAgJgEgHQgDgHgHgEQgGgEgJAAQgMAAgIAJgApGg7QgMgHgIgMQgHgMAAgQQAAgQAIgNQAHgMAMgHQANgHAQAAQALAAAJADQAIAEAFAEIgIAXIgJgHQgHgDgIAAQgJAAgHAEQgGAEgEAHQgDAHAAAJQAAANAIAIQAIAJAOAAQAIAAAGgDIAJgGIAIAWIgIAFIgLAFQgGABgIAAQgQAAgNgHgAg+g/QgJgLAAgVIAAgpIgLAAIAAgXIALAAIAAgWIAbAAIAAAWIAUAAIAAAXIgUAAIAAAoQAAAIACAEQACAEADABQADACAGAAIACAAIADAAIAAAXIgDABIgJAAQgTAAgIgKgADkg2IAAhAQgBgJgFgFQgEgFgIAAQgIABgFAFQgFAFAAAJIAAA/IgcAAIAAhpIAbAAIAAAMQACgDAEgEQAEgDAGgCQAFgCAHAAQALAAAHAEQAHAEAEAHQAEAGACAJQABAIAAAIIAAA9gAgHg2IAAhpIAbAAIAABpgAlNg2IAAiRIAcAAIAACRgAl/g2IAAiRIAcAAIAACRgAgFitQgEgEAAgHQAAgHAEgEQAFgFAGAAQAHAAAEAFQAFAEAAAHQAAAHgFAEQgEAFgHAAQgGAAgFgFgAAJkUQgHgEgDgHQgEgGgBgJQgCgIAAgIIAAg9IAbAAIAABAQAAAJAFAFQAFAEAHABQAJgBAFgFQAFgFAAgJIAAg/IAbAAIAABpIgbAAIAAgMQgCADgEAEIgJAFQgGACgHAAQgLAAgHgEgAhskXQgNgHgHgMQgHgMAAgQQAAgQAHgNQAIgMAMgHQANgHAQAAQAQAAANAHQAMAHAIAMQAHANAAAQQAAAQgHAMQgHAMgNAHQgNAHgQAAQgRAAgMgHgAhklcQgHAIgBAOQAAAJAEAHQAEAGAGAEQAHAEAIAAQANAAAIgIQAHgJABgNQAAgJgEgHQgEgHgGgEQgHgEgIAAQgNAAgIAJgAlbkbQgJgLAAgVIAAgpIgLAAIAAgXIAMAAIAAgWIAbAAIAAAWIAUAAIAAAXIgUAAIAAAoQAAAIACAEQABAEAEABQADACAFAAIADAAIACAAIAAAXIgDABIgJAAQgSAAgJgKgABnkSIAAhpIAbAAIAAAPQAEgIAHgEQAHgFALAAIAAAcQgPAAgHAJQgHAIABAQIAAAugAjjkSIAAhAQgBgJgFgFQgFgFgHAAQgJABgFAFQgFAFAAAJIAAA/IgcAAIAAiRIAcAAIAAA0QACgDAEgEQAEgDAGgCQAFgCAHAAQALAAAHAEQAHAEAEAHQAEAGACAJQABAIAAAIIAAA9gAmYkSIAAhpIAcAAIAABpgAnqkSIgahhIgbBhIgfAAIgmiMIAfAAIAYBpIAchpIAaAAIAcBpIAYhpIAfAAIgmCMgAmVmJQgFgEAAgHQAAgHAFgEQAEgFAHAAQAHAAAFAFQAEAEAAAHQAAAHgEAEQgFAFgHAAQgHAAgEgFg");
	this.shape.setTransform(63.475,48.525);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol67, new cjs.Rectangle(0,0,135.9,94), null);


(lib.Symbol66 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#894993").s().p("AgSCAIAAj/IAlAAIAAD/g");
	this.shape.setTransform(27.65,14.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#EA2127").s().p("AgSBlIAAjJIAlAAIAADJg");
	this.shape_1.setTransform(21.95,17.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#894993").s().p("AgSBUIAAinIAlAAIAACng");
	this.shape_2.setTransform(16.325,19.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#EA2127").s().p("AgSBDIAAiFIAlAAIAACFg");
	this.shape_3.setTransform(10.65,21.05);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#894993").s().p("AgSAkIAAhHIAlAAIAABHg");
	this.shape_4.setTransform(5.1,24.075);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F0E8F1").s().p("AiPADIAAgFIEfAAIAAAFg");
	this.shape_5.setTransform(16.375,29.375);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E2D1E4").s().p("AieCeIAAk7IE8AAIAAE7g");
	this.shape_6.setTransform(15.85,15.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol66, new cjs.Rectangle(0,0,31.7,31.6), null);


(lib.Symbol65 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F0E8F1").s().p("AhjAZIBThTIB0AAQAAAxgjAhQgiAjgvgBQgwAAgjghg");
	this.shape.setTransform(46.125,22.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#EA2127").s().p("Ag6g6QAxABAhAhQAiAiAAAwIh0AAg");
	this.shape_1.setTransform(50.25,9.95);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#894993").s().p("Ag6ASIAAgBQABgvAigiQAhgjAwAAIAAB0IhRBTQgigjgBgvg");
	this.shape_2.setTransform(38,14.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F0E8F1").s().p("AhLAJIAAgRICXAAIAAARg");
	this.shape_3.setTransform(10.775,21.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F0E8F1").s().p("AiDAJIAAgRIEHAAIAAARg");
	this.shape_4.setTransform(16.425,26.175);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F0E8F1").s().p("AiDAJIAAgRIEHAAIAAARg");
	this.shape_5.setTransform(16.425,16.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F0E8F1").s().p("AiDAJIAAgRIEHAAIAAARg");
	this.shape_6.setTransform(16.425,11.125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F0E8F1").s().p("AiDAJIAAgRIEHAAIAAARg");
	this.shape_7.setTransform(16.425,6.225);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#E2D1E4").s().p("AkkCbQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAkvQAAgBAAgBQAAAAABgBQAAAAABAAQAAAAABAAIJJAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAAEvQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_8.setTransform(29.625,15.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol65, new cjs.Rectangle(0,0,59.3,31.1), null);


(lib.Symbol64 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7A3185").s().p("AgCCgIAAk/IAFAAIAAE/g");
	this.shape.setTransform(10,19.825);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#EA2127").s().p("AkJBdIACgHQAYAFAUgVQAWgcALgKQATgQAbgLQA/gYBIAUIAvANQAdAFAUgHQATgGAYgSIAlghQAegdAMgHQAZgQAbAFIAAAHQgagFgaARQgHAFgiAfQggAdgYAPQgbARgigCQgTgCgrgNQgwgMgtAGQgzAHghAgQgMALgXAbQgQAQgTAAIgLgBg");
	this.shape_1.setTransform(36.4,23.2226);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E5F6F6").s().p("AkDBPQARgFApgdQAjgXAbAAQAVAAA6AQQAwANAegJQAugNAggjQAggiAPgKQAzgkBDABIAAAHQgpAAglAOQgmAPgcAeQgdAdgTAOQgbAUgfAHQgcAGgqgMQg3gPgPgBQgegCgkAYQguAegRAFIAAAAQgDAAACgHg");
	this.shape_2.setTransform(35.9019,22.2295);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F0E8F1").s().p("AhhAFIAAgIIDDAAIAAAIg");
	this.shape_3.setTransform(22.875,7.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F0E8F1").s().p("AjsAFIAAgJIHZAAIAAAJg");
	this.shape_4.setTransform(36.725,5.225);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#7A3185").s().p("AkbACIAAgDII3AAIAAADg");
	this.shape_5.setTransform(33.85,32.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F0E8F1").s().p("AlRATIAAglIKjAAIAAAlg");
	this.shape_6.setTransform(33.8,40.55);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E2D1E4").s().p("AlDDIIAAmPIKHAAIAAGPg");
	this.shape_7.setTransform(33.85,20);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol64, new cjs.Rectangle(0,0,67.6,42.5), null);


(lib.Symbol63 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F2F2F2").s().p("Al8IGQgOABgMgIQgLgHgGgNILVAAQAjAAAagYQAZgaAAgjIAAucQAPAEAKAMQALAMAAAPIAAO3QAAASgPAMQgOAMgUAAg");
	this.shape.setTransform(50.925,65.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#337D99").s().p("Al6J0Qg2AAglgkQgmglAAg0IAAwUQAAgkAZgZQAYgaAjAAIIDAAIAADOIBYhBIBYBBIAAjOIAkAAQAaAAAWAPQAWAPAJAYQA0ACAkAlQAlAlAAAyIAAO3QAAA0gnAlQgnAkg1AAg");
	this.shape_1.setTransform(50.775,62.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#19B1AE").s().p("Al8IGQgOABgMgIQgLgHgGgNILVAAQAjAAAagYQAZgaAAgjIAAucQAPAEAKAMQALAMAAAPIAAO3QAAASgPAMQgOAMgUAAg");
	this.shape_2.setTransform(50.925,65.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FDC02A").s().p("AiDBqIAAjTIEHAAIAADTg");
	this.shape_3.setTransform(69.325,10.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol63, new cjs.Rectangle(0,0,101.6,125.7), null);


(lib.Symbol61 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AECH8QgHgDgFgEQgGgEgDgFIARgOQAEAEAFAEQAGADAIAAQAHAAADgCQADgDABgEQgBgFgFgDQgFgDgHgCIgPgGQgHgEgFgHQgFgGAAgMQAAgJAFgHQAFgHAIgEQAJgDALAAQAKAAAHADQAHACAFAFIAHAIIgSAOIgFgFIgGgEQgDgBgGAAQgEAAgDACQgDACAAAEQAAAFAFADIAMAFIAPAGQAIADAEAHQAGAGAAALQgBAKgFAIQgFAHgJAEQgKAEgLAAQgKAAgIgDgAAfH4QgNgHgGgMQgIgMAAgQQAAgQAIgNQAHgMAMgHQANgHAQAAQAQAAANAHQANAHAHAMQAIANAAAQQgBAQgGAMQgIAMgMAHQgNAHgRAAQgRAAgMgHgAAnGzQgHAIgBAOQAAAJAFAHQADAGAHAEQAGAEAIAAQANAAAIgIQAIgJAAgNQAAgJgEgHQgEgHgGgEQgHgEgIAAQgMAAgJAJgAhwH8QgHgDgFgEQgGgEgCgFIAQgOQAEAEAFAEQAGADAIAAQAHAAADgCQADgDABgEQgBgFgFgDQgFgDgHgCIgPgGQgHgEgFgHQgFgGAAgMQAAgJAFgHQAFgHAIgEQAJgDALAAQAKAAAHADQAHACAFAFIAHAIIgTAOIgDgFIgHgEQgEgBgFAAQgEAAgDACQgDACAAAEQAAAFAFADIANAFIAOAGQAIADAEAHQAFAGABALQAAAKgGAIQgFAHgJAEQgKAEgLAAQgKAAgIgDgAj8H4QgNgHgHgMQgHgMAAgQQAAgQAHgNQAIgMAMgHQAMgHARAAQALAAAJADQAHAEAFAEIgHAXIgKgHQgGgDgIAAQgKAAgGAEQgGAEgEAHQgDAHAAAJQAAANAIAIQAIAJAOAAQAHAAAGgDIAKgGIAHAWIgIAFIgLAFQgFABgIAAQgQAAgNgHgAltH4QgMgHgHgMQgGgMgBgQQABgQAGgNQAGgMAMgHQAMgHAPAAQAPAAAMAGQALAHAHANQAFAMAAARIAAADIAAADIhKAAQABALAHAHQAIAGALAAQAIAAAFgCIAJgFIAEgFIASANQgCAEgFAGQgGAFgIAEQgKAEgNAAQgRAAgMgHgAk9G9QAAgJgGgGQgHgGgJAAQgKAAgGAGQgGAGgBAJIAtAAIAAAAgAnrH4QgLgHgHgMQgGgMAAgQQAAgRAGgMQAHgNALgGQALgHAPAAQAIAAAHACQAGADAFADIAEAFIAAgzIAcAAIAACRIgaAAIAAgLIgFAFQgEADgGADQgHACgJAAQgPAAgMgHgAngGzQgHAIAAAOQAAAOAHAIQAIAIALAAQAJAAAGgEQAGgEADgHQAEgHgBgIQABgKgEgHQgDgHgHgDQgFgEgJAAQgMAAgHAJgADEH9IAAhAQgBgJgEgFQgFgFgIAAQgIABgFAFQgFAFAAAJIAAA/IgcAAIAAhpIAbAAIAAAMQACgDAFgEQADgDAGgCQAGgCAGAAQAMAAAGAEQAHAEAFAHQAEAGABAJQABAIAAAIIAAA9gAgnH9IAAhpIAcAAIAABpgAivH9IAAhpIAbAAIAABpgAglGGQgEgEAAgHQAAgHAEgEQAFgFAHAAQAHAAAEAFQAFAEAAAHQAAAHgFAEQgEAFgHAAQgHAAgFgFgAitGGQgFgEABgHQgBgHAFgEQAEgFAIAAQAGAAAFAFQAFAEgBAHQABAHgFAEQgFAFgGAAQgIAAgEgFgAC6EgQgHgDgFgEQgGgEgCgFIAQgOQAEAEAFAEQAGADAIAAQAHAAADgCQADgDABgEQgBgFgFgDQgFgDgHgCIgPgGQgHgEgFgHQgFgGAAgMQAAgJAFgHQAFgHAIgEQAJgDALAAQAKAAAHADQAHACAFAFIAHAIIgSAOIgFgFIgGgEQgDgBgGAAQgEAAgDACQgDACAAAEQAAAFAFADIAMAFIAPAGQAIADAEAHQAGAGAAALQgBAKgFAIQgFAHgJAEQgKAEgLAAQgKAAgIgDgABkEgQgIgDgGgEQgFgEgDgFIAQgOQAEAEAGAEQAGADAJAAQAFAAAEgCQADgDAAgEQAAgFgFgDQgFgDgHgCIgOgGQgIgEgFgHQgFgGAAgMQAAgJAFgHQAFgHAJgEQAIgDALAAQAKAAAHADQAHACAEAFIAIAIIgSAOIgFgFIgGgEQgEgBgEAAQgFAAgDACQgDACAAAEQAAAFAFADIANAFIAOAGQAHADAGAHQAEAGAAALQAAAKgFAIQgFAHgJAEQgKAEgKAAQgLAAgHgDgAgFEcQgNgHgGgMQgHgMgBgQQABgQAHgNQAGgMAMgHQAKgHAPAAQAQAAAMAGQALAHAGANQAGAMgBARIAAADIAAADIhIAAQABALAGAHQAHAGAMAAQAHAAAGgCIAIgFIAFgFIARANQgBAEgGAGQgFAFgJAEQgKAEgNAAQgQAAgLgHgAApDhQAAgJgGgGQgGgGgJAAQgLAAgFAGQgFAGgCAJIAsAAIAAAAgAkEEgQgIgDgFgEQgGgEgCgFIAQgOQAEAEAFAEQAHADAIAAQAGAAAEgCQADgDAAgEQAAgFgFgDQgFgDgIgCIgOgGQgHgEgGgHQgEgGAAgMQAAgJAEgHQAGgHAIgEQAJgDALAAQAJAAAIADQAGACAFAFIAIAIIgTAOIgEgFIgGgEQgEgBgFAAQgEAAgDACQgDACAAAEQAAAFAEADIANAFIAOAGQAIADAFAHQAFAGAAALQAAAKgGAIQgEAHgJAEQgKAEgLAAQgKAAgIgDgAlwEfQgHgEgEgHQgEgGgBgJQgCgIAAgIIAAg9IAcAAIAABAQAAAJAFAFQAFAEAHABQAJgBAEgFQAFgFABgJIAAg/IAbAAIAABpIgbAAIAAgMQgCADgEAEIgKAFQgFACgHAAQgLAAgHgEgAnTEhQgHgDgEgDIgFgFIAAALIgaAAIAAiRIAbAAIAAAzIAGgFQAEgDAGgDQAHgCAIAAQAQAAAKAHQALAGAHANQAGAMAAARQAAAQgHAMQgGAMgMAHQgLAHgPAAQgJAAgGgCgAnWDSQgFADgEAHQgDAHAAAKQAAAIADAHQADAHAGAEQAGAEAJAAQALAAAHgIQAIgIAAgOQAAgOgHgIQgHgJgMAAQgIAAgHAEgAhKEhIAAhAQAAgJgFgFQgFgFgIAAQgIABgFAFQgFAFAAAJIAAA/IgcAAIAAhpIAbAAIAAAMQADgDAEgEQADgDAGgCQAGgCAGAAQAMAAAGAEQAHAEAFAHQAEAGABAJQABAIAAAIIAAA9gAi7EhIAAhpIAcAAIAABpgAi5CqQgFgEAAgHQAAgHAFgEQAFgFAGAAQAIAAAEAFQAEAEAAAHQAAAHgEAEQgEAFgIAAQgGAAgFgFgADTBAQgLgHgHgMQgGgMAAgQQAAgRAGgLQAGgNAMgGQALgHAPAAQAJAAAGACQAGADAFADIAEAFIAAgzIAcAAIAACQIgaAAIAAgLIgFAFQgEADgGADQgHACgJAAQgPAAgMgHgADegEQgHAHAAAOQAAAOAHAIQAIAIALAAQAJAAAGgEQAGgEADgHQADgHAAgIQAAgKgDgHQgEgGgGgDQgFgEgJAAQgLAAgIAJgABlBAQgMgHgHgMQgGgMgBgQQABgQAGgMQAHgMALgHQAMgHAPAAQAPAAAMAGQALAHAHANQAFALAAARIAAADIAAADIhKAAQABALAHAHQAIAGALAAQAIAAAFgCIAIgFIAFgFIASANQgCAEgFAGQgGAFgIAEQgKAEgNAAQgRAAgMgHgACVAFQAAgIgHgGQgFgGgKAAQgKAAgGAGQgGAGgBAIIAtAAIAAAAgAkGBAQgMgHgHgMQgIgMAAgQQAAgQAIgMQAHgMANgHQAMgHARAAQAQAAANAHQAMAHAHAMQAIAMAAAQQAAAQgHAMQgIAMgMAHQgNAHgQAAQgRAAgNgHgAj9gEQgIAHAAAOQAAAJAEAHQAEAGAGAEQAGAEAJAAQAMAAAIgIQAIgJABgNQAAgJgFgHQgDgGgHgEQgGgEgIAAQgNAAgIAJgAAgBFIAAg/QABgIgFgFQgEgGgIAAQgIAAgEAGQgEAFAAAIIAAA/IgcAAIAAhAQAAgIgEgFQgEgFgHAAQgIAAgFAGQgFAFABAIIAAA/IgcAAIAAhoIAbAAIAAAMQABgDAEgEQAEgDAFgCQAGgCAHAAQAKAAAIAEQAHAEAEAHQAEgHAHgEQAIgEAKAAQAMAAAJAEQAIAFAEAJQADAIAAALIAABFgAigBFIAAhoIAbAAIAAAPQADgIAIgEQAHgFALAAIAAAcQgPAAgIAJQgGAHABAQIAAAugAlXBFIAAhRIgLAAIAAgXIALAAIAAgEQABgNAEgIQAGgIAJgEQAIgDALAAIAFAAIAEABIAAAXIgDAAIgDgBQgHAAgDAEQgEADAAAHIAAADIASAAIAAAXIgSAAIAABRgAmMBFIAAhAQgBgIgEgFQgFgFgHAAQgJABgFAFQgFAFAAAIIAAA/IgcAAIAAhoIAbAAIAAAMQADgDADgEQAEgDAGgCQAFgCAIAAQAKAAAIAEQAGAEAFAHQAEAGABAJQACAHAAAIIAAA9gAn9BFIAAhoIAbAAIAABogAn7gxQgFgEABgHQgBgHAFgEQAFgFAGAAQAIAAAEAFQAFAEgBAHQABAHgFAEQgEAFgIAAQgGAAgFgFgAGhibQgMgHgHgMQgGgMgBgQQABgQAGgNQAGgMAMgHQAMgHAPAAQAPAAAMAGQALAHAHANQAFAMAAARIAAADIAAADIhKAAQABALAHAHQAIAGALAAQAIAAAFgCIAJgFIAEgFIASANQgCAEgFAGQgGAFgIAEQgKAEgNAAQgRAAgMgHgAHRjWQAAgJgGgGQgHgGgJAAQgKAAgGAGQgGAGgBAJIAtAAIAAAAgADfibQgMgHgHgMQgIgMAAgQQAAgQAIgNQAHgMANgHQAMgHARAAQAQAAANAHQAMAHAHAMQAIANAAAQQAAAQgHAMQgIAMgMAHQgNAHgQAAQgRAAgNgHgADojgQgIAIAAAOQAAAJAEAHQAEAGAGAEQAGAEAJAAQAMAAAIgIQAIgJABgNQAAgJgFgHQgDgHgHgEQgGgEgIAAQgNAAgIAJgAhsibQgNgHgGgMQgHgMAAgQQAAgQAHgNQAGgMAMgHQAMgHAOAAQARAAALAGQAMAHAFANQAGAMAAARIAAADIAAADIhJAAQAAALAIAHQAHAGAMAAQAGAAAGgCIAIgFIAFgFIASANQgCAEgFAGQgFAFgKAEQgJAEgNAAQgQAAgNgHgAg8jWQAAgJgHgGQgFgGgKAAQgKAAgGAGQgGAGgBAJIAtAAIAAAAgAlGiYQgIgEgFgIQgGgIAAgLQAAgKAFgIQAFgIAJgEQAJgEANAAQAHAAAGACQAGABADADIAAgHQAAgHgFgEQgFgFgJAAQgIAAgHADIgNAFIgKgTQAHgFALgEQALgDAMAAQAQAAAKAFQAKAFAEAKQAEAJgBAMIAABCIgYAAIgCgHQgEAEgGADQgGACgJAAQgLAAgJgEgAk4jCQgGAEAAAHQAAAGAGAEQAFAEAHAAQAIAAAGgEQAEgEAAgGQAAgHgEgEQgGgEgIAAQgHAAgFAEgAFFiWIAAhpIAbAAIAAAPQADgIAIgEQAHgFALAAIAAAcQgPAAgIAJQgGAIABAQIAAAugACaiWIAAg/QAAgJgFgFQgEgGgHAAQgIAAgEAGQgFAFAAAJIAAA/IgcAAIAAhAQAAgJgEgFQgFgFgHAAQgIAAgEAGQgFAFAAAJIAAA/IgcAAIAAhpIAbAAIAAAMQACgDAEgEQAEgDAFgCQAGgCAGAAQAKAAAIAEQAHAEAEAHQAFgHAIgEQAIgEAKAAQAMAAAIAEQAIAFAEAJQAEAIAAAMIAABFgAisiWIgjg2IAAA2IgcAAIAAiRIAcAAIAABUIAhgsIAgAAIglAwIAnA5gAmEiWIAAg/QABgJgFgFQgEgGgIAAQgHAAgFAGQgFAFAAAJIAAA/IgbAAIAAhAQAAgJgFgFQgEgFgHAAQgIAAgFAGQgEAFgBAJIAAA/IgbAAIAAhpIAbAAIAAAMQACgDAEgEQADgDAGgCQAFgCAHAAQAKAAAIAEQAGAEAEAHQAFgHAIgEQAIgEALAAQALAAAJAEQAHAFAEAJQAEAIABAMIAABFgAiXlOIAOgnIgohmIAdAAIAYBEIAXhEIAdAAIg1CNgAFOl0QgJgEgFgIQgGgIABgLQAAgKAEgIQAFgIAKgEQAIgEANAAQAIAAAGACQAGABADADIAAgHQgBgHgFgEQgEgFgKAAQgIAAgGADIgOAFIgKgTQAIgFAKgEQAMgDAMAAQAQAAAKAFQAJAFAEAKQAEAJAAAMIAABCIgYAAIgCgHQgEAEgGADQgGACgJAAQgLAAgJgEgAFbmeQgFAEAAAHQAAAGAFAEQAFAEAIAAQAIAAAFgEQAFgEAAgGQAAgHgFgEQgFgEgIAAQgIAAgFAEgAD0l3QgNgHgIgMQgGgMAAgQQgBgQAIgNQAHgMANgHQAMgHAQAAQALAAAJADQAIAEAFAEIgHAXIgKgHQgGgDgJAAQgJAAgHAEQgGAEgEAHQgDAHAAAJQAAANAJAIQAHAJAOAAQAIAAAGgDIAKgGIAHAWIgIAFIgLAFQgGABgHAAQgRAAgMgHgABPl0QgHgEgEgHQgEgGgBgJQgCgIAAgIIAAg9IAbAAIAABAQABAJAFAFQAFAEAHABQAJgBAFgFQAEgFAAgJIAAg/IAcAAIAABpIgbAAIAAgMQgCADgEAEIgJAFQgGACgHAAQgLAAgHgEgAgnl3QgMgHgHgMQgIgMAAgQQAAgQAIgNQAHgMANgHQANgHAPAAQAQAAANAHQAMAHAIAMQAHANAAAQQAAAQgHAMQgHAMgNAHQgNAHgQAAQgQAAgNgHgAgem8QgIAIAAAOQAAAJAEAHQADAGAHAEQAHAEAHAAQAMAAAJgIQAHgJABgNQAAgJgFgHQgDgHgHgEQgFgEgJAAQgMAAgIAJgAl5l0QgHgEgFgHQgEgGgBgJQgBgIAAgIIAAg9IAbAAIAABAQABAJAEAFQAGAEAHABQAIgBAFgFQAFgFAAgJIAAg/IAcAAIAABpIgbAAIAAgMQgCADgFAEIgJAFQgGACgGAAQgMAAgGgEgAkRl7QgIgLgBgVIAAgpIgLAAIAAgXIAMAAIAAgWIAbAAIAAAWIAUAAIAAAXIgUAAIAAAoQAAAIACAEQABAEAEABQADACAFAAIADAAIADAAIAAAXIgEABIgJAAQgSAAgJgKgAHplyIAAhAQgBgJgFgFQgFgFgHAAQgIABgGAFQgEAFAAAJIAAA/IgcAAIAAhpIAbAAIAAAMQACgDAEgEQAEgDAGgCQAFgCAHAAQALAAAHAEQAHAEAEAHQAEAGACAJQABAIAAAIIAAA9gAn7lyIAAiMIAtAAQAOAAAKAEQALAFAFAIQAGAIAAAMQAAAJgFAIQgFAJgHAEQAKAEAFAIQAHAJAAALQgBANgHAJQgGAKgLAEQgLAFgNAAgAnfmKIASAAQAIgBAGgEQAGgFAAgJQAAgJgGgEQgGgFgIAAIgSAAgAnfnGIAQAAQAIAAAFgEQAFgFAAgHQAAgHgFgFQgFgEgIAAIgQAAg");
	this.shape.setTransform(54.1,58.125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol61, new cjs.Rectangle(0,0,135.1,116), null);


(lib.Symbol60 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E2D1E4").s().p("AgfDYQgmgnAAg1IAAl9IBOAAIgFFoQgBA0AMAeQAOAoApAhQg9AAgogqg");
	this.shape.setTransform(29.975,34.925);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#985FA0").s().p("Al+FVQhHAAgyg1Qgyg1AAhLIAAkSIhmggQgVgGgKgUQgKgTAGgVQAHgUATgKQAUgKAUAGIBHAWIAAhKIgGAAQgIAAgGgFQgGgGAAgIIAAgBQAAgJAGgGQAGgHAIAAIRcAAQAIAAAGAHQAGAGAAAJIAAABQAAAIgGAGQgGAFgIAAIgDAAIAABKIBGgWQAVgGATAKQAUAKAHAUQAGAVgKATQgKAUgVAGIhmAgIAAESQAABLgyA1QgzA1hHAAgAlDELQgogigPgnQgLgfABgzIAFlpIhPAAIAAF+QAAA0AmAoQAoAqA9AAIAAAAg");
	this.shape_1.setTransform(69.3212,34.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol60, new cjs.Rectangle(0,0,138.7,68.2), null);


(lib.Symbol59 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D3BAD6").s().p("AglCeQBEhPAAhYQAAhYg1hEQgcgkgbgQQAvARAtAjQBcBGAABXQAABYhrBOQg0Ang2AVQAigVAjgng");
	this.shape.setTransform(10.7,21.85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol59, new cjs.Rectangle(0,0,21.4,43.7), null);


(lib.Symbol58 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D3BAD6").s().p("ABPCIQglgCgfgHQhhgZAAhOQAAhMBAgxQAUgPAYgLIAUgHIgMAHQgPAKgLAPQgmAwAABNQAABNBIAaQAWAIAbACg");
	this.shape.setTransform(8.725,13.55);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol58, new cjs.Rectangle(0,0,17.5,27.1), null);


(lib.Symbol57 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D3BAD6").s().p("AgGBPQAdgvgHguQgHgughghQgRgQgQgHQAaAGAbAOQA2AeAHAuQAHAvgyAxQgZAZgaAQQAQgOAPgYg");
	this.shape.setTransform(5.7926,11.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol57, new cjs.Rectangle(0,0,11.6,23.4), null);


(lib.Symbol56 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#985FA0").s().p("AmQApQCeg7DlgVQDkgUCmAgQCnAgAFBCIxRBhQgGhCCeg9gAmSBVQgqAVghAUQCAgfBUgEIAAgyQgzADhWApgAhvhIQgNgNgCgTQgCgUALgPQALgPARgBICFgMQARgBAOANQANAMACAUQABATgLAPQgKAPgRACIiGALIgDAAQgPAAgMgLg");
	this.shape.setTransform(55.314,16.7922);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E2D1E4").s().p("AgeABQBVgoAzgDIAAAyQhUADh/AgQAhgUAqgWg");
	this.shape_1.setTransform(18.125,25.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol56, new cjs.Rectangle(0,0,110.7,33.6), null);


(lib.Symbol55 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA2127").s().p("AhDAIIAAgPICHAAIAAAPg");
	this.shape.setTransform(33.725,44.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#EA2127").s().p("AjmASIAAgjIHNAAIAAAjg");
	this.shape_1.setTransform(33.65,13.175);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#337D99").s().p("AA/DBIAAhLIg4AAIAABLIgNAAIAAhLIg3AAIAABLIiOAAIAAmBIGWAAIAAGBgAB4A2IAuAAIAAguIguAAgAAoA2IAvAAIAAguIgvAAgAhWA2IAvAAIAAguIgvAAgAimA2IAvAAIAAguIgvAAgAB4gZIAuAAIAAguIguAAgAAogZIAvAAIAAguIgvAAgAhWgZIAvAAIAAguIgvAAgAimgZIAvAAIAAguIgvAAgAB4hoIAuAAIAAgvIguAAgAAohoIAvAAIAAgvIgvAAgAhWhoIAvAAIAAgvIgvAAgAimhoIAvAAIAAgvIgvAAg");
	this.shape_2.setTransform(33.7,33.275);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#337D99").s().p("Aj4AKIAAgTIHxAAIAAATg");
	this.shape_3.setTransform(33.7,55.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AjoDqQhhhiAAiIQAAiIBhhgQBhhhCHAAQCJAABhBhQBgBgAACIQAACIhgBiQhhBgiJAAQiHAAhhhgg");
	this.shape_4.setTransform(33,33);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol55, new cjs.Rectangle(0,0,66,66), null);


(lib.Symbol52 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("Ag0GRQgIgCgFgFQgFgEgDgFIAQgOQAEAFAGADQAGADAIAAQAGAAAEgCQADgCAAgFQAAgFgFgDQgFgDgHgCIgPgGQgHgEgFgGQgFgHAAgLQAAgKAFgHQAFgHAIgDQAJgEALAAQAKAAAHADQAHADAEAEIAHAIIgSAOIgEgFIgGgDQgEgCgFAAQgEAAgDACQgDADAAAEQAAAEAFADIAMAFIAPAGQAHADAEAHQAFAHAAALQAAAKgFAHQgEAIgJADQgKAEgLAAQgKAAgIgDgAiLGRQgIgCgFgFQgFgEgDgFIAQgOQAEAFAGADQAGADAIAAQAGAAAEgCQADgCAAgFQAAgFgFgDQgFgDgHgCIgPgGQgHgEgFgGQgFgHAAgLQAAgKAFgHQAFgHAIgDQAJgEALAAQAKAAAHADQAHADAEAEIAIAIIgTAOIgEgFIgGgDQgEgCgFAAQgEAAgDACQgDADAAAEQAAAEAFADIAMAFIAPAGQAHADAFAHQAFAHAAALQAAAKgFAHQgFAIgJADQgKAEgLAAQgKAAgIgDgAj1GOQgMgIgHgMQgGgMgBgQQABgQAGgNQAHgMALgHQAMgHAPAAQAQAAALAGQAMAIAGAMQAFANAAAQIAAAEIAAACIhJAAQAAALAIAHQAHAGAMABQAHAAAFgCIAJgGIAEgFIASAOQgCADgFAGQgFAFgJAEQgKAEgNAAQgQAAgNgGgAjFFSQAAgJgGgGQgGgGgKABQgKAAgGAFQgGAGgBAJIAtAAIAAAAgAnzGRQgIgCgFgFQgGgEgCgFIAQgOQAEAFAFADQAGADAJAAQAGAAADgCQADgCABgFQgBgFgFgDQgEgDgIgCIgOgGQgIgEgFgGQgFgHAAgLQAAgKAFgHQAFgHAJgDQAIgEALAAQAKAAAHADQAHADAFAEIAHAIIgSAOIgEgFIgHgDQgDgCgFAAQgFAAgDACQgDADAAAEQAAAEAFADIANAFIAOAGQAIADAFAHQAFAHAAALQAAAKgGAHQgFAIgJADQgJAEgLAAQgLAAgHgDgApfGQQgHgEgEgGQgEgHgCgJQgBgHAAgJIAAg8IAbAAIAAA/QABAJAFAFQAFAEAHABQAIgBAFgFQAFgFAAgJIAAg+IAcAAIAABoIgbAAIAAgMQgCAEgEADIgKAFQgFACgHAAQgLAAgHgEgArDGSQgGgDgEgDIgGgFIAAALIgaAAIAAiRIAcAAIAAA0IAFgGQAEgDAHgCQAGgDAJAAQAPAAALAHQALAGAHANQAGANAAAQQAAAQgHANQgGALgMAIQgLAGgPAAQgJAAgHgCgArFFDQgGADgDAIQgEAGAAAKQAAAJAEAGQADAHAGAEQAGAEAIAAQAMAAAHgIQAIgIAAgOQAAgOgHgIQgIgJgMAAQgIAAgGAEgAk5GSIAAhAQgBgJgFgEQgEgGgIABQgIAAgFAFQgFAGAAAIIAAA/IgcAAIAAhoIAbAAIAAAMQACgEAEgEQAEgDAGgCQAFgCAHAAQALAAAHAEQAHAEAEAHQAEAGACAJQABAIAAAIIAAA9gAmrGSIAAhoIAcAAIAABogAmoEcQgFgFAAgHQAAgHAFgEQAEgEAHgBQAHABAFAEQAEAEAAAHQAAAHgEAFQgFAEgHAAQgHAAgEgEgAjpDaQgKgDgHgEIAJgVIAGADIAKACIANABQAIABAHgCQAGgCAEgFQAEgEAAgIIAAgEIgFAEQgDADgHADQgGACgJABQgQAAgLgIQgLgGgGgNQgGgMAAgQQAAgRAGgMQAHgMALgHQAMgHAPAAQAIAAAHACQAGADAEADIAGAFIAAgLIAaAAIAABcQAAATgIAMQgHALgNAEQgNAGgPgBQgLAAgLgCgAjkBrQgHAJgBAOQABANAHAJQAHAIAMAAQAMAAAIgIQAHgJAAgNQAAgOgHgJQgIgHgMgBQgMABgHAHgAAqDaIAPgnIgphmIAeAAIAXBFIAYhFIAdAAIg2CNgAESC1QgHgFgEgHQgEgGgCgIQgBgJAAgIIAAg9IAbAAIAABAQABAJAFAFQAFAFAHAAQAIAAAFgFQAFgGAAgJIAAg/IAcAAIAABpIgbAAIAAgMQgCADgEAEIgKAGQgFABgHABQgLAAgHgEgACbCxQgMgGgHgNQgIgMAAgQQAAgQAIgMQAHgNANgHQAMgHAQAAQARAAAMAHQANAHAHANQAIAMAAAQQAAAQgHAMQgIANgMAGQgNAIgRAAQgQAAgNgIgACkBsQgIAJAAANQAAAJAEAHQADAHAHAEQAGADAIAAQANAAAIgIQAIgJAAgNQAAgJgEgHQgDgHgHgEQgGgEgJAAQgMAAgIAJgAhyCxQgNgHgGgMQgHgMAAgQQAAgQAHgMQAGgNAMgHQALgHAPAAQAQAAAMAHQALAGAGANQAGANAAAQIAAADIAAAEIhKAAQABAKAHAHQAIAHALgBQAHAAAGgCIAIgFIAFgFIASANQgCAFgFAFQgGAFgJAFQgJAEgNAAQgRAAgMgIgAhCB3QgBgKgGgGQgGgGgJAAQgKABgGAFQgGAGgBAKIAtAAIAAAAgAlcC1QgJgFgFgIQgGgHAAgMQAAgKAFgIQAFgHAJgEQAJgFANAAQAIAAAGACQAFABADADIAAgHQAAgHgFgEQgFgFgJAAQgIAAgHADIgNAFIgKgTQAHgFALgEQALgDAMAAQARAAAJAFQAKAFAEAKQAEAJAAAMIAABCIgZAAIgBgHQgEAEgHADQgGACgJABQgKAAgJgEgAlPCLQgFADAAAHQAAAGAFAEQAFAEAIABQAIgBAFgEQAFgEAAgGQAAgHgFgEQgFgEgIAAQgIABgFAEgAo1C1QgJgFgFgIQgFgHAAgMQAAgKAFgIQAFgHAJgEQAJgFAMAAQAIAAAGACQAGABADADIAAgHQAAgHgFgEQgFgFgJAAQgIAAgHADIgNAFIgKgTQAHgFALgEQALgDAMAAQAQAAAKAFQAKAFAEAKQADAJAAAMIAABCIgYAAIgCgHQgEAEgGADQgGACgJABQgLAAgJgEgAooCLQgFADAAAHQAAAGAFAEQAFAEAIABQAIgBAFgEQAFgEAAgGQAAgHgFgEQgFgEgIAAQgIABgFAEgAFvC2IAAhpIAcAAIAAAQQADgJAHgEQAIgFAKAAIAAAcQgPAAgHAJQgGAIAAARIAAAtgAmaC2IAAg/QgBgKgFgFQgEgEgIAAQgIAAgFAFQgFAGAAAIIAAA/IgcAAIAAhpIAbAAIAAAMQACgDAEgDQAEgEAGgCQAFgCAHAAQALAAAHAEQAHAEAEAHQAEAGACAJQABAIAAAJIAAA8gApzC2IAAg+QAAgKgEgFQgEgGgIABQgIgBgEAGQgFAFAAAKIAAA+IgcAAIAAg/QAAgKgEgFQgEgEgIAAQgHgBgFAGQgFAFAAAKIAAA+IgcAAIAAhpIAcAAIAAAMQABgDAEgDQAEgEAFgCQAGgCAHAAQAKAAAHAEQAHAEAEAIQAFgIAIgEQAIgEAKAAQAMAAAIAEQAIAGAEAIQAEAJAAALIAABFgAmhAAIAAiNIAaAAIAAALIAFgGQAEgDAHgCQAGgDAJAAQAPAAAMAHQALAHAHAMQAGANAAAPQAAARgGANQgGALgLAIQgLAGgPABQgJAAgHgDQgGgDgEgDIgFgFIAAAwgAl6hzQgGAEgDAGQgDAHAAAIQAAAKADAHQAEAHAGADQAGAEAIAAQAMAAAHgIQAHgJAAgOQAAgNgHgJQgHgIgMAAQgJAAgGAFgAHvgpQgMgIgHgMQgGgMgBgQQABgQAGgNQAHgMALgHQAMgHAPAAQAQAAALAGQAMAIAGAMQAFAMAAASIAAADIAAACIhJAAQAAALAIAHQAHAGAMABQAHAAAFgCIAJgGIAEgFIASAOQgCADgFAGQgFAFgJAEQgKAEgNABQgQgBgNgGgAIfhlQAAgJgGgGQgGgFgKAAQgKgBgGAHQgGAGgBAIIAtAAIAAAAgAD6gpQgMgIgHgMQgGgMgBgQQABgQAGgNQAHgMALgHQAMgHAPAAQAQAAALAGQAMAIAGAMQAFAMAAASIAAADIAAACIhJAAQAAALAIAHQAHAGAMABQAHAAAFgCIAJgGIAEgFIASAOQgCADgFAGQgFAFgJAEQgKAEgNABQgQgBgNgGgAEqhlQAAgJgGgGQgGgFgKAAQgKgBgGAHQgGAGgBAIIAtAAIAAAAgACUglQgHgDgEgDIgFgFIAAALIgaAAIAAiRIAcAAIAAA0IAFgGQAEgDAGgCQAHgDAJAAQAPAAALAHQALAGAGANQAGANAAAQQAAAQgGANQgHALgLAIQgMAGgPABQgJAAgGgDgACSh0QgGADgEAIQgDAGAAAKQAAAJADAGQADAHAGAEQAGAEAJAAQAMAAAHgIQAHgIAAgOQAAgOgHgIQgHgIgMgBQgIAAgGAEgAgsgpQgMgIgHgLQgIgNAAgQQAAgQAIgNQAHgMANgHQAMgHAQAAQAQAAAMAHQANAHAHAMQAIANAAAQQAAAQgHANQgIALgMAIQgNAGgQABQgQgBgNgGgAgjhvQgIAIAAAOQAAAJAEAHQADAGAHAEQAGAEAIAAQANAAAHgIQAIgIAAgOQAAgJgEgHQgDgHgGgEQgGgDgJgBQgMABgIAIgAkRgpQgMgIgHgMQgGgMgBgQQABgQAGgNQAHgMALgHQAMgHAPAAQAQAAALAGQAMAIAGAMQAFAMAAASIAAADIAAACIhJAAQAAALAIAHQAHAGAMABQAHAAAFgCIAJgGIAEgFIASAOQgCADgFAGQgFAFgJAEQgKAEgNABQgQgBgNgGgAjhhlQAAgJgGgGQgGgFgKAAQgKgBgGAHQgGAGgBAIIAtAAIAAAAgAofgpQgNgIgHgLQgHgNAAgQQAAgQAHgNQAHgMANgHQAMgHAQAAQAMAAAIAEQAIADAFAEIgHAXIgKgHQgGgCgJgBQgJAAgGAFQgHADgDAIQgEAGAAAJQABANAIAJQAIAIANAAQAIAAAGgDIAKgGIAHAWIgIAGIgLAEQgGACgHAAQgRgBgMgGgAqQgpQgNgIgGgMQgHgMAAgQQAAgQAHgNQAGgMAMgHQALgHAPAAQAQAAAMAGQALAIAGAMQAGAMAAASIAAADIAAACIhKAAQABALAHAHQAIAGALABQAHAAAGgCIAIgGIAFgFIASAOQgCADgFAGQgGAFgJAEQgJAEgNABQgRgBgMgGgApghlQgBgJgGgGQgGgFgJAAQgKgBgGAHQgGAGgBAIIAtAAIAAAAgAGkguQgJgKAAgWIAAgpIgLAAIAAgWIALAAIAAgXIAbAAIAAAXIAUAAIAAAWIgUAAIAAAoQAAAIACAEQACAEADACQADABAGAAIACAAIADAAIAAAXIgDABIgJAAQgTABgIgLgAFhguQgJgKAAgWIAAgpIgLAAIAAgWIAMAAIAAgXIAbAAIAAAXIAUAAIAAAWIgUAAIAAAoQAAAIACAEQABAEAEACQADABAFAAIADAAIACAAIAAAXIgDABIgJAAQgSABgJgLgAh4guQgJgKAAgWIAAgpIgLAAIAAgWIALAAIAAgXIAbAAIAAAXIAUAAIAAAWIgUAAIAAAoQAAAIACAEQACAEADACQADABAGAAIACAAIADAAIAAAXIgDABIgJAAQgTABgIgLgAJLglIAAhoIAbAAIAAAOQAEgHAHgFQAHgFALAAIAAAcQgPAAgHAJQgHAJABAPIAAAugAnTglIAAhoIAcAAIAABogArtglIAAhoIAcAAIAAAOQADgHAHgFQAIgFAKAAIAAAcQgPAAgHAJQgGAJAAAPIAAAugAnQicQgFgEAAgHQAAgHAFgEQAEgEAHgBQAHABAFAEQAEAEAAAHQAAAHgEAEQgFAFgHAAQgHAAgEgFgAIOjdQgKgDgHgEIAIgVIAGACIALADIANABQAIABAGgCQAGgCAFgEQAEgFAAgIIAAgEIgFAEQgEADgGADQgHADgJgBQgPABgLgIQgMgGgGgNQgGgMAAgQQAAgRAHgMQAGgMAMgHQALgHAPAAQAJAAAGACQAHADAEADIAFAFIAAgLIAaAAIAABcQAAATgHAMQgIALgNAFQgMAEgQAAQgLAAgKgCgAISlLQgHAHAAAOQAAAOAHAJQAIAIAMAAQAMAAAHgIQAHgJAAgOQAAgNgHgIQgHgJgNAAQgLAAgIAJgAK3kGQgNgGgHgNQgHgMAAgQQAAgQAHgMQAHgNANgHQAMgHAQAAQAMAAAIADQAIAEAFAEIgHAXIgKgGQgGgDgJgBQgJABgGADQgHAEgDAHQgEAIAAAIQABAOAIAHQAIAJANAAQAIAAAGgDIAKgGIAHAXIgIAEIgLAFQgGACgHgBQgRABgMgIgAGakCQgJgFgFgIQgFgHAAgMQAAgKAFgIQAFgHAJgEQAJgFAMAAQAIAAAGACQAGABADADIAAgHQAAgHgFgEQgFgFgJABQgIAAgHACIgNAFIgKgTQAHgFALgEQALgDAMAAQAQAAAKAFQAKAFAEAKQADAJAAAMIAABCIgYAAIgCgHQgEAEgGADQgGADgJgBQgLAAgJgDgAGnktQgFAEAAAHQAAAHAFADQAFAEAIABQAIgBAFgEQAFgEAAgGQAAgHgFgEQgFgEgIAAQgIABgFADgABMkGQgNgGgHgNQgHgMAAgQQAAgQAHgMQAIgNAMgHQANgHAQAAQAQAAANAHQAMAHAIANQAHAMAAAQQAAAQgHAMQgHANgNAGQgNAIgQgBQgRABgMgIgABUlLQgHAJgBANQAAAJAEAHQAEAHAGADQAHAEAIAAQANAAAIgIQAHgJABgNQAAgJgEgHQgEgHgGgEQgHgEgIAAQgNAAgIAJgAizkBQgIgDgFgFQgFgEgDgEIAQgPQAEAFAGADQAGADAIABQAGAAAEgDQADgDAAgEQAAgFgFgCQgFgDgHgDIgPgGQgHgEgFgHQgFgGAAgMQAAgJAFgHQAFgHAIgEQAJgDALAAQAKAAAHADQAHACAEAFIAIAIIgTAOIgEgEIgGgEQgEgCgFAAQgEAAgDACQgDACAAAEQAAAFAFADIAMAFIAPAGQAHAEAFAGQAFAHAAAKQAAAKgFAIQgFAHgJAFQgKADgLAAQgKAAgIgCgAlKkGQgMgGgHgNQgGgMgBgQQABgQAGgMQAHgNALgHQAMgHAPAAQAQAAALAHQAMAGAGANQAFANAAAQIAAADIAAAEIhJAAQAAALAIAGQAHAHAMgBQAHAAAFgCIAJgFIAEgFIASAOQgCAEgFAFQgFAFgJAFQgKADgNAAQgQABgNgIgAkalAQAAgKgGgGQgGgGgKAAQgKABgGAFQgGAHgBAJIAtAAIAAAAgAoCkGQgMgGgHgNQgGgMgBgQQABgQAGgMQAHgNALgHQAMgHAPAAQAQAAALAHQAMAGAGANQAFANAAAQIAAADIAAAEIhJAAQAAALAIAGQAHAHAMgBQAHAAAFgCIAJgFIAEgFIASAOQgCAEgFAFQgFAFgJAFQgKADgNAAQgQABgNgIgAnSlAQAAgKgGgGQgGgGgKAAQgKABgGAFQgGAHgBAJIAtAAIAAAAgAJwkBIAAhpIAcAAIAABpgAFckBIAAg+QAAgKgEgFQgEgGgIABQgIgBgEAGQgFAFAAAKIAAA+IgcAAIAAg/QAAgJgEgGQgEgEgIAAQgHgBgFAGQgFAFAAAKIAAA+IgcAAIAAhpIAcAAIAAANQABgEAEgDQAEgEAFgCQAGgCAHAAQAKAAAHAEQAHAEAEAIQAFgIAIgEQAIgEAKAAQAMAAAIAEQAIAGAEAIQAEAJAAALIAABFgAAGkBIAAg/QAAgJgFgGQgEgEgHAAQgJAAgFAFQgFAGAAAIIAAA/IgcAAIAAhpIAcAAIAAANQACgEAEgDQAEgEAFgCQAGgCAHAAQAKAAAHAEQAHAEAEAHQAEAHABAIQACAIAAAIIAAA9gAmmkBIAAhpIAbAAIAAAQQAEgJAHgEQAHgFALAAIAAAcQgPAAgHAJQgHAJABAQIAAAtgApGkBIAAg/QgBgJgFgGQgFgEgHAAQgJAAgFAFQgFAGAAAIIAAA/IgcAAIAAiQIAcAAIAAA0QACgEAEgDQAEgEAGgCQAFgCAHAAQALAAAHAEQAHAEAEAHQAEAHACAIQABAIAAAIIAAA9gArSkBIAAhzIghAAIAAgZIBeAAIAAAZIghAAIAABzgAjyliIAFgDIAEgGQADgDAAgEQgHgCgDgEQgEgFAAgFQABgIAEgFQAFgEAHAAQAIAAAFAEQAFAFAAAJQAAAOgHALQgGAMgJAGgAJyl3QgEgFAAgHQAAgHAEgEQAFgFAHABQAHgBAEAFQAFAEAAAHQAAAHgFAFQgEAEgHAAQgHAAgFgEg");
	this.shape.setTransform(78.025,46.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol52, new cjs.Rectangle(0,0,163.9,94), null);


(lib.Symbol51 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F2F2F2").s().p("AipBsIAAjXIFTAAIAADXg");
	this.shape.setTransform(17,10.75);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,34,21.5);


(lib.Symbol50 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AnnAEIAAgHIPPAAIAAAHg");
	this.shape.setTransform(48.8,13.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AgbAgQgLgMAAgUQAAgSALgNQAMgMAPAAQASAAALAMQALAMgBASIAAACIhFAAQAAARAKAJQAJAJAOAAQARAAAMgOIAEAEQgLASgWAAQgRAAgNgMgAgTgcQgJAJgBAOIA8AAQAAgOgKgJQgIgHgNAAQgLAAgIAHg");
	this.shape_1.setTransform(93.05,7.425);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgQArIAAhTIAIAAIAAAPQACgGAGgFQAHgGAKAAIAAAIQgZAAAAAiIAAArg");
	this.shape_2.setTransform(86.625,7.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AgeAfQgLgMgBgTQABgSALgMQAMgNASAAQATAAALANQANAMAAASQAAATgNAMQgLANgTAAQgSAAgMgNgAgYgZQgKALAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgLQgKgKgPAAQgOAAgKAKg");
	this.shape_3.setTransform(78.9,7.425);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AAyArIAAgyQgBgbgVAAQgLAAgGAHQgHAHAAAOIAAAxIgHAAIAAg1QAAgLgGgHQgGgGgKAAQgKAAgGAHQgIAIABAMIAAAyIgIAAIAAhTIAIAAIAAAOQADgHAGgEQAHgFAIAAQAVAAAEARQAHgRAVAAQAOAAAHAJQAIAJAAAOIAAA1g");
	this.shape_4.setTransform(67.15,7.325);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#333333").s().p("AAMAzQgUgBAAgYIAAgzIgKAAIAAgHIAKAAIAAgRIAIAAIAAARIATAAIAAAHIgTAAIAAAuQAAANADAFQADAEAKAAIADAAIAAAIg");
	this.shape_5.setTransform(53.725,6.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#333333").s().p("AgWAiQgJgIAAgPIAAg1IAIAAIAAA1QAAALAHAHQAGAGAKAAQAKAAAHgHQAHgIAAgMIAAgyIAIAAIAABTIgIAAIAAgOQgDAHgHAEQgIAFgHAAQgNAAgIgJg");
	this.shape_6.setTransform(47.275,7.525);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#333333").s().p("AgdAfQgNgMAAgTQAAgSANgMQAMgNARAAQATAAAMANQAMAMAAASQAAASgMANQgNANgSAAQgRAAgMgNgAgYgZQgJALAAAOQAAAQAJAKQAKAKAOAAQAPAAAKgKQAJgKAAgQQAAgOgJgLQgKgKgPAAQgOAAgKAKg");
	this.shape_7.setTransform(38.125,7.425);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#333333").s().p("AgbAvQgMgMAAgUQAAgRALgNQAMgNAQAAQANABAJAGQAHAFADAGIAAgwIAIAAIAABzIgIAAIAAgQQgMASgTAAQgRAAgLgMgAgVgKQgJAKAAAPQAAAQAJALQAJAJANAAQAOAAAJgKQAIgLAAgPQAAgPgJgLQgJgJgOAAQgMAAgJAKg");
	this.shape_8.setTransform(23.875,5.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#333333").s().p("AAYArIAAg1QAAgLgHgHQgGgGgKAAQgKAAgHAHQgHAIAAAMIAAAyIgIAAIAAhTIAIAAIAAAOQADgHAHgEQAIgFAHAAQANAAAIAJQAJAIAAAPIAAA1g");
	this.shape_9.setTransform(15.025,7.325);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#333333").s().p("AgDA4IAAhSIAHAAIAABSgAgGgxQABgGAFAAQAHAAgBAGQABAHgHAAQgFAAgBgHg");
	this.shape_10.setTransform(9.05,6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#333333").s().p("AgYA4IAAhvIAxAAIAAAIIgpAAIAAAsIAlAAIAAAGIglAAIAAA1g");
	this.shape_11.setTransform(3.9,5.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol50, new cjs.Rectangle(0,0,97.6,13.6), null);


(lib.Symbol49 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AghA2IAHgTQAKAHAPAAQAYAAAAgSIAAgEQgJAMgRAAQgTAAgLgOQgMgMAAgUQAAgVAMgNQAMgNATAAQAQAAAKALIAAgJIAWAAIAABNQAAAsgvAAQgQAAgQgIgAgPghQgGAHAAAMQAAALAGAHQAGAHAJAAQALAAAGgHQAGgHAAgLQAAgMgGgHQgGgHgLAAQgJAAgGAHg");
	this.shape.setTransform(173.275,64.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AAPAuIAAg2QAAgHgEgEQgEgEgGAAQgHAAgEAEQgEAFAAAHIAAA1IgYAAIAAhYIAXAAIAAAKQAIgNAPAAQAfAAAAAoIAAAzg");
	this.shape_1.setTransform(163.525,62.575);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AgLA+IAAhYIAXAAIAABYgAgJgmQgEgEAAgFQAAgGAEgEQAEgEAFAAQAGAAAEAEQAEAEAAAGQAAAFgEAEQgEAEgGAAQgFAAgEgEg");
	this.shape_2.setTransform(156.625,60.95);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("AANA9IgdguIAAAuIgXAAIAAh5IAXAAIAABGIAcglIAaAAIgfAoIAiAwg");
	this.shape_3.setTransform(150.45,61);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AAPAuIAAg2QAAgHgEgEQgEgEgGAAQgHAAgEAEQgEAFAAAHIAAA1IgYAAIAAhYIAXAAIAAAKQAHgNAQAAQAfAAAAAoIAAAzg");
	this.shape_4.setTransform(140.775,62.575);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#333333").s().p("AgcAnQgJgIgBgOQAAgNAKgHQAKgIAPAAQAMAAAGAFIAAgGQAAgNgPAAQgLAAgMAGIgJgQQAQgLASAAQAlAAAAAjIAAA4IgVAAIgCgGQgGAIgOAAQgOAAgKgIgAgKAHQgEAEAAAFQAAAGAEADQAFAEAGAAQAOAAAAgNQAAgMgOAAQgGAAgFADg");
	this.shape_5.setTransform(131.3,62.675);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#333333").s().p("AgoA7IAAh2IAnAAQAQAAALAJQALAIAAAPQAAASgPAHQASAHAAATQAAARgMAJQgLAJgRAAgAgQAmIAPAAQAQAAABgPQgBgPgQAAIgPAAgAgQgLIAOAAQAFAAAFgEQAEgDAAgGQAAgGgEgEQgFgEgFAAIgOAAg");
	this.shape_6.setTransform(122.5,61.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#333333").s().p("AggAeIANgMQAIAKALAAQAMAAAAgIQAAgFgVgIQgUgIAAgSQAAgMAJgIQAIgHANAAQAWAAAJAQIgQAMQgFgJgLAAQgHAAgBAHQAAAFAVAIQAUAIABASQAAAMgKAIQgKAIgOAAQgWAAgKgRg");
	this.shape_7.setTransform(109.4,62.675);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#333333").s().p("AghAeIAOgMQAIAKALAAQALAAAAgIQABgFgVgIQgVgIABgSQAAgMAJgIQAJgHAMAAQAWAAAJAQIgPAMQgHgJgKAAQgIAAAAAHQABAFATAIQAWAIAAASQgBAMgJAIQgKAIgOAAQgXAAgKgRg");
	this.shape_8.setTransform(102,62.675);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#333333").s().p("AgeAiQgMgNAAgVQAAgTAMgNQAMgOASAAQAVAAALANQALANAAAVIAAAFIg9AAQAAAJAHAGQAGAFAJAAQAOAAAHgLIAQAMQgEAHgIAFQgLAIgOAAQgVAAgNgNgAgMgVQgFAFgBAIIAmAAQgBgIgFgFQgFgFgIAAQgHAAgGAFg");
	this.shape_9.setTransform(93.575,62.675);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#333333").s().p("AAPAuIAAg2QAAgHgEgEQgEgEgGAAQgHAAgEAEQgEAFAAAHIAAA1IgYAAIAAhYIAXAAIAAAKQAIgNAPAAQAfAAAAAoIAAAzg");
	this.shape_10.setTransform(84.075,62.575);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#333333").s().p("AgLA+IAAhYIAXAAIAABYgAgJgmQgEgEAAgFQAAgGAEgEQAEgEAFAAQAGAAAEAEQAEAEAAAGQAAAFgEAEQgEAEgGAAQgFAAgEgEg");
	this.shape_11.setTransform(77.175,60.95);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#333333").s().p("AghAeIAOgMQAJAKALAAQALAAAAgIQAAgFgUgIQgVgIAAgSQAAgMAJgIQAJgHANAAQAVAAAJAQIgPAMQgGgJgKAAQgIAAAAAHQAAAFAUAIQAVAIAAASQAAAMgKAIQgKAIgOAAQgWAAgLgRg");
	this.shape_12.setTransform(71.375,62.675);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#333333").s().p("AgmAFIAAgyIAYAAIAAA1QAAAIAEAFQAEADAGAAQAHABAEgFQAEgFAAgHIAAg1IAYAAIAABYIgXAAIAAgKQgIANgPAAQgfAAAAgpg");
	this.shape_13.setTransform(62.975,62.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#333333").s().p("AgnA7IAAh2IAlAAQARAAALAJQALAIgBAPQAAASgOAHQATAHAAATQgBARgLAJQgMAJgRAAgAgPAmIAOAAQAQAAAAgPQAAgPgQAAIgOAAgAgPgLIANAAQAFAAAEgEQAFgDAAgGQAAgGgEgEQgFgEgFAAIgNAAg");
	this.shape_14.setTransform(53.7,61.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#333333").s().p("AgfAsQgRgRAAgbQAAgZASgSQARgSAaAAQAUAAAPALIgGAVQgOgJgPAAQgPAAgLALQgKALAAAQQAAARAKALQALALAPAAQAQAAAOgJIAGAVQgPALgVAAQgbAAgRgSg");
	this.shape_15.setTransform(38.875,61.175);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#333333").s().p("AgnA7IAAh2IAlAAQARAAALAJQAKAIAAAPQAAASgOAHQASAHAAATQAAARgMAJQgLAJgRAAgAgQAmIAPAAQAHAAAEgDQAFgFAAgHQAAgPgQAAIgPAAgAgQgLIAOAAQAFAAAFgEQAEgDAAgGQAAgGgEgEQgFgEgFAAIgOAAg");
	this.shape_16.setTransform(28.925,61.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#333333").s().p("AgfAsQgRgRAAgbQAAgZARgSQASgSAaAAQAUAAAPALIgHAVQgNgJgPAAQgPAAgLALQgKALAAAQQAAARAKALQALALAPAAQAQAAANgJIAHAVQgPALgVAAQgbAAgRgSg");
	this.shape_17.setTransform(18.325,61.175);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#333333").s().p("AgrAsQgSgRAAgbQAAgZASgSQARgSAaAAQAbAAASASQARASAAAZQAAAbgRARQgSASgbAAQgaAAgRgSgAgZgbQgLALAAAQQAAARALALQAKALAPAAQAQAAALgLQAKgLAAgRQAAgQgKgLQgLgLgQAAQgPAAgKALg");
	this.shape_18.setTransform(6.2,61.175);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#333333").s().p("AgMANQgGgFAAgIQAAgGAGgGQAFgFAHgBQAIABAFAFQAGAGAAAGQAAAIgGAFQgFAGgIgBQgHABgFgGg");
	this.shape_19.setTransform(219.325,38.65);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#333333").s().p("AgqAnIARgQQAMANAOAAQAOAAgBgLQAAgGgagLQgbgKAAgXQABgQAMgJQALgJARAAQAbAAAMAUIgTAPQgJgLgMAAQgLAAAAAJQAAAHAaAKQAbAJAAAYQAAAQgNAKQgMAKgSAAQgdAAgNgVg");
	this.shape_20.setTransform(211.85,34.475);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#333333").s().p("AgrAnIASgQQALANAPAAQAOAAAAgLQAAgGgagLQgcgKAAgXQAAgQAMgJQAMgJARAAQAbAAANAUIgUAPQgJgLgMAAQgLAAAAAJQAAAHAaAKQAcAJAAAYQAAAQgNAKQgNAKgSAAQgcAAgPgVg");
	this.shape_21.setTransform(202.275,34.475);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#333333").s().p("AgnArQgQgRAAgaQAAgZAQgRQAQgRAXAAQAbAAAPAQQAOAQAAAcIAAAHIhQAAQABALAIAIQAIAHAMAAQATAAAJgOIAUAPQgFAJgKAHQgPAJgTAAQgaAAgRgRgAgQgcQgGAHgBAKIAwAAQAAgLgHgGQgHgHgKAAQgKAAgHAHg");
	this.shape_22.setTransform(191.375,34.475);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#333333").s().p("AAUA7IAAhFQAAgJgGgHQgFgFgIAAQgIAAgGAHQgGAGAAAIIAABFIgeAAIAAhzIAeAAIAAAOQAJgQAUAAQAoAAAAA0IAABBg");
	this.shape_23.setTransform(179.075,34.35);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#333333").s().p("AgOBQIAAhyIAdAAIAABygAgLgxQgGgFAAgIQAAgHAGgFQAFgFAGAAQAIAAAFAFQAFAFAAAHQAAAIgFAFQgFAFgIAAQgGAAgFgFg");
	this.shape_24.setTransform(170.125,32.225);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#333333").s().p("AgrAnIASgQQALANAPAAQAOAAAAgLQAAgGgagLQgbgKAAgXQAAgQAMgJQALgJARAAQAbAAANAUIgVAPQgIgLgMAAQgLAAAAAJQAAAHAbAKQAbAJAAAYQgBAQgNAKQgMAKgSAAQgdAAgOgVg");
	this.shape_25.setTransform(162.65,34.475);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#333333").s().p("AgxAHIAAhBIAeAAIAABFQAAAKAGAFQAFAGAIAAQAIAAAGgGQAGgHAAgJIAAhEIAeAAIAAByIgeAAIAAgNQgKAQgTAAQgoAAAAg0g");
	this.shape_26.setTransform(151.775,34.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#333333").s().p("AgeBCIAAAMIgdAAIAAieIAfAAIAAA4QADgEAIgEQAKgGAMgBQAZAAAPARQAOARAAAaQAAAbgPARQgQAQgZAAQgVAAgMgPgAgVgDQgIAIAAAQQAAAPAIAJQAIAJANABQANgBAHgIQAJgKAAgPQAAgPgIgJQgIgJgNAAQgMAAgJAJg");
	this.shape_27.setTransform(139.15,32.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#333333").s().p("AgeA7IAAhzIAeAAIAAASQAIgUAXAAIAAAeQgfABAAAjIAAAzg");
	this.shape_28.setTransform(122.875,34.35);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#333333").s().p("AgxAHIAAhBIAeAAIAABFQAAAKAGAFQAFAGAIAAQAIAAAGgGQAGgHAAgJIAAhEIAeAAIAAByIgeAAIAAgNQgKAQgTAAQgoAAAAg0g");
	this.shape_29.setTransform(112.525,34.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#333333").s().p("AgsArQgRgRAAgaQAAgZASgRQARgRAaAAQAaAAASARQASARAAAZQAAAagRARQgSARgbAAQgaAAgSgRgAgWgXQgIAKgBANQABAPAIAJQAJAKANAAQAOAAAIgKQAJgJAAgPQAAgNgJgKQgIgKgOAAQgNAAgJAKg");
	this.shape_30.setTransform(99.65,34.475);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#333333").s().p("AgcBNIAPgqIgshvIAgAAIAaBLIAahLIAfAAIg6CZg");
	this.shape_31.setTransform(86.95,36.425);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#333333").s().p("AgsBFIAKgXQAOAIASAAQAfAAAAgXIAAgFQgMAOgVAAQgYAAgQgQQgPgRAAgZQAAgbAQgRQAQgRAZAAQALAAALAGQAHAEAEAFIAAgNIAdAAIAABkQAAA5g9AAQgXAAgUgLgAgUgrQgIAJAAAPQAAAQAIAHQAJAKAMAAQANAAAIgKQAIgHAAgQQAAgOgIgKQgIgJgOAAQgMAAgIAJg");
	this.shape_32.setTransform(68.525,36.45);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#333333").s().p("AAUA7IAAhFQAAgJgGgHQgFgFgIAAQgIAAgGAHQgGAGAAAIIAABFIgeAAIAAhzIAeAAIAAAOQAJgQAUAAQAoAAAAA0IAABBg");
	this.shape_33.setTransform(55.925,34.35);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#333333").s().p("AgOBQIAAhyIAdAAIAABygAgMgxQgFgFAAgIQAAgHAFgFQAGgFAGAAQAIAAAFAFQAFAFAAAHQAAAIgFAFQgFAFgIAAQgGAAgGgFg");
	this.shape_34.setTransform(46.975,32.225);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#333333").s().p("AAUA7IAAhFQAAgJgGgHQgFgFgIAAQgIAAgGAHQgGAGAAAIIAABFIgeAAIAAhzIAeAAIAAAOQAJgQAUAAQAoAAAAA0IAABBg");
	this.shape_35.setTransform(38.175,34.35);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#333333").s().p("AAUA7IAAhFQAAgJgGgHQgFgFgIAAQgIAAgHAHQgFAGAAAIIAABFIgeAAIAAhzIAeAAIAAAOQAJgQAUAAQAoAAAAA0IAABBg");
	this.shape_36.setTransform(25.85,34.35);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#333333").s().p("AgxAHIAAhBIAeAAIAABFQAAAKAGAFQAFAGAIAAQAIAAAGgGQAGgHAAgJIAAhEIAeAAIAAByIgdAAIAAgNQgKAQgUAAQgoAAAAg0g");
	this.shape_37.setTransform(13.525,34.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#333333").s().p("AgeA7IAAhzIAeAAIAAASQAHgUAYAAIAAAeQgfABAAAjIAAAzg");
	this.shape_38.setTransform(3.75,34.35);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#333333").s().p("AAUA7IAAhFQAAgKgGgFQgFgGgIAAQgIAAgGAHQgGAGAAAIIAABFIgeAAIAAhzIAeAAIAAAOQAKgQATAAQAoAAAAA0IAABBg");
	this.shape_39.setTransform(171.325,10.15);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#333333").s().p("AgOBQIAAhyIAdAAIAABygAgLgxQgGgFAAgIQAAgHAGgFQAFgFAGAAQAIAAAFAFQAFAFAAAHQAAAIgFAFQgFAFgIAAQgGAAgFgFg");
	this.shape_40.setTransform(162.375,8.025);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#333333").s().p("AgxAHIAAhBIAeAAIAABFQAAAKAGAFQAFAGAIAAQAIAAAGgGQAGgHAAgJIAAhEIAeAAIAABzIgeAAIAAgOQgJAQgUAAQgoAAAAg0g");
	this.shape_41.setTransform(148.125,10.4);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#333333").s().p("AgrArQgSgQAAgbQAAgZASgRQARgRAaAAQAaAAASARQASARAAAZQAAAagSARQgRARgbAAQgaAAgRgRgAgWgXQgJAKAAANQAAAPAJAJQAJAKANAAQAOAAAJgKQAJgJAAgPQAAgNgJgKQgJgKgOAAQgNAAgJAKg");
	this.shape_42.setTransform(135.275,10.275);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#333333").s().p("AgdBNIAQgqIgshvIAhAAIAYBLIAahLIAgAAIg6CZg");
	this.shape_43.setTransform(122.575,12.225);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#333333").s().p("AgsBGIAKgYQAPAIASAAQAeAAAAgXIAAgFQgMAOgVAAQgYAAgQgQQgPgQAAgaQAAgbAQgRQAQgRAZAAQAVAAAMAPIAAgNIAdAAIAABkQgBA5g8AAQgYAAgTgKgAgUgrQgIAJAAAPQAAAPAJAIQAHAKAMAAQANAAAJgKQAIgHAAgQQAAgPgIgJQgJgJgNAAQgMAAgIAJg");
	this.shape_44.setTransform(104.15,12.25);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#333333").s().p("AAUA7IAAhFQAAgKgGgFQgFgGgIAAQgIAAgHAHQgFAGAAAIIAABFIgeAAIAAhzIAeAAIAAAOQAJgQAUAAQAoAAAAA0IAABBg");
	this.shape_45.setTransform(91.55,10.15);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#333333").s().p("AgOBQIAAhyIAdAAIAABygAgMgxQgEgFAAgIQAAgHAEgFQAFgFAHAAQAIAAAFAFQAEAFAAAHQAAAIgEAFQgFAFgIAAQgHAAgFgFg");
	this.shape_46.setTransform(82.6,8.025);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#333333").s().p("AgTAXIAAgsIgNAAIAAgZIANAAIAAgXIAdAAIAAAXIAVAAIAAAZIgVAAIAAAsQAAAMAEAFQAEADAJAAIAFAAIAAAaQgEACgIgBQgnAAAAgvg");
	this.shape_47.setTransform(76.05,9.15);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#333333").s().p("AgeA7IAAhzIAeAAIAAARQAHgTAYAAIAAAeQgfABAAAjIAAAzg");
	this.shape_48.setTransform(68.275,10.15);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#333333").s().p("AgrArQgSgRAAgaQAAgZASgRQASgRAZAAQAaAAASARQASARAAAZQAAAagRARQgSARgbAAQgaAAgRgRgAgWgXQgIAKgBANQABAPAIAJQAJAKANAAQAOAAAIgKQAJgJAAgPQAAgNgJgKQgIgKgOAAQgNAAgJAKg");
	this.shape_49.setTransform(57.25,10.275);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#333333").s().p("Ag7BPIAAibIAdAAIAAAMQAMgPAVAAQAZAAAPARQARASgBAZQABAbgPARQgQAQgYAAQgMAAgKgGQgIgEgDgFIAAA1gAgVgqQgIAJAAAOQAAAQAIAJQAJAJAMAAQANAAAIgKQAIgIAAgQQAAgOgIgKQgJgJgMAAQgNAAgIAKg");
	this.shape_50.setTransform(44,12.2);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#333333").s().p("Ag7BPIAAibIAdAAIAAAMQAEgFAHgEQALgFALgBQAZAAAQARQAQASAAAZQAAAbgPARQgPAQgZAAQgVAAgMgPIAAA1gAgVgqQgIAJAAAOQAAAQAJAJQAHAJANAAQANAAAHgKQAJgIgBgQQABgOgJgKQgHgJgNAAQgNAAgIAKg");
	this.shape_51.setTransform(30.35,12.2);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#333333").s().p("AgxAHIAAhBIAeAAIAABFQAAAKAGAFQAFAGAIAAQAIAAAGgGQAGgHAAgJIAAhEIAeAAIAABzIgeAAIAAgOQgJAQgUAAQgoAAAAg0g");
	this.shape_52.setTransform(17.075,10.4);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#333333").s().p("AgkBDQgKgKgEgNIAagNQAHAUASAAQATAAAAgQQAAgKgggRQgigQAAgbQAAgUANgMQAOgMAVAAQAUAAAOANQAJAIAEANIgaALQgHgQgPAAQgHAAgEAEQgFAEAAAHQAAAKAhAQQAhAPAAAbQAAAVgNANQgPANgXAAQgVAAgPgNg");
	this.shape_53.setTransform(5.125,8.325);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol49, new cjs.Rectangle(0,0,221.2,70.4), null);


(lib.Symbol48 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AB7AjIAAghIgWgkIAJAAIARAeIARgeIAJAAIgWAkIAAAhgABbAjIgJgWIgbAAIgIAWIgJAAIAbhFIAIAAIAaBFgABQAGIgLgfIgLAfIAWAAgAAAAjIAAhFIAIAAIAAA9IAaAAIAAAIgAgyAjIAAhFIATAAQAKAAAGAFQAFAGAAAJQAAAHgCAEQgDAEgFACQgEACgHABIgLAAIAAAdgAgqgBIALAAQAGABADgEQAEgDAAgHQAAgGgEgDQgDgEgGAAIgLAAgAhhAjIAAhFIAhAAIAAAHIgZAAIAAAYIAWAAIAAAGIgWAAIAAAYIAaAAIAAAIgAh0AjIgQgeIgMAAIAAAeIgIAAIAAhFIASAAQALAAAFAFQAGAFAAAKIgCAIQgBADgDADQgCABgEACIARAggAiQgCIAKAAQAGAAAEgCQADgDAAgHQAAgGgDgDQgDgEgIAAIgJAAg");
	this.shape.setTransform(18.075,8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol48, new cjs.Rectangle(0,0,35.6,16), null);


(lib.Path_11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#878787","#B2B2B2","#DBDBDB","#F5F5F5","#FFFFFF"],[0,0.282,0.6,0.851,1],0,0,0,0,0,9.4).s().p("AA3ApQgcgEgjgOQgkgPgXgQQgXgRAEgKQAEgJAcAEQAcAEAjAPQAkAOAXAQQAXARgEAJQgCAHgPAAIgPgBg");
	this.shape.setTransform(8.775,4.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Path_11, new cjs.Rectangle(0,0,17.6,8.4), null);


(lib.Path_9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgvBZIALgVIgTgNIBQiSIATANIAHgMIAEAEIhhCyg");
	this.shape.setTransform(5.55,9.175);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Path_9, new cjs.Rectangle(0,0,11.1,18.4), null);


(lib.Path_7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#878787","#B2B2B2","#DBDBDB","#F5F5F5","#FFFFFF"],[0,0.282,0.6,0.851,1],0,0,0,0,0,12.1).s().p("ABHA1QgkgFgugTQgugTgegVQgegWAFgMQAFgMAlAFQAkAFAuATQAuATAeAUQAeAWgFAMQgEAJgUAAIgSgBg");
	this.shape.setTransform(11.3245,5.4128);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Path_7, new cjs.Rectangle(0,0,22.7,10.8), null);


(lib.Path_6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Ag7BgIBrjGIAMAHIhsDGg");
	this.shape.setTransform(5.975,10.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Path_6, new cjs.Rectangle(0,0,12,20.5), null);


(lib.Path_5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#878787","#B2B2B2","#DBDBDB","#F5F5F5","#FFFFFF"],[0,0.282,0.6,0.851,1],0,0,0,0,0,11.8).s().p("ABFAzQgjgEgsgTQgugSgcgUQgdgWAEgLQAFgMAkAFQAjAEAsATQAuASAcAUQAdAVgFAMQgDAJgTAAIgSgCg");
	this.shape.setTransform(11.0065,5.275);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Path_5, new cjs.Rectangle(0,0,22,10.6), null);


(lib.Path_3_0 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgMAMQgGgFABgHQAAgHAFgFQAGgGAGABQAIAAAFAFQAFAGAAAGQAAAIgGAFQgFAFgHAAQgHAAgFgGg");
	this.shape.setTransform(1.8229,1.8229);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Path_3_0, new cjs.Rectangle(0,0,3.7,3.7), null);


(lib.Path_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#878787","#B2B2B2","#DBDBDB","#F5F5F5","#FFFFFF"],[0,0.282,0.6,0.851,1],0,0,0,0,0,19.5).s().p("AiIAoQg5gNgBgVQAAgUA4gQQA5gRBQgCQBQgDA6ANQA5ANABAVQABATg5ASQg5AQhQADIgZAAQhBAAgwgLg");
	this.shape.setTransform(19.4756,5.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Path_3, new cjs.Rectangle(0,0,39,10.2), null);


(lib.Path_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgMANQgGgGABgHQAAgHAFgFQAGgGAGABQAIAAAFAFQAFAGAAAGQAAAIgGAFQgFAFgHAAQgHAAgFgFg");
	this.shape.setTransform(1.8229,1.8229);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Path_1, new cjs.Rectangle(0,0,3.7,3.7), null);


(lib.Path = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AigAMQhDgFAAgHQAAgGBDgFQBDgFBdAAQBfAABCAFQBDAFAAAGQAAAHhDAFQhCAFhfAAQhdAAhDgFg");
	this.shape.setTransform(22.75,1.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Path, new cjs.Rectangle(0,0,45.5,3.4), null);


(lib.Symbol8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAIAZIAAgdQABgDgDgDQgDgCgDAAQgCAAgDACQgDADAAAEIAAAcIgMAAIAAgwIAMAAIAAAGQACgDAEgCQACgCAFAAQAQAAAAAWIAAAbg");
	this.shape.setTransform(272.85,37.375);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgSATQgHgIAAgLQAAgKAHgHQAIgHAKAAQALAAAHAHQAIAHAAAKQAAAKgHAJQgIAGgLABQgKgBgIgGgAgJgJQgDAEAAAFQAAAGADAEQAEAEAFAAQAGAAADgEQAFgEAAgGQAAgFgFgEQgDgEgGAAQgFAAgEAEg");
	this.shape_1.setTransform(267.45,37.45);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgDAZQgEgFAAgKIAAgSIgGAAIAAgLIAGAAIAAgKIALAAIAAAKIAJAAIAAALIgJAAIAAASQAAAFACACQABABAEAAIADAAIAAALIgGABQgIAAgDgFg");
	this.shape_2.setTransform(260.825,36.975);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgRATQgIgIAAgLQAAgKAIgHQAHgHAKAAQALAAAIAHQAHAHAAAKQAAAKgHAJQgIAGgLABQgLgBgGgGgAgIgJQgFAEAAAFQAAAGAFAEQADAEAFAAQAGAAAEgEQADgEAAgGQAAgFgDgEQgEgEgGAAQgFAAgDAEg");
	this.shape_3.setTransform(256.6,37.45);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgYAhIAAhBIAMAAIAAAGIACgDIAFgCIAGgBQALgBAGAIQAHAHAAALQAAAKgGAIQgGAGgLABQgDAAgDgCIgFgDIgCgCIAAAWgAgIgRQgEAEAAAGQAAAGAEAEQADADAFAAQAGAAADgEQADgCAAgHQAAgHgDgDQgEgEgFAAQgFAAgDAEg");
	this.shape_4.setTransform(251.075,38.25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgKAXQgFgCgCgEIAHgHQAFAFAFAAIAFgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBAAAAAAIgFgEIgHgCQgDgCgCgCQgDgDAAgFQAAgHAFgEQAGgDAGAAQALAAAGAIIgJAHQgDgFgGAAIgCABQgBAAAAABQAAAAAAAAQgBAAAAABQAAAAAAAAQAAABAAAAQABABAAAAQAAABABAAQAAABABAAIALAFQADABADADQACADAAAFQAAAHgFAEQgFAFgIAAQgFAAgFgDg");
	this.shape_5.setTransform(246.125,37.45);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgLAgIAHgRIgUguIAOAAIAKAfIALgfIAOAAIgZA/g");
	this.shape_6.setTransform(270.5,30.05);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgGAiIAAhDIAMAAIAABDg");
	this.shape_7.setTransform(266.95,28.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgYAhIAAhAIAMAAIAAAEIACgCIAFgCIAGgBQALgBAGAIQAHAGAAAMQAAAJgGAIQgGAHgLAAIgGgBIgFgDIgCgCIAAAWgAgIgSQgEAFAAAGQAAAGAEADQAEAEAEAAQAFAAAEgEQADgEAAgFQAAgGgDgFQgEgEgFAAQgFAAgDAEg");
	this.shape_8.setTransform(263.125,30.05);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAWAZIAAgcQAAgDgCgEQgCgCgEAAQgDAAgCACQgCACAAAFIAAAcIgNAAIAAgdQAAgEgBgCQgCgCgEAAQgDAAgCACQgDADAAAEIAAAcIgMAAIAAgwIAMAAIAAAGQACgDADgCQADgCAFAAQAIAAAEAHQAEgHAKAAQAIAAAEAFQAEAEABAJIAAAfg");
	this.shape_9.setTransform(256.25,29.175);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgFAiIAAgwIALAAIAAAwgAgFgUIgBgFQAAgDABgDQACgCADAAQADAAACACQACACABAEQgBADgCACQgCACgDAAQgDAAgCgCg");
	this.shape_10.setTransform(251.2,28.275);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgKAXQgEgCgDgFIAHgGQAFAFAFAAQABAAABAAQAAAAABAAQAAAAABgBQAAAAABAAQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBAAAAgBIgMgFQgDgCgCgCQgDgEAAgEQAAgGAFgFQAFgDAHAAQALAAAGAIIgJAGQgDgEgGAAIgCABIgCADQAAAAAAABQABAAAAABQAAAAABAAQAAABABAAIALAFQAEACACACQACADAAAFQAAAHgFAEQgEAEgJAAQgGAAgEgCg");
	this.shape_11.setTransform(248.125,29.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#EA2127").s().p("AgmApQgRgRAAgYQAAgWARgRQAQgRAWAAQAXAAAQARQARAQAAAXQAAAYgRAQQgQAQgXABQgVAAgRgQg");
	this.shape_12.setTransform(277.525,49.05);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#EA2127").s().p("AiXCYQg+g/gBhZQABhYA+g/QA/g+BYgBQBZABA/A+QA/A/AABYQgBAsgQAmQgIgCgLAAQgfAAgXAWQgYAXAAAhQAAAPAGAOQgzAcg4AAQhYAAg/g/g");
	this.shape_13.setTransform(259.6,33.25);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#EA2127").s().p("AleA4IBhAAIhmgFIBrgBIhwgGIArgBQAWABASgJQAFgDADgDIAEgEQAKgLgBgOQABgQgMgLQgLgMgRAAQgGAAgHACIgbgeQASgLAWAAQAgAAAYAXQAXAXAAAgQAAAggXAYQgYAXggAAQggAAgXgXgAi6AeQgKgKAAgTQAAgSANgMQAMgMASABQASgBAKAKQALALAAATQAAATgMALQgMAMgSAAQgTAAgLgLgAipgSQgFAHgBALQABAYATAAQAIAAAGgGQAGgGABgMQgBgYgTAAQgJABgGAFgAllApQgCgHgIgBIgBgFIAXAAIAEAFIAkAAIgIAIgADAAZQAAgVAiAAIAAgEQABgHgMgBQgKABgIAEIgBgNQAKgDALAAQAOAAAFAGQAGAEAAAJIAAAoIgPAAIABgLQgFAMgOAAQgRAAAAgQgADPAXQgBAGAIAAQAFAAAEgEQADgEAAgGIAAgBQgTAAAAAJgAAuAcQgIgJAAgRQAAgSALgLQALgMAVAAQAIAAAKACIgCAQIgQgCQgKAAgGAGQgGAHABAKQAAAYAWAAQAHAAAIgDIACAQQgKAEgLAAQgVAAgLgNgAhqACQABgSAKgLQAMgMAVAAIARACIgCAQQgJgCgHAAQgKAAgGAGQgFAHAAAKQAAAYAWAAQAHAAAIgDIADAQQgMAEgKAAQgoAAAAgngAFkAoIgTgeIAAAeIgPAAIAAhVIAPAAIAAAzIASgYIASAAIgVAaIAXAggAEkAoIAAgmQAAgJgGAAQgHAAgDAGQgFAEAAAIIAAAdIgPAAIAAg6IAOAAIAAAKQAGgLAOAAQASAAAAASIAAApgACAAoIAAhOIAcgBQAbAAAAAUQAAAMgMAFQANADAAAOQAAAKgGAHQgJAHgRABgACQAaIAJABQAPAAAAgLQAAgLgRAAIgHAAgACQgbIAAAVIAHAAQAPAAAAgLQAAgKgNAAIgJAAgAggAoIAAhOIAggBQAcAAAAAUQAAAMgMAFQAOADgBAOQABAKgJAHQgJAIgRAAgAgMAZIAHAAQANAAABgKQgBgJgOAAIgGAAgAgMgHIAGAAQANAAAAgKQAAgHgLgBIgIAAgAlxAaQgFgMAAgOIABgOIAnANIAAABQAAAOAJALQgGgLAAgJIABgFIApAOIAAAMgAlKgBQACgKAFgIIAiAUIAAAMgAlBgUQAGgHAJgEIARASIAAANgAlzgSQADgOAHgLIAhAWQgFAHgBALgAlnguQAIgLAMgHIAcAcQgJAEgFAIg");
	this.shape_14.setTransform(53.4,32.45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol8, new cjs.Rectangle(15.9,11.8,267.3,42.900000000000006), null);


(lib.Symbol72 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA2127").s().p("Ah0AOIAAgbIDpAAIAAAbg");
	this.shape.setTransform(66.725,56.275);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#EA2127").s().p("AmKAfIAAg9IMVAAIAAA9g");
	this.shape_1.setTransform(66.65,3.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#337D99").s().p("ABrFKIAAiBIheAAIAACBIgZAAIAAiBIheAAIAACBIjxAAIAAqTIK3AAIAAKTgADNBdIBQAAIAAhQIhQAAgABFBdIBQAAIAAhQIhQAAgAiUBdIBQAAIAAhQIhQAAgAkcBdIBQAAIAAhQIhQAAgADNgrIBQAAIAAhPIhQAAgABFgrIBQAAIAAhPIhQAAgAiUgrIBQAAIAAhPIhQAAgAkcgrIBQAAIAAhPIhQAAgADNizIBQAAIAAhQIhQAAgABFizIBQAAIAAhQIhQAAgAiUizIBQAAIAAhQIhQAAgAkcizIBQAAIAAhQIhQAAg");
	this.shape_2.setTransform(66.725,37.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#337D99").s().p("AmrARIAAgiINWAAIAAAig");
	this.shape_3.setTransform(66.75,75.1);

	this.instance = new lib.Path();
	this.instance.setTransform(64.85,75.75,1,1,0,0,0,22.8,1.7);
	this.instance.alpha = 0.1016;

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ai7BIQjUgHiGgTQiIgVAAgZQAAgfDEgWQDEgWEVAAQEWAADEAWQDEAWAAAfQAAAbicAVQhfANiCAHQiKAIiXAAQhTAAhogEg");
	this.shape_4.setTransform(67.025,76.075);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#C9C8C8").s().p("AnZA2QjEgXAAgfQAAgfDEgWQDEgWEVAAQEWAADEAWQDEAWAAAfQAAAfjEAXQjEAWkWAAQkVAAjEgWg");
	this.shape_5.setTransform(67.025,76.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#7F7E7C").s().p("AnZA2QjEgXAAgfQAAgeDEgWQDEgXEVAAQEWAADEAXQDEAWAAAeQAAAfjEAXQjFAWkVAAQkUAAjFgWg");
	this.shape_6.setTransform(67.025,78.375);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#7F7E7C").s().p("AgMAJIAAgXIAZAPIgHAOg");
	this.shape_7.setTransform(1.3,77.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#7F7E7C").s().p("AAOgQIAAAXIgbAJg");
	this.shape_8.setTransform(132.65,77.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F1C2B1").s().p("AgJAfIgIgCIgFgCIgIgEIgDgFIgEgFIgCgIIABgIQABgFAEgEIADgFIADgDIAOgGIAHgCIAIgBQAMgCAKACIAHADIACADIADADIADAHIABAOIgBAIQAAAFgEAEIgDAFQgHAFgUACIgIABIgDAAIgDAAg");
	this.shape_9.setTransform(47.65,90.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#3C3C3B").s().p("AgCAAQAAAAAAAAQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAQAAABABAAQAAABAAAAIAAACIgCABIgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBg");
	this.shape_10.setTransform(107.375,108.85);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#3C3C3B").s().p("AgCABQAAgBAAAAQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAQAAABABAAQAAABAAAAQAAAAAAAAQAAABAAAAQAAABgBAAQAAAAgBABIgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAg");
	this.shape_11.setTransform(106.575,109.05);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#3C3C3B").s().p("AgCABQAAgBAAAAQAAAAAAgBQAAAAABAAQABAAAAAAQAAgBAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIgBABQAAAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAg");
	this.shape_12.setTransform(107.175,108);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#3C3C3B").s().p("AgCAAQAAAAAAAAQAAAAAAgBQAAAAABAAQABAAAAAAQAAgBAAAAQABAAAAABQABAAAAAAQABABAAAAIAAABIgCABIgBABQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBg");
	this.shape_13.setTransform(106.375,108.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#DADADA").s().p("AgMANQgGgGABgHQAAgHAFgFQAGgGAGABQAIAAAFAFQAFAGAAAGQAAAIgGAFQgFAFgHAAQgHAAgFgFg");
	this.shape_14.setTransform(106.9229,108.6229);

	this.instance_1 = new lib.Path_1();
	this.instance_1.setTransform(107.1,108.5,1,1,0,0,0,1.8,1.8);
	this.instance_1.alpha = 0.1016;

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#3C3C3B").s().p("AgCABQAAgBAAAAQAAAAAAgBQAAAAABAAQABgBAAAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQAAAAAAAAQAAABAAAAQAAABgBAAQgBAAAAABIgBAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQgBgBAAAAg");
	this.shape_15.setTransform(102.775,105.7375);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#3C3C3B").s().p("AgCABQAAgBAAAAQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQAAAAAAAAQAAABAAAAQAAABgBAAQgBAAAAABIgBAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQgBgBAAAAg");
	this.shape_16.setTransform(101.975,105.9375);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#3C3C3B").s().p("AgCABQAAgBAAAAQAAAAAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAQgBABAAAAQgBAAAAABIgBAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQgBgBAAAAg");
	this.shape_17.setTransform(102.575,104.8875);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#3C3C3B").s().p("AgCABQAAgBAAAAQAAAAAAAAQAAgBABAAQABgBAAAAQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAQgBABAAAAQgBAAAAABIgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAg");
	this.shape_18.setTransform(101.775,105.0875);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#DADADA").s().p("AAAASQgHAAgFgFQgGgGABgHQAAgHAFgFQAGgFAGAAQAIAAAFAGQAFAFAAAGQAAAIgGAFQgFAFgGAAIgBAAg");
	this.shape_19.setTransform(102.3229,105.5);

	this.instance_2 = new lib.Path_3_0();
	this.instance_2.setTransform(102.5,105.4,1,1,0,0,0,1.8,1.8);
	this.instance_2.alpha = 0.1016;

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#E30613").s().p("AlpiIIiDhIIA5hqQAEgGAHAFIOVH7IhcB/g");
	this.shape_20.setTransform(153.75,115.3988);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#E30613").s().p("AnYjUQgDgCgBgEQgCgEACgEIA9htICDBIIL6HHIhhCRg");
	this.shape_21.setTransform(146.0429,128.1);

	this.instance_3 = new lib.Path_6();
	this.instance_3.setTransform(103.95,94.05,1,1,0,0,0,6,10.3);
	this.instance_3.alpha = 0.1016;

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AghAtQgGgDADgHIAwhaIAaAOIg0Bhg");
	this.shape_22.setTransform(100.5882,98.65);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F6F6F6").s().p("AgnAqIAwhZIABgDQACgDAEgBQADgCADACIATAKIg2BkIAAAAg");
	this.shape_23.setTransform(105.85,88.8929);

	this.instance_4 = new lib.Path_9();
	this.instance_4.setTransform(101.6,93.2,1,1,0,0,0,5.5,9.2);
	this.instance_4.alpha = 0.1992;

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F3B897").s().p("AD1C1IgIAAIgHAAQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAAAAAAAIhVhWIgBgCIgqgpIgDgCIgPgNIgBgBIhVg/IgVgIIgBAAQgIgDgVgBIgbAAIgsAJIguASIAAgCIgBgIIAAgBIgBAAIAAgEIAAAAIgBgDIgFgVIgBgCIAAgCIgBgGIgDgFIgPgCQg4gFgrADIhlAOIgnAAIgUgBIgCAAIgKgCIgCAAQgNgBgJgFQgDgCgDgEQgDgFgBgEQgEgLACgIIABgDIADgIIACgEIAEgEIAAgBIACgBIAFgFIAFgCIANgFIACgBIA9gNIAGgBIAIAAIAgABIA3gGQAvgHAfgWIElAAIAiAVIAAABIAZAQIADACIAOAKIACABIFqDlQgBADACALQACAKgBADQgDAFAGANQAGANgCAHQAAABgHACIgNACIgEABQgJADABADQAAAAAAABQABAAgBAAQAAABAAAAQAAAAgBAAIgxAEIg1AAIhHAAQgZgDgBACQAAABgHgBQgGgBgBABIgGAAQgFgBgBABIgCABIgFgBg");
	this.shape_24.setTransform(94.5872,100);

	this.instance_5 = new lib.Path_3();
	this.instance_5.setTransform(61.6,90.85,1,1,0,0,0,19.4,5.1);
	this.instance_5.alpha = 0.2617;

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F1C2B1").s().p("AAQAPIgBgBIgBAAIgRgJIgMgIIgBAAIgEgDIAAgBIAAgBIAAgDIACgCIADgCIABAAIABAAIABAAIAHABIABABIAIAEIAFAEIAIAIIABABIAAABIACADIAAAAIABAAIABAEIAAADIgBABg");
	this.shape_25.setTransform(25.5,84.425);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F3B897").s().p("ABgB5IgMgGIgagRIgfgVIgtgXIgBgBIgdgNIg3ggIgDgCIhTg4IgBgBIgegRIgCgBQgSgHgNgHQgOgJgCgHIAAgCIAAgCIABgDIAAgBIAKgIIAMgEQAOgDAPADIAFABIASAFIAfAOIAWAMQALAFARAFIA2AYIAyANIABABIAoALIABAAIAyAVQAEACAJACQAJACAFABIAHgBQANgEAGAAQAHgBAMABIASABIAaAAIAKABIAuADIACAAIAEAGIAAAFIAAACIABADIAFAUIABADIAAABIAAACIAAABIABABIABAIIAAACIgDABQgkASgOAGIgNAFQgVAHgLAFQgbAPgNAFIgPAFIgGAAIgHABIgIgBg");
	this.shape_26.setTransform(50.075,93.27);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F1C2B1").s().p("AAYAQIgFgBIgBAAIgCgBIgQgGIgRgJIgBAAIgEgDIgBgCIABgDIACgDIABgBIABgBIABgBIACAAIAHABIACABIAJAEIAHAEIAJAHIABACIAAAAIABABIABACIAAABIABABIABAEIAAADg");
	this.shape_27.setTransform(19.875,80.325);

	this.instance_6 = new lib.Path_5();
	this.instance_6.setTransform(35.75,86,1,1,0,0,0,11,5.3);
	this.instance_6.alpha = 0.6992;

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#E8B290").s().p("ABOBGQgXgLgQgLIh4hPIgCgBIAAAAIgJgFIgBgBIgBAAIgZgLQgNgHgFgGIgEgGIAAgCIAAgFIADgIIAEgEQADgDAEgBIAIgCIADAAIANAAIAFABIAPADIAFABIAMAFIAeASQALAGAJAHQAKAIAQAIIBxA4IABAAIASAHIAAABIgBAHQAAAHgEAAQgEgBAAAIIAAAcQgBAOgCADg");
	this.shape_28.setTransform(31.825,85.9625);

	this.instance_7 = new lib.Path_7();
	this.instance_7.setTransform(29.45,81.6,1,1,0,0,0,11.3,5.4);
	this.instance_7.alpha = 0.3281;

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#E8B290").s().p("AAXARIgDgBIgCgBIgBAAIgBAAIgdgPIgEgCIgBAAIgEgDIAAgCIgBAAIABgDIACgDIABgBIACgBIABAAIABgBIAAAAIAHACIACAAIAJAFIAGADIAJAJIABABIABABIACADIAAAAIAAAAIABACIABACIAAACIAAABIAAACg");
	this.shape_29.setTransform(22.6,80.275);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#E8B290").s().p("AAXANIgCgBIgEAAIgIgBIgMgEIgUgHIgCgBIABgDIABgEIABgBIABgBIACgBIAIAAIALACIAHADIACABIAJAFIAFAFIACACIAAADIABABIAAABIgBABg");
	this.shape_30.setTransform(30.9167,84.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#E8B290").s().p("ABKBIQgUgJgJgGIhshQIgUgMIAAgBIgKgFIAAAAIAAAAIgBAAIgZgNQgLgHgHgGIgDgHIAAgGIABgDIACgFIACgCIACgCIABAAIAHgDIALgDIAMABIAWAFIAPAHIAdATIAUAOIAZAQIBRAvIAgAMIAAAAIACAAIARAGIgCAFIgBAGQgBAHgEAAQgDAAAAAEIAAAVIgBADIAAAFIAAACQgBANgDADg");
	this.shape_31.setTransform(34.5,86.35);

	this.instance_8 = new lib.Path_11();
	this.instance_8.setTransform(37.15,83.8,1,1,0,0,0,8.8,4.2);
	this.instance_8.alpha = 0.3281;

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#E8B290").s().p("ABbA6IgegKIgSgIIgCAAIhOgmIgYgJIgWgIIgBAAIgFgCIgFgCIAAAAIgBAAIAAAAIgbgHQgOgEgGgGIgFgFIAAgBIgBgBIAAgEIAAgDIACgGIABgCIABgCIABAAQADgEAEgBIAHgEIAPgDIAGAAIAOABIACAAIAEAAIAMADIAhANIAWAKQATAIAJACIA8AVQAPAFANADQAKADARACIAbACIgBAFIAAAMQAAAAgBAAQAAABAAAAQgBAAgBABQAAAAgBAAQgCABABAHIADASIAAACIABAGIABAIQABAHgCAEg");
	this.shape_32.setTransform(43.225,87.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_32},{t:this.instance_8},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.instance_7},{t:this.shape_28},{t:this.instance_6},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.instance_5},{t:this.shape_24},{t:this.instance_4},{t:this.shape_23},{t:this.shape_22},{t:this.instance_3},{t:this.shape_21},{t:this.shape_20},{t:this.instance_2},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.instance_1},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.instance},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol72, new cjs.Rectangle(0,0,203.1,161.8), null);


(lib.Symbol62 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_28 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(28).call(this.frame_28).wait(1));

	// Symbol 66
	this.instance = new lib.Symbol66();
	this.instance.setTransform(-0.2,90.2,1,1,0,0,0,15.8,15.8);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(17).to({_off:false},0).to({x:15.8,alpha:1},10).wait(2));

	// Symbol 65
	this.instance_1 = new lib.Symbol65();
	this.instance_1.setTransform(84.45,89.35,1,1,0,0,0,29.6,15.6);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(15).to({_off:false},0).to({x:68.45,alpha:1},10).wait(4));

	// Symbol 64
	this.instance_2 = new lib.Symbol64();
	this.instance_2.setTransform(49.6,30.65,1,1,0,0,0,33.8,21.3);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(13).to({_off:false},0).to({y:46.65,alpha:1},10).wait(6));

	// Layer_1
	this.instance_3 = new lib.Symbol63();
	this.instance_3.setTransform(56.05,38.9,1,1,0,0,0,50.8,62.9);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({y:62.9,alpha:1},21,cjs.Ease.backOut).wait(8));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-16,-24,130.1,152.1);


(lib.Symbol53 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_33 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(33).call(this.frame_33).wait(1));

	// s
	this.instance = new lib.Symbol57();
	this.instance.setTransform(127.1,13.3,1,1,0,0,0,5.8,11.7);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(28).to({_off:false},0).to({y:11.7,alpha:1},5).wait(1));

	// s
	this.instance_1 = new lib.Symbol58();
	this.instance_1.setTransform(116.1,29.9,1,1,0,0,0,8.7,13.6);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(26).to({_off:false},0).to({y:28.3,alpha:1},5).wait(3));

	// s
	this.instance_2 = new lib.Symbol59();
	this.instance_2.setTransform(132.6,52.8,1,1,0,0,0,10.7,21.9);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(24).to({_off:false},0).to({y:51.2,alpha:1},5).wait(5));

	// Layer_4
	this.instance_3 = new lib.Symbol56();
	this.instance_3.setTransform(13.9,78.25,1,1,4.4545,0,0,0,33.6);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(14).to({_off:false},0).to({rotation:0,y:71.85,alpha:1},10,cjs.Ease.quadOut).wait(10));

	// Layer_2
	this.instance_4 = new lib.Symbol55();
	this.instance_4.setTransform(69.25,111.1,0.6849,0.6849,0,0,0,33,33);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(9).to({_off:false},0).to({scaleX:1,scaleY:1,x:69.2,y:111.05,alpha:1},12,cjs.Ease.quadOut).wait(13));

	// Layer_1
	this.instance_5 = new lib.Symbol60();
	this.instance_5.setTransform(69.3,94.95,1,1,0,0,0,69.3,34);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({y:110.95,alpha:1},21,cjs.Ease.backOut).wait(13));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,143.3,146.7);


(lib.ClipGroup = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_46 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(46).call(this.frame_46).wait(1));

	// Symbol 71
	this.instance = new lib.Symbol71();
	this.instance.setTransform(161.35,111.2,0.2308,0.2308,90,0,0,6.5,6.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(35).to({_off:false},0).to({scaleX:1,scaleY:1,rotation:0},9,cjs.Ease.quadOut).wait(3));

	// Symbol 70
	this.instance_1 = new lib.Symbol70();
	this.instance_1.setTransform(211.5,79.1,0.1392,0.1392,45,0,0,8.2,7.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(32).to({_off:false},0).to({regX:8,regY:7.9,scaleX:1,scaleY:1,rotation:0},9,cjs.Ease.quadOut).wait(6));

	// Symbol 69
	this.instance_2 = new lib.Symbol69();
	this.instance_2.setTransform(259.25,100.7,0.1278,0.1278,60.0006,0,0,6.6,6.5);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(29).to({_off:false},0).to({regX:6.7,regY:6.7,scaleX:1,scaleY:1,rotation:0,y:100.75},9,cjs.Ease.quadOut).wait(9));

	// Symbol 68
	this.instance_3 = new lib.Symbol68();
	this.instance_3.setTransform(260.1,137.15,0.3645,0.3645,-45,0,0,5.5,5.5);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(26).to({_off:false},0).to({regX:5.4,regY:5.4,scaleX:1,scaleY:1,rotation:0,y:137.3},9,cjs.Ease.quadOut).wait(12));

	// Layer_8 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_18 = new cjs.Graphics().p("AhZDtIAAnZICzAAIAAHZg");
	var mask_graphics_19 = new cjs.Graphics().p("AiTDtIAAnZIEoAAIAAHZg");
	var mask_graphics_20 = new cjs.Graphics().p("AjODtIAAnZIGdAAIAAHZg");
	var mask_graphics_21 = new cjs.Graphics().p("AkJDtIAAnZIITAAIAAHZg");
	var mask_graphics_22 = new cjs.Graphics().p("AlDDtIAAnZIKIAAIAAHZg");
	var mask_graphics_23 = new cjs.Graphics().p("Al+DtIAAnZIL9AAIAAHZg");
	var mask_graphics_24 = new cjs.Graphics().p("Am5DtIAAnZINzAAIAAHZg");
	var mask_graphics_25 = new cjs.Graphics().p("AnzDtIAAnZIPnAAIAAHZg");
	var mask_graphics_26 = new cjs.Graphics().p("AouDtIAAnZIRdAAIAAHZg");
	var mask_graphics_27 = new cjs.Graphics().p("AppDtIAAnZITTAAIAAHZg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(18).to({graphics:mask_graphics_18,x:163.825,y:94.05}).wait(1).to({graphics:mask_graphics_19,x:169.7,y:94.05}).wait(1).to({graphics:mask_graphics_20,x:175.575,y:94.05}).wait(1).to({graphics:mask_graphics_21,x:181.425,y:94.05}).wait(1).to({graphics:mask_graphics_22,x:187.3,y:94.05}).wait(1).to({graphics:mask_graphics_23,x:193.2,y:94.05}).wait(1).to({graphics:mask_graphics_24,x:199.075,y:94.05}).wait(1).to({graphics:mask_graphics_25,x:204.925,y:94.05}).wait(1).to({graphics:mask_graphics_26,x:210.8,y:94.05}).wait(1).to({graphics:mask_graphics_27,x:216.675,y:94.05}).wait(20));

	// Layer_7
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#F0E8F1").ss(1.1).p("AgXgDIARAQIAfgd");
	this.shape.setTransform(243.2468,92.5632);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#F0E8F1").ss(1.1).p("AgYgDIASAQIAfgd");
	this.shape_1.setTransform(221.6703,104.4602);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#F0E8F1").ss(1.1).p("AgXgDIARAQIAfgd");
	this.shape_2.setTransform(200.2925,92.5629);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#F0E8F1").ss(1.1).p("AgXgDIARAQIAfgd");
	this.shape_3.setTransform(178.6925,104.4629);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#985FA0").s().p("AggAhQgOgNAAgUQAAgSAOgOQANgOATAAQATAAAOAOQAOAOAAASQAAAUgOANQgOAOgTAAQgTAAgNgOg");
	this.shape_4.setTransform(243.25,92.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#985FA0").s().p("AggAhQgOgNAAgUQAAgSAOgOQANgOATAAQAUAAAOAOQANAOAAASQAAAUgNANQgOAOgUAAQgTAAgNgOg");
	this.shape_5.setTransform(200.3,92.35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#985FA0").s().p("AggAiQgOgOAAgUQAAgSAOgOQAOgOASAAQATAAAPAOQANAOAAASQAAAUgNAOQgPANgTAAQgSAAgOgNg");
	this.shape_6.setTransform(221.65,104.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#985FA0").s().p("AggAiQgOgOAAgUQAAgSAOgOQANgOATAAQAUAAAOAOQANAOAAASQAAAUgNAOQgOANgUAAQgTAAgNgNg");
	this.shape_7.setTransform(178.7,104.25);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#7A3185").ss(0.8).p("AhlA8IDLh3");
	this.shape_8.setTransform(232.5,98.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#7A3185").ss(0.8).p("Ahjg9IDHB7");
	this.shape_9.setTransform(211.7,98.75);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#7A3185").ss(0.8).p("AhkA8IDJh3");
	this.shape_10.setTransform(188.825,98.3);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},18).wait(29));

	// Layer_3
	this.instance_4 = new lib.Symbol72();
	this.instance_4.setTransform(375.35,211.75,1,1,0,0,0,101.5,80.9);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:246.45,y:193.35,alpha:1},18,cjs.Ease.quadOut).wait(29));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(145,71.2,332,221.40000000000003);


(lib.Symbol9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol8();
	this.instance.setTransform(150,31.7,1,1,0,0,0,150,31.7);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F2F2F2").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance}]}).wait(1));

	// Layer_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FFFFFF","rgba(255,255,255,0)"],[0,1],0,-77.6,0,72.4).s().p("A3gNAIAA5/MAvBAAAIAAZ/g");
	this.shape_1.setTransform(150.5,83.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F2F2F2").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_2.setTransform(150.4,125.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol9, new cjs.Rectangle(0,0,301,250.5), null);


// stage content:
(lib.OCBC_300x250_v2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		if (myCounter<=1){
			this.rplay.addEventListener("click", fl_MouseClickHandler.bind(this));
			
			this.ctaBTN.addEventListener("click", f2_MouseClickHandler.bind(this));
		}
		
		function fl_MouseClickHandler()
		{
			this.gotoAndPlay(1);
		}
		
		function f2_MouseClickHandler()
		{
			window.open(clickTag, "_blank");
		}
	}
	this.frame_426 = function() {
		myCounter++;
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(426).call(this.frame_426).wait(1));

	// Layer_11
	this.rplay = new lib.Symbol51();
	this.rplay.setTransform(264.25,75.1,1.3088,1,0,0,0,17,10.8);
	this.rplay._off = true;
	new cjs.ButtonHelper(this.rplay, 0, 1, 2, false, new lib.Symbol51(), 3);

	this.timeline.addTween(cjs.Tween.get(this.rplay).wait(417).to({_off:false},0).wait(10));

	// Layer_1
	this.ctaBTN = new lib.Symbol51();
	this.ctaBTN.setTransform(150,125.6,8.8235,11.6279,0,0,0,17,10.8);
	new cjs.ButtonHelper(this.ctaBTN, 0, 1, 2, false, new lib.Symbol51(), 3);

	this.timeline.addTween(cjs.Tween.get(this.ctaBTN).wait(427));

	// Layer_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA2127").s().p("A3bAtIAAhZMAu3AAAIAABZg");
	this.shape.setTransform(150,245.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(427));

	// replay
	this.instance = new lib.Symbol48();
	this.instance.setTransform(264.35,73.8,1,1,0,0,0,17.8,8);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(398).to({_off:false},0).to({alpha:1},19).wait(10));

	// find more
	this.instance_1 = new lib.Symbol50();
	this.instance_1.setTransform(69.1,179.45,1,1,0,0,0,48.8,6.8);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(379).to({_off:false},0).to({alpha:1},19).wait(29));

	// supporting
	this.instance_2 = new lib.Symbol49();
	this.instance_2.setTransform(131.4,125.3,1,1,0,0,0,110.6,35.2);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(360).to({_off:false},0).to({alpha:1},19).wait(48));

	// hand
	this.instance_3 = new lib.ClipGroup();
	this.instance_3.setTransform(174.1,137.1,1,1,0,0,0,174.1,137.1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(253).to({_off:false},0).wait(100).to({x:204.1,alpha:0},7,cjs.Ease.quadOut).to({_off:true},1).wait(66));

	// text3
	this.instance_4 = new lib.Symbol67();
	this.instance_4.setTransform(95.6,124.8,1,1,0,0,0,67.9,47);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(240).to({_off:false},0).to({alpha:1},21).wait(92).to({alpha:0},7).to({_off:true},1).wait(66));

	// book
	this.instance_5 = new lib.Symbol62();
	this.instance_5.setTransform(82.9,142.95,1,1,0,0,0,53.4,62.9);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(131).to({_off:false},0).wait(101).to({y:160.95,alpha:0},7,cjs.Ease.quadOut).to({_off:true},1).wait(187));

	// text2
	this.instance_6 = new lib.Symbol61();
	this.instance_6.setTransform(222.85,142.9,1,1,0,0,0,67.5,58);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(119).to({_off:false},0).to({alpha:1},22).wait(91).to({alpha:0},7).to({_off:true},1).wait(187));

	// bot
	this.instance_7 = new lib.Symbol53();
	this.instance_7.setTransform(205.35,146.7,1,1,0,0,0,71.7,72.5);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(26).to({_off:false},0).wait(87).to({y:154.7,alpha:0},6,cjs.Ease.quadOut).to({_off:true},1).wait(307));

	// text1
	this.instance_8 = new lib.Symbol52();
	this.instance_8.setTransform(101.5,114.65,1,1,0,0,0,81.9,47);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(11).to({_off:false},0).to({alpha:1},19).wait(83).to({alpha:0},6).to({_off:true},1).wait(307));

	// bg
	this.instance_9 = new lib.Symbol9();
	this.instance_9.setTransform(150,125.55,1,1,0,0,0,150,125);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({alpha:1},11).wait(416));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,125,357,167.60000000000002);
// library properties:
lib.properties = {
	id: '4C67F3A136A92E4E81338A9018FE5B2A',
	width: 300,
	height: 250,
	fps: 28,
	color: "#F2F2F2",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.StageGL();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['4C67F3A136A92E4E81338A9018FE5B2A'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;