(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Image = function() {
	this.initialize(img.Image);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,487,347);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol32 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AMPCxQgTgWAAglIAAgPQAAgkATgWQAUgXAhAAQAeAAASATQASAUABAhIgtAAQAAgkgWAAQgaAAAAAnIAAAbQAAAnAaAAQAWAAAAglIAtAAQgBAjgSATQgSAUgeAAQgiAAgTgXgApnCxQgTgWAAglIAAgPQAAgkAUgWQAUgXAhAAQAeAAASATQASATABAiIgtAAQAAgkgXAAQgZAAAAAnIAAAbQAAAnAZAAQAXAAAAglIAtAAQgBAjgSATQgSAUgeAAQgiAAgUgXgAs+CxQgTgWAAglIAAgPQAAgkAUgWQAUgXAhAAQAeAAASATQASATABAiIgtAAQAAgkgXAAQgZAAAAAnIAAAbQAAAnAZAAQAXAAAAglIAtAAQgBAjgSATQgSAUgeAAQgiAAgUgXgAPwDEIgIgeIguAAIgIAeIguAAIA0irIAyAAIA1CrgAPCCEIAeAAIgPg5gAK/DEIAAirIAtAAIAACrgAKCDEIgYg3IgNAAIAAA3IgsAAIAAirIBFAAQAZAAAQAPQAQAPAAAbIAAACQAAAjgbAOIAdA/gAJdBpIATAAQARAAAAgVIAAgCQAAgVgRAAIgTAAgAHRDEIAAiHIglAAIAAgkIB2AAIAAAkIgkAAIAACHgAEwDEIAAirIBwAAIAAAkIhEAAIAAAfIA8AAIAAAjIg8AAIAAAhIBGAAIAAAkgADADEIAAirIAtAAIAACHIAxAAIAAAkgAA+DEIAAirIBwAAIAAAkIhDAAIAAAfIA8AAIAAAjIg8AAIAAAhIBGAAIAAAkgAghDEIgIgeIgvAAIgIAeIgtAAIA0irIAyAAIAzCrgAhPCEIAdAAIgOg5gAjPDEIAAiHIgkAAIAAgkIB1AAIAAAkIgkAAIAACHgAlwDEIAAirIBwAAIAAAkIhDAAIAAAfIA8AAIAAAjIg8AAIAAAhIBGAAIAAAkgAngDEIAAirIAtAAIAACHIAyAAIAAAkgAq2DEIAAirIAtAAIAACrgAuNDEIAAirIAtAAIAACrgAwZDEIAAirIBGAAQAXAAANALQAPALAAAXIAAADQAAAWgSAMQAXALAAAbIAAADQAAAWgPANQgOANgYAAgAvuChIAXAAQAPAAAAgQIAAgEQAAgQgPAAIgXAAgAvuBeIATAAQAQAAAAgPIAAgDQAAgPgQAAIgTAAgAFTAJIAbglIAuAAIglAlgAkggtQgQgQAAgcIAAhrIArAAIAABtQAAAWATAAQATAAAAgXIAAhsIArAAIAABrQAAAcgQAQQgQAPgeAAQgfAAgPgPgAwOgzQgQgUAAgkIAAgPQAAgiATgVQATgWAgAAQAbAAARARQARAQACAcIgqAAQgDgagTAAQgYAAAAAkIAAAaQAAAmAbAAQAYAAABgbIAAgCIgcAAIAAgfIBBAAIAABbIgeAAIgDgTQgKAWgeAAQgcAAgRgVgABtghIgIgdIgsAAIgHAdIgsAAIAyijIAvAAIAyCjgABCheIAbAAIgOg2gAgqghIAAhuIgZBuIgfAAIgZhuIAABuIgoAAIAAijIA7AAIAXBqIAWhqIA4AAIAACjgAnQghIAAijIBrAAIAAAjIhBAAIAAAdIA6AAIAAAhIg6AAIAAAgIBDAAIAAAigAoNghIAAhCIgpAAIAABCIgqAAIAAijIAqAAIAAA+IApAAIAAg+IArAAIAACjgAqfghIgrhgIAABgIgoAAIAAijIAuAAIAqBdIAAhdIAoAAIAACjgAspghIgHgdIgsAAIgIAdIgrAAIAyijIAvAAIAyCjgAtUheIAcAAIgOg2g");
	this.shape.setTransform(105.475,19.975);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol32, new cjs.Rectangle(0,0,211,40), null);


(lib.Symbol31 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AinA+IAAhcIAHAAIAAANQAFgOAQAAQAZAAAAAgIAAAGQAAAhgZAAQgPAAgGgNIAAAjgAigAAIAAAIQAAAaAUAAQASAAAAgbIAAgGQAAgagSAAQgUAAAAAZgAo2A+IAAhcIAHAAIAAANQAFgOAQAAQAZAAAAAgIAAAGQAAAhgZAAQgOAAgHgNIAAAjgAovAAIAAAIQAAAaAUAAQASAAAAgbIAAgGQAAgagSAAQgUAAAAAZgANFAgQgHgJAAgQIAAgGQAAggAbAAQAbAAgBAkIgtAAIAAACQAAAbATAAQAOAAADgQIAIAAQgFAWgUAAQgNAAgHgIgANGgBIAAABIAlAAIAAgBQgBgYgRAAQgSAAgBAYgAMCAgQgHgJAAgQIAAgGQAAggAZAAQAPAAAGANIAAgrIAIAAIAABkIgIAAIAAgNQgGAOgPAAQgLAAgHgIgAMDABIAAAGQAAAbATAAQATAAAAgaIAAgIQAAgZgTAAQgTAAAAAagALGAjQgGgFAAgJQAAgQARgDIAWgCIAAgKQAAgPgOAAQgPAAAAAPIgIAAQACgVAVAAQAKAAAGAFQAGAGAAAKIAAAxIgHAAIAAgKQgGALgOAAQgJAAgFgFgALTAJQgLABAAALQAAANANAAQAIAAAFgFQAFgGAAgIIAAgKgAKFAgQgHgJAAgQIAAgGQAAgPAHgJQAGgIAMAAQAPAAAFANIAAgrIAIAAIAABkIgHAAIAAgNQgGAOgPAAQgMAAgGgIgAKGABIAAAGQAAAbASAAQAUAAAAgaIAAgIQAAgZgUAAQgSAAAAAagAH/AbIgBAMIgHAAIAAhkIAIAAIAAArQAFgNAQAAQAYAAAAAgIAAAGQAAAhgYAAQgQAAgFgNgAH/AAIAAAIQAAAaATAAQATAAAAgbIAAgGQAAgagTAAQgTAAAAAZgAG+AjQgFgFAAgJQAAgQAQgDIAXgCIAAgKQAAgPgOAAQgPAAgBAPIgHAAQABgVAWAAQAKAAAGAFQAGAGAAAKIAAAxIgIAAIAAgKQgGALgOAAQgJAAgFgFgAHLAJQgLABAAALQAAANAOAAQAHAAAGgFQAFgGAAgIIAAgKgAGXAYIAAgvIgLAAIAAgHIALAAIAAgVIAIAAIAAAVIARAAIAAAHIgRAAIAAAuQAAALAKAAQAFAAADgCIAAAHIgJABQgRAAAAgQgAETAHIAAgGQAAgPAHgJQAHgIANAAQAbAAgBAkIgtAAIAAACQAAAbATAAQAPAAADgQIAHAAQgEAWgVAAQgbAAAAghgAEbgBIAAABIAlAAIAAgBQgBgYgRAAQgSAAgBAYgADzAYIAAgvIgMAAIAAgHIAMAAIAAgVIAHAAIAAAVIARAAIAAAHIgRAAIAAAuQAAALALAAQAEAAADgCIAAAHIgIABQgRAAAAgQgAC0ASIAHAAQACAQAPAAQAPAAAAgNQAAgGgEgDQgEgDgJgCQgKgCgEgEQgGgEAAgJQAAgJAGgFQAGgFAJAAQAUAAACAUIgHAAQgCgOgNAAQgOAAAAAMQAAAGAEAEQAEACAIABQAVAEAAAQQAAAJgGAGQgGAFgKAAQgWAAgCgWgAB6ASIAAgwIAHAAIAAAuQAAARAPAAQAQAAAAgVIAAgqIAIAAIAABFIgHAAIAAgLQgFAMgOAAQgUAAAAgWgAA/ASIAHAAQACAQAPAAQAPAAAAgNQAAgGgEgDQgEgDgJgCQgKgCgEgEQgGgEAAgJQAAgJAGgFQAGgFAJAAQAVAAABAUIgHAAQgCgOgNAAQgNAAAAAMQAAAGADAEQAEACAIABQAVAEAAAQQAAAUgWAAQgWAAgCgWgAgNAjQgFgFAAgJQAAgQAQgDIAWgCIAAgKQAAgPgOAAQgOAAgBAPIgHAAQABgVAVAAQAKAAAGAFQAGAGAAAKIAAAxIgIAAIAAgKQgGALgOAAQgIAAgFgFgAAAAJQgLABAAALQAAANANAAQAHAAAGgFQAFgGAAgIIAAgKgAhoAHIAAgGQAAgPAHgJQAHgIANAAQAbAAgBAkIgtAAIAAACQAAAbATAAQAPAAADgQIAHAAQgEAWgVAAQgbAAAAghgAhggBIAAABIAlAAIAAgBQgBgYgRAAQgSAAgBAYgAkeAjQgGgFAAgJQAAgQARgDIAXgCIAAgKQAAgPgOAAQgPAAgBAPIgHAAQABgVAWAAQAVAAAAAVIAAAxIgHAAIAAgKQgGALgOAAQgJAAgFgFgAkRAJQgLABAAALQAAANANAAQAIAAAFgFQAGgGAAgIIAAgKgAlxAjQgGgFAAgJQAAgQARgDIAXgCIAAgKQAAgPgPAAQgOAAgBAPIgIAAQACgVAWAAQAKAAAFAFQAGAGAAAKIAAAxIgHAAIAAgKQgGALgOAAQgJAAgFgFgAlkAJQgLABAAALQAAANANAAQAIAAAFgFQAGgGAAgIIAAgKgAm5AHIAAgGQAAggAZAAQAPAAAGANIAAgrIAHAAIAABkIgHAAIAAgNQgFAOgQAAQgZAAAAghgAmxABIAAAGQAAAbASAAQAUAAAAgaIAAgIQAAgZgUAAQgSAAAAAagAn3AHIAAgGQAAgPAHgJQAHgIANAAQAbAAgBAkIgtAAIAAACQABAbASAAQAPAAADgQIAIAAQgFAWgVAAQgbAAAAghgAnvgBIAAABIAlAAIAAgBQgBgYgRAAQgSAAgBAYgAqJASIAIAAQABAQAPAAQAPAAAAgNQAAgGgEgDQgDgDgJgCQgKgCgFgEQgGgEAAgJQAAgJAGgFQAGgFAKAAQATAAADAUIgIAAQgCgOgMAAQgOAAAAAMQAAAGAEAEQADACAJABQAVAEAAAQQAAAJgGAGQgGAFgLAAQgWAAgCgWgArBAgQgHgJAAgQIAAgGQAAggAbAAQANAAAHAIQAHAJAAAPIAAAGQAAAQgHAJQgHAIgNAAQgNAAgHgIgArAABIAAAGQAAAbATAAQATAAAAgbIAAgGQAAgagTAAQgTAAAAAagAthAjQgGgFAAgJQAAgQARgDIAXgCIAAgKQAAgPgPAAQgPAAAAAPIgIAAQACgVAVAAQAKAAAGAFQAGAGAAAKIAAAxIgHAAIAAgKQgGALgOAAQgJAAgFgFgAtUAJQgLABAAALQAAANANAAQAIAAAFgFQAGgGAAgIIAAgKgAOLAnIAAgMIAJAAIAAAMgAJpAnIAAhFIAIAAIAABFgAJRAnIAAhkIAIAAIAABkgAI5AnIAAhFIAIAAIAABFgAF8AnIAAguQAAgSgPAAQgRAAAAAWIAAAqIgIAAIAAhFIAHAAIABALQAFgMAOAAQAUAAAAAWIAAAwgAgnAnIAAhkIAIAAIAABkgAjlAnIAAhFIAHAAIABANQAFgOANAAIADAAIAAAIIgDgBQgIAAgFAHQgFAGAAALIAAAngAk4AnIAAhkIAIAAIAABkgArcAnIAAguQAAgSgOAAQgRAAAAAWIAAAqIgHAAIAAguQAAgSgOAAQgRAAAAAWIAAAqIgHAAIAAhFIAHAAIAAALQAGgMANAAQAOAAAEANQAFgNAPAAQAUAAAAAWIAAAwgAuNAnIgehgIAJAAIAZBUIAZhUIAJAAIgeBggAOLAMIAAgCQAAgMANgLQAMgKAAgJIAAgBQAAgJgFgFQgFgEgIAAQgSAAgCAUIgIAAQACgbAaAAQALAAAIAHQAHAHAAALIAAABQAAALgMALQgMAKAAAKIAAACgAJpgqIAAgTIAIAAIAAATgAI5gqIAAgTIAIAAIAAATg");
	this.shape.setTransform(93.975,6.175);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol31, new cjs.Rectangle(0,0,188,12.4), null);


(lib.Symbol30 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00B859").s().p("AGPB+QgKgNAAgXIAAgJQAAgWALgOQAMgNAVAAQARAAALAKQAKALACARIgbAAQgCgQgMAAQgPAAAAAXIAAAQQAAAYARAAQAPAAABgRIAAgBIgSAAIAAgUIApAAIAAA6IgTAAIgCgMQgHAOgSAAQgSAAgKgNgAChB9QgLgNAAgWIAAgJQAAgWALgNQAMgOAVAAQAUAAANAOQALANAAAWIAAAJQAAAWgLANQgNAOgUAAQgVAAgMgOgACyBNIAAARQAAAXAQAAQAQAAAAgXIAAgRQAAgXgQAAQgQAAAAAXgAE8CJIAAgOQAAgNAFgJQAFgJAOgJQAMgJADgDQADgEAAgFIAAgBQAAgJgIAAQgJAAAAAOIgYAAQABgQAJgJQAIgJAQAAQAOAAAJAIQAIAIAAANIAAABQAAAKgEAGQgEAIgMAIQgLAIgEAFQgDADAAAGIAnAAIAAAVgAD0CJIAAgOQAAgNAFgJQAFgJAOgJIAOgMQADgEAAgFIAAgBQAAgJgHAAQgJAAAAAOIgYAAQAAgQAJgJQAJgJAPAAQAOAAAJAIQAIAIAAANIAAABQAAAKgDAGQgFAIgMAIQgLAIgDAFQgDADAAAGIAmAAIAAAVgAB1CJIgPghIgHAAIAAAhIgbAAIAAhnIApAAQAPAAAKAJQAKAJAAAQIAAABQAAAWgQAIIARAmgABfBSIALAAQAKAAAAgNIAAgBQAAgMgKAAIgLAAgAgKCJIAAhnIBDAAIAAAWIgpAAIAAASIAlAAIAAAVIglAAIAAAUIArAAIAAAWgAhWCJIAAgTIAjg+IggAAIAAgWIA/AAIAAATIgjA+IAkAAIAAAWgAh7CJIAAhnIAcAAIAABngAjXCJIAAhnIAlAAQAVAAAMALQANAMAAAYIAAAJQAAAYgNAMQgMALgVAAgAi8BzIAIAAQAUAAAAgVIAAgRQAAgVgUAAIgIAAgAj7CJIgPghIgHAAIAAAhIgbAAIAAhnIApAAQAPAAAKAJQAKAJAAAQIAAABQAAAWgQAIIARAmgAkRBSIALAAQAKAAAAgNIAAgBQAAgMgKAAIgLAAgAl7CJIAAhnIBEAAIAAAWIgpAAIAAASIAlAAIAAAVIglAAIAAAUIArAAIAAAWgAm8CJIgchnIAdAAIAPBGIAPhGIAcAAIgcBngACBgOQgLgNAAgWIAAgJQAAgWALgNQAMgOAVAAQAUAAAMAOQAMANAAAWIAAAJQAAAWgMANQgMAOgUAAQgVAAgMgOgACSg+IAAARQAAAXAQAAQAQAAAAgXIAAgRQAAgXgQAAQgQAAAAAXgAAjgNQgKgNAAgXIAAgJQAAgWALgOQAMgNAVAAQARAAALAKQALALABARIgbAAQgCgQgMAAQgPAAAAAXIAAAQQAAAYARAAQAPAAABgRIAAgBIgSAAIAAgUIApAAIAAA6IgTAAIgCgMQgHAOgSAAQgSAAgKgNgAi9gOQgLgNAAgWIAAgJQAAgWALgNQAMgOAVAAQAUAAANAOQALANAAAWIAAAJQAAAWgLANQgNAOgUAAQgVAAgMgOgAisg+IAAARQAAAXAQAAQAQAAAAgXIAAgRQAAgXgQAAQgQAAAAAXgAkXgOQgMgNAAgWIAAgJQAAgWAMgOQAMgNAUAAQASAAALALQALAMAAAUIgbAAQAAgVgNAAQgQAAAAAXIAAAQQAAAYAQAAQANAAAAgWIAbAAQAAAUgLAMQgLAMgSAAQgUAAgMgOgADbgCIAAgYIAYAAIAAAYgAgLgCIAAhnIAaAAIAABngAhngCIAAhnIAkAAQAWAAAMALQANAMAAAYIAAAJQAAAYgNAMQgNALgVAAgAhMgYIAIAAQATAAAAgVIAAgRQAAgVgTAAIgIAAgADbg2IAAgYIAYAAIAAAYgAiphzIARgXIAbAAIgWAXg");
	this.shape.setTransform(69.375,19.625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AnYDRQhWAAg+g9Qg9g+AAhWQAAhWA9g9QA+g9BWAAIOxAAQBWAAA+A9QA9A9AABWQAABWg9A+Qg+A9hWAAgAGcAhQgLANAAAWIAAAKQAAAWAKANQAKAOASAAQASAAAHgOIACAMIATAAIAAg6IgpAAIAAATIASAAIAAABQgBASgPAAQgRAAAAgYIAAgRQAAgXAPAAQAMAAACARIAbAAQgCgSgKgKQgLgLgRAAQgVAAgMAOgACtAhQgLAOAAAVIAAAKQAAAWALANQAMAOAVAAQAUAAANgOQALgNAAgWIAAgKQAAgWgLgNQgNgOgUAAQgVAAgMAOgAFyAxIAAAAQAAAGgDADQgDAEgMAIQgOAJgFAKQgFAIAAAOIAAAOIBDAAIAAgWIgnAAQAAgFADgEQAEgEALgIQAMgJAEgHQAEgHAAgKIAAgBQAAgNgIgIQgJgIgOAAQgQAAgIAJQgJAJgBARIAYAAQAAgOAJAAQAIAAAAAJgAEpAxIAAAAQAAAGgDADIgOAMQgOAJgFAKQgFAIAAAOIAAAOIBCAAIAAgWIgmAAQAAgFADgEQADgEALgIQAMgJAFgHQADgGAAgLIAAgBQAAgNgIgIQgJgIgOAAQgPAAgJAJQgJAJAAARIAYAAQAAgOAJAAQAHAAAAAJgACdB9IgRgmQAQgIAAgWIAAgCQAAgQgKgJQgKgJgPAAIgpAAIAABoIAbAAIAAgiIAHAAIAPAiIAcAAgAABB9IBGAAIAAgWIgrAAIAAgUIAlAAIAAgWIglAAIAAgSIApAAIAAgWIhEAAgAhHArIAgAAIgjA+IAAAUIBDAAIAAgWIgkAAIAjg+IAAgUIg/AAgAhvB9IAcAAIAAhoIgcAAgAjLB9IAlAAQAVAAAMgMQANgMAAgXIAAgKQAAgXgNgMQgMgMgVAAIglAAgAjTB9IgRgmQAQgIAAgWIAAgCQAAgQgKgJQgKgJgPAAIgpAAIAABoIAbAAIAAgiIAHAAIAPAiIAcAAgAlvB9IBGAAIAAgWIgrAAIAAgUIAlAAIAAgWIglAAIAAgSIApAAIAAgWIhEAAgAmwB9IAfAAIAchoIgcAAIgPBHIgPhHIgdAAgACNhqQgLAOAAAVIAAAKQAAAWALANQAMAOAVAAQAUAAAMgOQAMgNAAgWIAAgKQAAgWgMgNQgMgOgUAAQgVAAgMAOgAAwhqQgLANAAAWIAAAKQAAAWAKANQAKAOASAAQASAAAHgOIACAMIATAAIAAg6IgpAAIAAATIASAAIAAABQgBASgPAAQgRAAAAgYIAAgRQAAgXAPAAQAMAAACARIAbAAQgBgSgLgKQgLgLgRAAQgVAAgMAOgAixhqQgLAOAAAVIAAAKQAAAWALANQAMAOAVAAQAUAAANgOQALgNAAgWIAAgKQAAgWgLgNQgNgOgUAAQgVAAgMAOgAkLhqQgMANAAAWIAAAKQAAAWAMANQAMAOAUAAQASAAALgMQALgMAAgVIgbAAQAAAWgNAAQgQAAAAgXIAAgQQAAgYAQAAQANAAAAAWIAbAAQAAgUgLgMQgLgMgSAAQgUAAgMAOgADngOIAYAAIAAgYIgYAAgAAAgOIAbAAIAAhoIgbAAgAhbgOIAkAAQAVAAANgMQANgMAAgXIAAgKQAAgXgNgMQgMgMgWAAIgkAAgADnhCIAYAAIAAgYIgYAAgAidiAIAWAAIAWgXIgbAAgAC+BRIAAgQQAAgYAQAAQAQAAAAAYIAAAQQAAAYgQAAQgQAAAAgYgAiwBnIAAg8IAIAAQAUAAAAAWIAAAQQAAAWgUAAgABrBFIAAgaIALAAQAKAAAAAMIAAACQAAAMgKAAgAkFBFIAAgaIALAAQAKAAAAAMIAAACQAAAMgKAAgACeg6IAAgQQAAgYAQAAQAQAAAAAYIAAAQQAAAYgQAAQgQAAAAgYgAigg6IAAgQQAAgYAQAAQAQAAAAAYIAAAQQAAAYgQAAQgQAAAAgYgAhAgkIAAg8IAIAAQATAAAAAWIAAAQQAAAWgTAAg");
	this.shape_1.setTransform(68.175,20.875);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol30, new cjs.Rectangle(0,0,136.4,41.8), null);


(lib.Symbol28 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00B859").s().p("AGwCIQgLgOAAgZIAAgKQAAgXAMgPQANgPAWAAQATAAAMAMQALALABATIgcAAQgCgJgDgEQgDgFgHAAQgRAAAAAZIAAASQAAAaASAAQARAAABgTIAAgBIgTAAIAAgVIAsAAIAAA+IgUAAIgDgNQgHAPgUAAQgTAAgLgOgACvCHQgNgOAAgYIAAgKQAAgXANgPQANgPAWAAQAWAAANAPQANAPAAAXIAAAKQAAAYgNAOQgNAPgWAAQgWAAgNgPgADBBUIAAARQAAAaARAAQARAAAAgaIAAgRQAAgagRAAQgRAAAAAagAFWCUIAAgPQAAgOAGgJQAFgLAPgKQAMgIAEgEQADgEAAgGIAAgBQAAgJgIAAQgKAAAAAPIgaAAQACgmAjAAQAPAAAJAJQAJAJAAAOIAAABQAAALgEAHQgEAIgNAJQgMAJgEAEQgDAEgBAGIAqAAIAAAXgAEICUIAAgPQAAgOAFgJQAGgLAPgKQAMgIADgEQADgEAAgGIAAgBQAAgJgIAAQgJAAAAAPIgaAAQAAgSAKgKQAJgKARAAQAPAAAKAJQAJAJAAAOIAAABQAAALgEAHQgFAIgNAJQgMAJgDAEQgEAEAAAGIApAAIAAAXgAB+CUIgPgkIgJAAIAAAkIgdAAIAAhwIAuAAQAQAAAKAKQALAKAAARIAAACQAAAXgRAJIASApgABmBYIANAAQALAAAAgNIAAgCQAAgNgLAAIgNAAgAgKCUIAAhwIBIAAIAAAYIgsAAIAAAUIAnAAIAAAXIgnAAIAAAWIAtAAIAAAXgAhdCUIAAgVIAmhDIgjAAIAAgYIBEAAIAAAWIglBDIAnAAIAAAXgAiECUIAAhwIAdAAIAABwgAjoCUIAAhwIAnAAQAXAAANANQAOANAAAZIAAAKQAAAagOANQgNAMgXAAgAjLB9IAJAAQAVAAAAgYIAAgRQAAgNgGgGQgFgFgKAAIgJAAgAkQCUIgPgkIgJAAIAAAkIgdAAIAAhwIAtAAQARAAAKAKQALAKAAARIAAACQAAAXgRAJIASApgAkoBYIANAAQALAAAAgNIAAgCQAAgNgLAAIgNAAgAmZCUIAAhwIBJAAIAAAYIgsAAIAAAUIAnAAIAAAXIgnAAIAAAWIAtAAIAAAXgAngCUIgfhwIAgAAIAQBNIARhNIAeAAIgfBwgACMgPQgNgPAAgXIAAgKQAAgYANgOQANgPAWAAQAWAAANAPQANAOAAAYIAAAKQAAAYgNAOQgNAPgWAAQgWAAgNgPgACehDIAAASQAAAZARAAQARAAAAgZIAAgSQAAgZgRAAQgRAAAAAZgAAmgOQgLgPAAgYIAAgKQAAgYANgOQANgPAWAAQATAAALALQALAMACATIgdAAQgDgSgMAAQgRAAAAAZIAAASQAAAZATAAQAQAAABgSIAAgBIgTAAIAAgWIAsAAIAAA/IgUAAIgCgNQgIAPgUAAQgTAAgLgOgAjMgPQgMgOAAgYIAAgKQAAgYAMgOQANgPAWAAQAWAAANAPQANAOAAAYIAAAKQAAAYgNAOQgNAPgWAAQgWAAgNgPgAi6hDIAAASQAAAZARAAQASAAAAgZIAAgSQAAgZgSAAQgRAAAAAZgAkugPQgMgOAAgYIAAgKQAAgYAMgOQANgPAWAAQATAAAMAMQAMANABAWIgeAAQAAgXgOAAQgRAAAAAZIAAASQAAAZARAAQAOAAAAgYIAeAAQgBAXgMANQgLAMgUAAQgWAAgNgPgADtgCIAAgaIAaAAIAAAagAgMgCIAAhwIAdAAIAABwgAhvgCIAAhwIAnAAQAXAAANAMQAOANAAAaIAAAKQAAAZgOAOQgNAMgXAAgAhSgaIAIAAQAVAAAAgXIAAgSQAAgNgFgFQgFgFgLAAIgIAAgADtg6IAAgaIAaAAIAAAagAi2h8IARgZIAeAAIgYAZg");
	this.shape.setTransform(75.025,21.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AoQDiQhWAAg9g9Qg+g9AAhXIAAghQAAhXA+g9QA9g9BWAAIQhAAQBWAAA9A9QA+A9AABXIAAAhQAABXg+A9Qg9A9hWAAgAG+AkQgNAOAAAYIAAAKQABAYAKAOQAMAPATAAQAUAAAHgPIACANIAUAAIAAg/IgsAAIAAAWIATAAIAAABQgBASgQAAQgSAAAAgZIAAgSQAAgZAQAAQAIAAADAEQADAEABAJIAdAAQgBgSgLgMQgMgLgTAAQgWAAgNAPgAC8AkQgNAOAAAYIAAAKQAAAXANAPQANAPAWAAQAWAAANgPQAMgOAAgYIAAgKQAAgYgMgOQgNgPgWAAQgWAAgNAPgAGPA1IAAAAQAAAGgCAEQgEAEgMAJQgPAKgGAKQgFAJAAAPIAAAPIBHAAIAAgXIgpAAQAAgGAEgEQADgFANgIQANgKAEgIQAEgHAAgLIAAgBQAAgOgJgIQgJgJgPAAQgkAAgBAlIAaAAQAAgPAKAAQAIAAgBAKgAFBA1IAAAAQAAAGgDAEQgEAEgLAJQgQAKgFAKQgGAJABAPIAAAPIBHAAIAAgXIgpAAQAAgGADgEQAEgFAMgIQANgKAEgIQAEgHABgLIAAgBQgBgOgIgIQgKgJgPAAQgRAAgJAKQgKAJAAASIAaAAQAAgPAJAAQAIAAAAAKgACqCHIgSgpQARgJAAgYIAAgBQAAgSgLgKQgKgJgQAAIguAAIAABwIAdAAIAAgkIAJAAIAPAkIAfAAgAABCHIBLAAIAAgYIguAAIAAgWIAoAAIAAgXIgoAAIAAgTIAtAAIAAgYIhKAAgAhOAvIAkAAIgmBDIAAAVIBJAAIAAgYIgnAAIAlhDIAAgVIhFAAgAh3CHIAdAAIAAhwIgdAAgAjcCHIAoAAQAXAAANgMQAOgOAAgZIAAgKQAAgagOgNQgNgMgXAAIgoAAgAjkCHIgTgpQASgJAAgYIAAgBQAAgSgLgKQgLgJgQAAIgtAAIAABwIAdAAIAAgkIAIAAIAQAkIAfAAgAmMCHIBKAAIAAgYIguAAIAAgWIAnAAIAAgXIgnAAIAAgTIAtAAIAAgYIhJAAgAnTCHIAhAAIAehwIgdAAIgRBMIgRhMIgfAAgACZhzQgNAPAAAXIAAAKQAAAYANAPQANAPAWAAQAWAAANgPQAMgPAAgYIAAgKQAAgXgMgPQgNgPgWAAQgWAAgNAPgAA1hzQgOAPAAAXIAAAKQAAAZAMAOQAKAPAUAAQAUAAAHgQIACANIAVAAIAAg+IgsAAIAAAVIATAAIAAABQgBATgQAAQgTAAAAgaIAAgSQAAgZARAAQAMAAACASIAdAAQgBgTgLgLQgMgMgSAAQgWAAgNAPgAi/hzQgNAPAAAXIAAAKQAAAYANAPQANAPAWAAQAWAAANgPQANgPAAgYIAAgKQAAgXgNgPQgNgPgWAAQgWAAgNAPgAkhhzQgNAPAAAXIAAAKQAAAYANAPQAMAPAXAAQATAAAMgNQAMgNAAgWIgdAAQAAAYgOAAQgSAAABgaIAAgRQgBgaASAAQAOAAAAAXIAdAAQAAgVgMgNQgMgNgTAAQgWAAgNAPgAD6gQIAaAAIAAgZIgaAAgAAAgQIAdAAIAAhwIgdAAgAhigQIAmAAQAYAAANgMQAOgNAAgaIAAgKQAAgZgOgNQgNgNgYAAIgmAAgAD6hIIAaAAIAAgZIgaAAgAipiKIAXAAIAXgZIgdAAgADOBYIAAgSQgBgZASAAQARAAAAAZIAAASQAAAZgRAAQgSAAABgZgAi+BvIAAhAIAJAAQAKAAAFAFQAFAFAAANIAAASQAAAXgUAAgABzBLIAAgcIAMAAQAMAAAAANIAAABQAAAOgMAAgAkbBLIAAgcIANAAQALAAAAANIAAABQAAAOgLAAgACrg/IAAgRQAAgaARAAQARAAAAAaIAAARQAAAagRAAQgRAAAAgagAitg/IAAgRQAAgaARAAQARAAAAAaIAAARQAAAagRAAQgRAAAAgagAhGgnIAAhBIAJAAQAKAAAGAFQAFAGAAANIAAARQAAAYgVAAg");
	this.shape_1.setTransform(73.75,22.575);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol28, new cjs.Rectangle(0,0,147.5,45.2), null);


(lib.Symbol27 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgXAKQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgNQAAgBAAgBQAAAAABgBQAAAAABAAQAAgBABAAIAvAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAABIAAANQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape.setTransform(10.625,20.95);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgXALQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIAAgNQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAIAvAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIAAANQAAABAAABQAAAAgBABQAAAAgBABQAAAAgBAAg");
	this.shape_1.setTransform(10.625,13.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgXALQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgNQAAgBAAgBQAAAAABgBQAAAAABAAQAAgBABAAIAvAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAABIAAANQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAg");
	this.shape_2.setTransform(10.625,17.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbAxQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIAAhbQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAQAAQABAAABAAQABAAAAABQABAAAAABQAAAAAAABIAABJIAjAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAPQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_3.setTransform(31.15,17.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgHAxQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBIAAhbQAAgBAAAAQABgBAAAAQABgBAAAAQABAAABAAIAPAAQABAAABAAQAAAAABABQAAAAABABQAAAAAAABIAABbQAAABAAAAQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_4.setTransform(25.275,17.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXAsQgIgEgBgDQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAgBAAAAIAJgNIADgBIADABIAGAEQAHAEAGAAQAKAAAAgHQAAgFgOgHQgOgGgFgDQgJgIAAgMQAAgNAJgIQAKgJAOAAQAMAAAKAGIAIAFQAAAAAAABQABAAAAABQAAAAAAABQgBAAAAABIgHANQAAABAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgIgHgKAAQgKAAAAAIQAAAEAOAHQANAFAGAEQAJAIAAAMQAAAOgJAIQgJAJgPAAQgNAAgLgHg");
	this.shape_5.setTransform(3.43,17.125);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgbAkQgPgPgBgVQABgVAPgPQAQgPATAAQAUAAAPAOIABACIgBABIgMANQAAAAgBAAQAAABgBAAQAAAAgBgBQAAAAAAAAQgIgIgMAAQgLAAgJAJQgJAJABALQgBAMAJAJQAJAJALgBQAMABAIgIQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAABIAMALIABACIgBABQgPAOgUABQgUAAgPgQg");
	this.shape_6.setTransform(18.75,17.15);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFC20E").s().p("Ag5AhIAAgWQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAQAZAAAXgKQAVgMAOgUIACgBIAaAAIABABQAAAAAAABQABAAAAAAQAAAAgBABQAAAAAAAAQgRAfgeARQgdASgkAAQAAAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAg");
	this.shape_7.setTransform(25.2,26.525);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFC20E").s().p("AhhAZQgqgcgTgxIAAgCIACgBIAXAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABQASAmAkAWQAkAXApAAQAqAAAkgXQAkgWASgmQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIAXAAIACABIAAACQgSAwgrAdQgsAfg2AAQg1AAgsgfg");
	this.shape_8.setTransform(19.65,28.625);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFC20E").s().p("Ag2AjIgCgBIAAgCQARggAegQQAdgSAjAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAWQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAQgYAAgXAKQgVAMgOAUIgCABg");
	this.shape_9.setTransform(13.9625,7.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFC20E").s().p("ACGA4IgCgBQgSgngkgWQgkgXgqAAQgqAAgjAXQgkAWgSAnIgCABIgXAAIgCgBIAAgCQATgxArgcQAsgfA0AAQA1AAAsAfQArAcATAxIAAACIgCABg");
	this.shape_10.setTransform(19.525,5.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAMAZQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIgDgLIgNAAIgDALQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgJAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIgBgBIARguQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAIAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAQAuQAAAAABAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgBABgAADADIgDgJIAAgBIAAABIgDAJIAGAAg");
	this.shape_11.setTransform(22.875,39.725);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgBADIgCgCQAAAAgBAAQAAAAAAABQAAAAAAABQAAAAAAABIgBABIgFAAIgCgBQAAgIAJAAQADAAACACIACABQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAAAAAAAQABAAAAAAIAFAAIABABQAAAJgJAAQgCAAgDgDg");
	this.shape_12.setTransform(22.85,36.25);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgOAZQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgtQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAbAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAHQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAgBAAIgQAAIAAAIIANAAQAAAAAAAAQABAAAAABQAAAAAAAAQABABAAAAIAAAGQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgNAAIAAAJIARAAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAHQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_13.setTransform(14.85,39.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgPAZQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgtQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAPAAQAQAAAAAOQAAAFgEAEQAGAEABAHQAAAPgSAAgAgFAOIAGAAQAFAAAAgFQAAgEgFAAIgGAAgAgFgFIAFAAQAEAAAAgEQAAgEgEAAIgFAAg");
	this.shape_14.setTransform(10.8,39.725);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgRASQgIgHAAgLQAAgKAIgHQAHgIAKAAQALAAAHAIQAIAHAAAKQAAALgIAHQgHAIgLAAQgKAAgHgIgAgIgJQgEAEgBAFQABAGAEAEQADAEAFAAQAGAAAEgEQADgEAAgGQAAgFgDgEQgEgEgGAAQgFAAgDAEg");
	this.shape_15.setTransform(27.75,39.725);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgDAZQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgkIgOAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgHQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAmAAQABAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIAAAHQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgNAAIAAAkQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAg");
	this.shape_16.setTransform(18.95,39.725);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol27, new cjs.Rectangle(0,0,35.6,42.3), null);


(lib.Symbol26 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgWAoQgIgGABgMQAAgUAVgDIAdgFIAAgMQgBgUgSAAQgRAAgCAUIgKAAQACgOAHgHQAIgHAMAAQANAAAIAHQAIAIAAANIAAA/IgKAAIAAgNQgHAPgSAAQgMAAgGgHgAgFAGQgOADgBANQABAQARAAQAJAAAHgGQAGgHABgLIAAgNg");
	this.shape.setTransform(264.1,8.525);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgXAkQgJgMAAgUIAAgHQAAgVAJgLQAJgLAQAAQANAAAJAIQAIAIABAOIgKAAQgCgVgTAAQgYAAAAAiIAAAHQAAAiAYAAQATAAACgWIAKAAQgBAPgIAIQgJAIgNAAQgQAAgJgLg");
	this.shape_1.setTransform(256.575,8.525);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgEBBIAAhZIAJAAIAABZgAgEgoIAAgYIAJAAIAAAYg");
	this.shape_2.setTransform(251.075,6.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgSAuIAAhZIAKAAIAAASQAGgUARAAIADABIAAAKIgDgBQgLAAgFAIQgHAJAAAPIAAAxg");
	this.shape_3.setTransform(247.45,8.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgIAnIAAg+IgPAAIAAgJIAPAAIAAgbIAKAAIAAAbIAVAAIAAAJIgVAAIAAA8QAAAOANAAQAFAAAEgCIAAAJQgGACgEAAQgWAAAAgVg");
	this.shape_4.setTransform(241.7,7.275);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYA3QgJgMAAgUIAAgIQAAgUAJgLQAJgLAQAAQAkAAgDAvIg5AAIAAADQAAAiAYAAQATAAAEgUIAKAAQgGAdgbAAQgQAAgJgLgAgXALIAAABIAvAAIAAgBQgBgdgWAAQgWAAgCAdgAgGgpIATgYIAOAAIgXAYg");
	this.shape_5.setTransform(235.2831,6.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgEBBIAAiBIAJAAIAACBg");
	this.shape_6.setTransform(229.65,6.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgYAkQgJgMAAgUIAAgHQAAgVAJgLQAJgLAQAAQAkAAgDAvIg5AAIAAADQAAAiAYAAQATAAAEgUIAKAAQgGAdgbAAQgQAAgJgLgAgXgHIAAABIAvAAIAAgBQgBgegWAAQgWAAgCAeg");
	this.shape_7.setTransform(224.1831,8.525);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgWAoQgIgGABgMQAAgUAVgDIAcgFIAAgMQAAgUgSAAQgRAAgCAUIgKAAQACgOAHgHQAIgHAMAAQANAAAIAHQAIAIAAANIAAA/IgKAAIgBgNQgHAPgRAAQgMAAgGgHgAgFAGQgOADAAANQAAAQARAAQAJAAAHgGQAGgHAAgLIAAgNg");
	this.shape_8.setTransform(213.15,8.525);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgIAnIAAg+IgPAAIAAgJIAPAAIAAgbIAJAAIAAAbIAXAAIAAAJIgXAAIAAA8QAAAOAOAAQAGAAADgCIAAAJQgGACgFAAQgUAAgBgVg");
	this.shape_9.setTransform(206.65,7.275);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgYAkQgJgMAAgUIAAgHQAAgVAJgLQAJgLAQAAQAjAAgCAvIg5AAIAAADQAAAiAYAAQASAAAEgUIAKAAQgFAdgbAAQgQAAgJgLgAgXgHIAAABIAvAAIAAgBQgCgegVAAQgXAAgBAeg");
	this.shape_10.setTransform(200.2781,8.525);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgEBBIAAiBIAJAAIAACBg");
	this.shape_11.setTransform(194.65,6.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgXAkQgJgMAAgUIAAgHQAAgrAiAAQANAAAIAIQAIAIABAOIgKAAQgBgVgUAAQgXAAAAAiIAAAHQAAAiAXAAQATAAADgWIAKAAQgEAfgcAAQgPAAgJgLg");
	this.shape_12.setTransform(189.325,8.525);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgEBBIAAhZIAJAAIAABZgAgEgoIAAgYIAJAAIAAAYg");
	this.shape_13.setTransform(183.775,6.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgXAkQgJgMAAgUIAAgHQAAgrAiAAQAbAAAEAeIgKAAQgDgVgTAAQgXAAAAAiIAAAHQAAAiAXAAQATAAADgWIAKAAQgEAfgcAAQgPAAgJgLg");
	this.shape_14.setTransform(178.425,8.525);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgEBBIAAhZIAJAAIAABZgAgEgoIAAgYIAJAAIAAAYg");
	this.shape_15.setTransform(172.925,6.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgYAwIAAAQIgJAAIAAiBIAKAAIAAA3QAHgRASAAQAPAAAJALQAIALAAAUIAAAIQAAAUgIAMQgJALgPAAQgTAAgHgSgAgYANIAAALQAAAQAHAIQAHAJALAAQAXAAAAgiIAAgIQAAghgXAAQgZAAAAAfg");
	this.shape_16.setTransform(167.275,6.625);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgXAoQgGgHAAgLQgBgUAWgDIAcgFIAAgMQAAgUgSAAQgSAAgBAUIgJAAQAAgOAJgHQAHgHAMAAQANAAAIAHQAIAIgBANIAAA/IgJAAIAAgNQgIAPgRAAQgLAAgIgHgAgFAGQgOACAAAOQAAAQARAAQAJAAAGgGQAIgHgBgLIAAgNg");
	this.shape_17.setTransform(155.8,8.525);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAsAuIAAg8QAAgWgSAAQgVAAAAAcIAAA2IgJAAIAAg8QAAgWgSAAQgKAAgGAHQgGAIAAANIAAA2IgKAAIAAhZIAKAAIAAAOQAHgQASAAQASAAAFASQAHgSASAAQAMAAAHAIQAHAIgBANIAAA+g");
	this.shape_18.setTransform(145.75,8.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgXAmQgGgIAAgNIAAg+IAKAAIAAA8QAAAWASAAQAKAAAFgHQAGgIAAgNIAAg2IAKAAIAABZIgJAAIgBgOQgHAQgRAAQgMAAgHgIg");
	this.shape_19.setTransform(135.25,8.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgSAuIAAhZIAKAAIAAASQAGgUARAAIADABIAAAKIgDgBQgLAAgFAIQgGAJgBAPIAAAxg");
	this.shape_20.setTransform(126.2,8.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgWAoQgHgGAAgMQAAgUAVgDIAdgFIAAgMQAAgUgTAAQgSAAgBAUIgKAAQABgOAIgHQAIgHAMAAQANAAAIAHQAHAIAAANIAAA/IgJAAIAAgNQgHAPgSAAQgLAAgHgHgAgFAGQgOACAAAOQAAAQARAAQAJAAAHgGQAHgHAAgLIAAgNg");
	this.shape_21.setTransform(119.275,8.525);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAUBBIAAg8QAAgWgSAAQgJAAgHAHQgFAHAAANIAAA3IgLAAIAAiBIALAAIAAA2QAGgQARAAQAaAAAAAdIAAA+g");
	this.shape_22.setTransform(111.6,6.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAUAuIAAg7QAAgXgSAAQgKAAgGAHQgGAHAAAOIAAA2IgKAAIAAhZIAKAAIAAAOQAHgQARAAQANAAAHAIQAHAIAAAOIAAA9g");
	this.shape_23.setTransform(103.475,8.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgWAoQgIgHABgLQAAgUAVgDIAdgFIAAgMQgBgUgSAAQgSAAgBAUIgKAAQACgOAHgHQAIgHANAAQANAAAHAHQAIAIAAANIAAA/IgKAAIAAgNQgHAPgSAAQgMAAgGgHgAgFAGQgOACAAAOQAAAQARAAQAJAAAHgGQAGgHABgLIAAgNg");
	this.shape_24.setTransform(95.35,8.525);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgfAlIALAAQACAQATAAQAXABAAgXIAAgSQgHAQgSABQgPgBgIgKQgKgMABgTIAAgHQgBgUAKgLQAIgLAPAAQASAAAIASIAAgQIAKAAIAABaQAAAPgJAHQgJAJgQAAQgdAAgDgZgAgXgTIAAAHQAAAhAXAAQAMAAAGgIQAHgKgBgOIAAgJQAAgggYAAQgXAAAAAhg");
	this.shape_25.setTransform(87.2,10);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgXAoQgGgGAAgMQgBgUAWgDIAcgFIAAgMQAAgUgSAAQgRAAgCAUIgJAAQAAgOAJgHQAHgHAMAAQANAAAIAHQAIAIgBANIAAA/IgJAAIgBgNQgGAPgSAAQgLAAgIgHgAgFAGQgOADAAANQgBAQASAAQAJAAAGgGQAIgHgBgLIAAgNg");
	this.shape_26.setTransform(76.15,8.525);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgYAkQgJgMAAgUIAAgHQAAgVAJgLQAJgLAQAAQAjAAgCAvIg5AAIAAADQABAiAXAAQASAAAEgUIALAAQgGAdgbAAQgQAAgJgLgAgXgHIAAABIAvAAIAAgBQgCgegVAAQgXAAgBAeg");
	this.shape_27.setTransform(65.5781,8.525);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgdASIAKAAQACAVASAAQATAAAAgSQAAgHgFgEQgFgEgKgDQgNgCgGgEQgHgGAAgMQAAgMAIgHQAHgGALAAQAaAAADAbIgKAAQgCgTgRAAQgQAAAAAQQAAAIAFAEQAEADAKADQANADAHAEQAHAGAAALQAAANgIAHQgIAHgNAAQgbAAgDgdg");
	this.shape_28.setTransform(57.975,8.525);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgWAFIAAgJIAsAAIAAAJg");
	this.shape_29.setTransform(51.2,7.975);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgYAkQgJgMAAgUIAAgHQAAgVAJgLQAJgLAQAAQAkAAgDAvIg5AAIAAADQAAAiAYAAQATAAAEgUIAKAAQgGAdgbAAQgQAAgJgLgAgXgHIAAABIAvAAIAAgBQgBgegWAAQgWAAgCAeg");
	this.shape_30.setTransform(44.0831,8.525);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgHAnIAAg+IgQAAIAAgJIAQAAIAAgbIAJAAIAAAbIAVAAIAAAJIgVAAIAAA8QgBAOANAAQAHAAADgCIAAAJQgGACgFAAQgUAAAAgVg");
	this.shape_31.setTransform(37.35,7.275);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgEBBIAAhZIAJAAIAABZgAgEgoIAAgYIAJAAIAAAYg");
	this.shape_32.setTransform(33.225,6.5);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgEBBIAAiBIAJAAIAACBg");
	this.shape_33.setTransform(30.1,6.5);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgEBBIAAhZIAJAAIAABZgAgEgoIAAgYIAJAAIAAAYg");
	this.shape_34.setTransform(27.025,6.5);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgYAwIAAAQIgJAAIAAiBIAKAAIAAA3QAHgRASAAQAPAAAJALQAJALgBAUIAAAIQABAVgJALQgJALgPAAQgSAAgIgSgAgXANIAAALQAAAQAGAIQAHAJALAAQAXAAAAgiIAAgIQAAghgXAAQgYAAAAAfg");
	this.shape_35.setTransform(21.4,6.625);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgWAoQgIgGABgMQAAgUAVgDIAcgFIAAgMQAAgUgSAAQgRAAgCAUIgKAAQACgOAHgHQAIgHAMAAQANAAAIAHQAIAIAAANIAAA/IgKAAIgBgNQgHAPgRAAQgMAAgGgHgAgFAGQgOADAAANQAAAQARAAQAJAAAHgGQAGgHAAgLIAAgNg");
	this.shape_36.setTransform(12.9,8.525);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAeA+IAAg7Ig6AAIAAA7IgLAAIAAh8IALAAIAAA5IA6AAIAAg5IAKAAIAAB8g");
	this.shape_37.setTransform(4.025,6.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol26, new cjs.Rectangle(0,0,267.2,16.2), null);


(lib.Symbol25 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag6BIQgVgYAAgoIAAgPQAAgoAVgYQAWgZAkAAQAlAAAWAZQAVAYAAAoIAAAPQAAAogVAYQgWAZglAAQgkAAgWgZgAgcgOIAAAdQAAAqAcAAQAdAAAAgqIAAgdQAAgqgdAAQgcAAAAAqg");
	this.shape.setTransform(202.7,15.425);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AASBeIgZg9IgOAAIAAA9IgwAAIAAi7IBKAAQAcAAARAQQASARAAAdIAAADQAAAmgdAPIAfBFgAgVgGIAVAAQASAAAAgWIAAgDQAAgWgSAAIgVAAg");
	this.shape_1.setTransform(186.875,15.425);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag+BeIAAi7IB6AAIAAAoIhJAAIAAAhIBBAAIAAAmIhBAAIAAAkIBMAAIAAAog");
	this.shape_2.setTransform(171.925,15.425);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag8BeIAAgkIA/hvIg6AAIAAgoIBxAAIAAAkIg+BvIBBAAIAAAog");
	this.shape_3.setTransform(157.95,15.425);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgYBeIAAi7IAxAAIAAC7g");
	this.shape_4.setTransform(143.425,15.425);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhKBeIAAi7IBCAAQAmAAAVAVQAYAWAAArIAAAPQgBArgXAWQgWAVglAAgAgZA2IAOAAQAiAAAAgnIAAgdQABgVgKgKQgIgIgRAAIgOAAg");
	this.shape_5.setTransform(131.75,15.425);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AASBeIgZg9IgOAAIAAA9IgwAAIAAi7IBKAAQAcAAARAQQASARAAAdIAAADQAAAmgdAPIAfBFgAgVgGIAVAAQASAAAAgWIAAgDQAAgWgSAAIgVAAg");
	this.shape_6.setTransform(115.825,15.425);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag+BeIAAi7IB6AAIAAAoIhJAAIAAAhIBBAAIAAAmIhBAAIAAAkIBMAAIAAAog");
	this.shape_7.setTransform(100.875,15.425);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgbBeIgzi7IA0AAIAbB/IAch/IAyAAIgzC7g");
	this.shape_8.setTransform(85.575,15.425);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag6BIQgVgYAAgoIAAgPQAAgoAVgYQAWgZAkAAQAlAAAWAZQAVAYAAAoIAAAPQAAAogVAYQgWAZglAAQgkAAgWgZgAgcgOIAAAdQAAAqAcAAQAdAAAAgqIAAgdQAAgqgdAAQgcAAAAAqg");
	this.shape_9.setTransform(64.675,15.425);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAhB8IgJgiIgxAAIgJAiIgyAAIA5i7IA2AAIA6C7gAgPA1IAeAAIgPg9gAAChXQgLgFgEAAQgHAAAAAJIgaAAQABgXAHgJQAGgIANAAQAIAAAKAFQAKAFAEgBQAHABABgJIAZAAQgBAWgGAJQgHAJgMAAQgIgBgKgEg");
	this.shape_10.setTransform(48.5,12.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgXBeIAAiTIgoAAIAAgoIB/AAIAAAoIgnAAIAACTg");
	this.shape_11.setTransform(35.3,15.425);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag9BeIAAi7IB5AAIAAAoIhJAAIAAAhIBBAAIAAAmIhBAAIAAAkIBLAAIAAAog");
	this.shape_12.setTransform(21.5,15.425);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhEBeIAAi7IBLAAQAaAAAOAMQAQANAAAYIAAAEQAAAYgTANQAZALAAAeIAAADQAAAYgQAPQgPAOgbAAgAgUA3IAYAAQAQAAABgRIAAgFQgBgRgQAAIgYAAgAgUgRIAUAAQAQAAAAgQIAAgFQAAgQgQAAIgUAAg");
	this.shape_13.setTransform(6.9,15.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol25, new cjs.Rectangle(0,0,210.7,25.2), null);


(lib.Symbol24 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgiAvQgMgPAAgcIAAgIQAAgbAMgPQANgPAVAAQAWAAAMAPQANAPAAAbIAAAIQAAAcgNAPQgMAQgWAAQgVAAgNgQgAgggEIAAAIQAAAuAgAAQAhAAAAguIAAgIQAAgtghAAQggAAAAAtg");
	this.shape.setTransform(84.65,6.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgkA8IAAh4IAmAAQAPAAAKAKQAJAJAAAQIAAACQAAARgJAIQgJAJgQAAIgYAAIAAAxgAgWAAIAYAAQAUAAABgXIAAgCQgBgXgUAAIgYAAg");
	this.shape_1.setTransform(75.2,6.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAlA8IAAhmIgfBmIgLAAIgfhmIAABmIgOAAIAAh4IAVAAIAdBkIAehkIAVAAIAAB4g");
	this.shape_2.setTransform(64.425,6.25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AghA8IAAh4IBCAAIAAAMIg0AAIAAAqIAwAAIAAAKIgwAAIAAAsIA1AAIAAAMg");
	this.shape_3.setTransform(54.175,6.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgGA8IAAhsIgeAAIAAgMIBJAAIAAAMIgeAAIAABsg");
	this.shape_4.setTransform(45.65,6.25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAgA8IgKghIgrAAIgKAhIgPAAIAoh4IANAAIAoB4gAgSAPIAkAAIgSg6g");
	this.shape_5.setTransform(38.15,6.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgaA1QgMgKAAgUIANAAQADAbAYAAQAXAAAAgVIAAgBQAAgKgGgFQgGgEgOgEQgTgFgIgGQgHgIAAgNIAAgCQAAgOAKgJQAKgJAPAAQAPAAAKAIQALAJABASIgOAAQgCgYgVAAQgVAAAAAVIAAACQAAAIAFAFQAGAEANAEQATAEAIAGQAJAJAAAOIAAACQAAAPgKAJQgKAKgSAAQgRAAgKgKg");
	this.shape_6.setTransform(29.075,6.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgaA1QgMgKAAgUIAOAAQACAbAYAAQAYAAAAgVIAAgBQgBgKgFgFQgGgEgQgEQgSgFgHgGQgIgIABgNIAAgCQAAgOAJgJQAKgJAPAAQAPAAALAIQAKAJACASIgPAAQgBgYgWAAQgVAAAAAVIAAACQAAAIAGAFQAFAEANAEQATAEAIAGQAJAJAAAOIAAACQAAAPgKAJQgKAKgRAAQgRAAgLgKg");
	this.shape_7.setTransform(20.35,6.25);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAgA8IgKghIgrAAIgLAhIgNAAIAnh4IAOAAIAnB4gAgRAPIAjAAIgSg6g");
	this.shape_8.setTransform(11.35,6.25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgkA8IAAh4IAmAAQAPAAAKAKQAJAJAAAQIAAACQAAARgJAIQgJAJgQAAIgXAAIAAAxgAgVAAIAXAAQAUAAABgXIAAgCQgBgXgUAAIgXAAg");
	this.shape_9.setTransform(3.65,6.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol24, new cjs.Rectangle(0,0,89.4,12.5), null);


(lib.Symbol23 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGiFFQgFAAgDgDQgEgEAAgFIAAlwQAAgFAEgDQADgDAFAAIAxAAQAFAAADADQADADAAAFIAAFwQAAAFgDAEQgDADgFAAgACyFFIAAhGIBTAAQAFAAADgEQAEgDAAgFIAAjkQAAgFgEgEQgDgDgFAAIhxAAIAAFCIhJAAIAAmHIDHAAQARAAALALIAfAfQAMAMAAAPIAAD8QAAAQgMAMIgfAfQgLALgRAAgAgOFFQgRAAgPgJQgPgJgHgQIgohPIAuAAQAPAAAMAHQAMAHAHANIArBWgAkBFFIAAlCQAAgPALgMIAggfQALgLAQAAICCAAQARAAALALIAfAfQALAMAAAPIAABrQAAAQgLAMIgfAfQgLALgQAAIhjAAIAAhBIBVAAQAFAAAEgEQADgDAAgFIAAhYQAAgFgDgEQgEgDgFAAIhnAAQgFAAgEADQgDAEAAAFIAAE2gAoHFFQgQAAgLgLIgggfQgLgMAAgQIAAj8QAAgPALgMIAggfQALgLAQAAICAAAQARAAALALIAgAfQALAMAAAPIAABoQAAAQgLAMIggAfQgMAMgPAAIhhAAIAAhHIBTAAQAFAAAEgDQADgEAAgFIAAhQQAAgFgDgEQgEgDgFAAIhlAAQgFAAgEADQgDAEAAAFIAADjQAAAFADADQAEAEAFAAICSAAQAFAAADADQAEAEAAAFQAAAEgEAEIgnAoQgLALgRAAgAsaFFQgRAAgLgLIgPgQIByhyIAAjvQAAgFAEgDQADgDAFAAIAxAAQAFAAADADQAEADAAAFIAAD6QAAAQgMAMIhbBbQgLALgRAAgAuRDfQgLgLAAgRIAAj6QAAgFADgDQAEgDAFAAIAwAAQAFAAADADQAEADAAAFIAADvIArArIgyAygANPAlQgMgKAAgUIAAgiQAAgTAMgLQAMgLAVAAQAVAAAMALQAMALAAATIAAAiQAAAUgMAKQgLALgWAAQgWAAgLgLgANdgsQgGAGAAALIAAAiQAAALAGAGQAHAGAMAAQANAAAGgGQAGgFAAgMIAAgiQAAgLgGgGQgHgFgMAAQgNAAgGAFgAMiAtQgCAAgBgEIgOgbQgDgGgEgDQgDgCgJAAIgLAAIAAAmQAAAAAAABQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAQAAABgBAAQgBAAgBAAIgJAAQgBAAAAAAQgBAAgBgBQAAAAgBAAQAAAAAAAAIgBgEIAAhlIABgEQAAgBABAAQAAAAABAAQAAgBABAAQABAAAAAAIAsAAQARAAAJAKQAKAJAAAQQAAAMgGAJQgFAIgKACIAFAHIARAiQADAFgFAAgALzgOIAbAAQAJAAADgFQAFgDAAgJQAAgIgFgEQgDgEgJAAIgbAAgAKIAuQgBAAAAAAQgBAAgBgBQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAgBAAAAIAAhlQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAIA/AAQABAAABAAQAAAAABABQAAAAABAAQAAAAABABIABAEIAAAIIgBAEQgBAAAAAAQAAAAgBABQAAAAgBAAQgBAAgBAAIgwAAIAAAcIApAAIAEABIABAEIAAAIIgBAEIgEABIgpAAIAAAcIAyAAQABAAABAAQABAAAAABQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAABIAAAIQAAAAAAABQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAQAAABgBAAQgBAAgBAAgAIlAuIgEgBIgBgEIAAgIQAAgDACgDIA3hKIgzAAQgBAAAAAAQgBAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAgBAAAAQAAgBAAAAIAAgIQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAIBGAAQABAAABAAQAAAAABABQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAABIAAAHQAAADgCADIg3BKIA0AAQABAAABAAQABAAAAABQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAABIAAAIQAAAAAAABQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAQAAABgBAAQgBAAgBAAgAibiAIA1hsQAVgpAmgXQAmgYAsAAIHuAAIg5BzQgSAlgjAWQgkAWgpAAgAE0jsIgFAeQgDASAIALQAJAKAUAAQAmAAAHgmIAFgdQADgSgJgLQgJgLgTAAQgmAAgHAmgAEMi8IACANQABAGAHAAIALAAQAFAAAAgFIgQhcQAAgGgGAAIgMAAQgEAAgDAEIgwBdQgCAGAGAAIALAAQAHAAACgEIAHgPgACbkLIgCAKQgBAGAGAAIATAAIgNBMQgBAGAGAAIALAAQAGAAAAgFIAOhNIAUAAQAGAAAAgFIACgJQABgHgFAAIg+AAQgHAAAAAFgABSkKIgRBbQAAAGAFAAIA3AAQAFAAABgFIACgJQAAgHgFAAIglAAIADgUIAeAAQAFAAABgGIACgJQABgGgGAAIgdAAIADgUIAlAAQAFAAABgFIACgJQABgHgGAAIg0AAQgHAAAAAGgAgCkLIgQBcQgBAGAGAAIAkAAQARAAAKgJQAKgJAAgQQAAgNgJgGIAAgBQAOgJAAgPQAAgZgcAAIgiAAQgEAAgBAFgAENkYQAFADAGAAQALAAACgOQABgGgDAAIgHAAQAAAAgBAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAFgEAAIgGgEQgFgEgHAAQgMAAgBAPQgBAFADAAIAHAAQAAAAABAAQAAAAABAAQAAgBAAAAQAAgBAAAAQABgFADAAQACAAAGAEgAFFjMIAGgfQADgSARAAQARAAgDARIgGAeQgDATgRAAQgRAAADgRgAAGi9IAEgWIATAAQAJAAAAAIQAAAGgEAEQgEAEgHAAgAD1jPIAKgWQAGgNACgJIABAAQgBAIABAMIACAYgAANjmIAEgWIAQAAQAKAAgBALQgBALgLAAg");
	this.shape.setTransform(92.525,32.525);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol23, new cjs.Rectangle(0,0,185.1,65.1), null);


(lib.Symbol21 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_65 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(65).call(this.frame_65).wait(1));

	// Layer_8 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EgITAgUMAAAhAnIQoAAMAAABAng");
	var mask_graphics_1 = new cjs.Graphics().p("EgITAgaMAAAhAzIQoAAMAAABAzg");
	var mask_graphics_2 = new cjs.Graphics().p("EgITAggMAAAhBAIQoAAMAAABBAg");
	var mask_graphics_3 = new cjs.Graphics().p("EgITAgnMAAAhBNIQoAAMAAABBNg");
	var mask_graphics_4 = new cjs.Graphics().p("EgITAguMAAAhBbIQoAAMAAABBbg");
	var mask_graphics_5 = new cjs.Graphics().p("EgITAg0MAAAhBnIQoAAMAAABBng");
	var mask_graphics_6 = new cjs.Graphics().p("EgITAg7MAAAhB1IQoAAMAAABB1g");
	var mask_graphics_7 = new cjs.Graphics().p("EgITAhBMAAAhCBIQoAAMAAABCBg");
	var mask_graphics_8 = new cjs.Graphics().p("EgITAhIMAAAhCPIQoAAMAAABCPg");
	var mask_graphics_9 = new cjs.Graphics().p("EgITAhPMAAAhCdIQoAAMAAABCdg");
	var mask_graphics_10 = new cjs.Graphics().p("EgITAhVMAAAhCpIQoAAMAAABCpg");
	var mask_graphics_11 = new cjs.Graphics().p("EgITAhbMAAAhC2IQoAAMAAABC2g");
	var mask_graphics_12 = new cjs.Graphics().p("EgITAhiMAAAhDDIQoAAMAAABDDg");
	var mask_graphics_13 = new cjs.Graphics().p("EgITAhpMAAAhDRIQoAAMAAABDRg");
	var mask_graphics_14 = new cjs.Graphics().p("EgITAhvMAAAhDdIQoAAMAAABDdg");
	var mask_graphics_15 = new cjs.Graphics().p("EgITAh2MAAAhDrIQoAAMAAABDrg");
	var mask_graphics_16 = new cjs.Graphics().p("EgITAh8MAAAhD3IQoAAMAAABD3g");
	var mask_graphics_17 = new cjs.Graphics().p("EgITAiDMAAAhEFIQoAAMAAABEFg");
	var mask_graphics_18 = new cjs.Graphics().p("EgITAiKMAAAhETIQoAAMAAABETg");
	var mask_graphics_19 = new cjs.Graphics().p("EgITAiQMAAAhEfIQoAAMAAABEfg");
	var mask_graphics_20 = new cjs.Graphics().p("EgITAiWMAAAhErIQoAAMAAABErg");
	var mask_graphics_21 = new cjs.Graphics().p("EgITAidMAAAhE5IQoAAMAAABE5g");
	var mask_graphics_22 = new cjs.Graphics().p("EgITAikMAAAhFHIQoAAMAAABFHg");
	var mask_graphics_23 = new cjs.Graphics().p("EgITAiqMAAAhFTIQoAAMAAABFTg");
	var mask_graphics_24 = new cjs.Graphics().p("EgITAixMAAAhFhIQoAAMAAABFhg");
	var mask_graphics_25 = new cjs.Graphics().p("EgITAi4MAAAhFuIQoAAMAAABFug");
	var mask_graphics_26 = new cjs.Graphics().p("EgITAi+MAAAhF7IQoAAMAAABF7g");
	var mask_graphics_27 = new cjs.Graphics().p("EgITAjEMAAAhGHIQoAAMAAABGHg");
	var mask_graphics_28 = new cjs.Graphics().p("EgITAjLMAAAhGVIQoAAMAAABGVg");
	var mask_graphics_29 = new cjs.Graphics().p("EgITAjSMAAAhGjIQoAAMAAABGjg");
	var mask_graphics_30 = new cjs.Graphics().p("EgITAjYMAAAhGvIQoAAMAAABGvg");
	var mask_graphics_31 = new cjs.Graphics().p("EgITAjfMAAAhG9IQoAAMAAABG9g");
	var mask_graphics_32 = new cjs.Graphics().p("EgITAjlMAAAhHJIQoAAMAAABHJg");
	var mask_graphics_33 = new cjs.Graphics().p("EgITAjsMAAAhHXIQoAAMAAABHXg");
	var mask_graphics_34 = new cjs.Graphics().p("EgITAjzMAAAhHkIQoAAMAAABHkg");
	var mask_graphics_35 = new cjs.Graphics().p("EgITAj5MAAAhHxIQoAAMAAABHxg");
	var mask_graphics_36 = new cjs.Graphics().p("EgITAj/MAAAhH+IQoAAMAAABH+g");
	var mask_graphics_37 = new cjs.Graphics().p("EgITAkGMAAAhILIQoAAMAAABILg");
	var mask_graphics_38 = new cjs.Graphics().p("EgITAkNMAAAhIZIQoAAMAAABIZg");
	var mask_graphics_39 = new cjs.Graphics().p("EgITAkTMAAAhIlIQoAAMAAABIlg");
	var mask_graphics_40 = new cjs.Graphics().p("EgITAkaMAAAhIzIQoAAMAAABIzg");
	var mask_graphics_41 = new cjs.Graphics().p("EgITAkgMAAAhI/IQoAAMAAABI/g");
	var mask_graphics_42 = new cjs.Graphics().p("EgITAknMAAAhJNIQoAAMAAABJNg");
	var mask_graphics_43 = new cjs.Graphics().p("EgITAkuMAAAhJaIQoAAMAAABJag");
	var mask_graphics_44 = new cjs.Graphics().p("EgITAk0MAAAhJnIQoAAMAAABJng");
	var mask_graphics_45 = new cjs.Graphics().p("EgITAk6MAAAhJ0IQoAAMAAABJ0g");
	var mask_graphics_46 = new cjs.Graphics().p("EgJRAk9MAAAhJ5ISkAAMAAABJ5g");
	var mask_graphics_47 = new cjs.Graphics().p("EgKQAlAMAAAhKAIUhAAMAAABKAg");
	var mask_graphics_48 = new cjs.Graphics().p("EgLOAlDMAAAhKGIWdAAMAAABKGg");
	var mask_graphics_49 = new cjs.Graphics().p("EgMMAlGMAAAhKLIYZAAMAAABKLg");
	var mask_graphics_50 = new cjs.Graphics().p("EgNKAlJMAAAhKSIaVAAMAAABKSg");
	var mask_graphics_51 = new cjs.Graphics().p("EgOIAlMMAAAhKYIcRAAMAAABKYg");
	var mask_graphics_52 = new cjs.Graphics().p("EgPGAlPMAAAhKdIeNAAMAAABKdg");
	var mask_graphics_53 = new cjs.Graphics().p("EgQFAlSMAAAhKkMAgLAAAMAAABKkg");
	var mask_graphics_54 = new cjs.Graphics().p("EgRDAlVMAAAhKqMAiHAAAMAAABKqg");
	var mask_graphics_55 = new cjs.Graphics().p("EgSAAlYMAAAhKvMAkCAAAMAAABKvg");
	var mask_graphics_56 = new cjs.Graphics().p("EgS/AlbMAAAhK2MAl/AAAMAAABK2g");
	var mask_graphics_57 = new cjs.Graphics().p("EgT9AleMAAAhK8MAn7AAAMAAABK8g");
	var mask_graphics_58 = new cjs.Graphics().p("EgU7AlhMAAAhLBMAp3AAAMAAABLBg");
	var mask_graphics_59 = new cjs.Graphics().p("EgV5AlkMAAAhLIMArzAAAMAAABLIg");
	var mask_graphics_60 = new cjs.Graphics().p("EgW3AlnMAAAhLOMAtvAAAMAAABLOg");
	var mask_graphics_61 = new cjs.Graphics().p("EgX1AlqMAAAhLTMAvrAAAMAAABLTg");
	var mask_graphics_62 = new cjs.Graphics().p("EgYzAltMAAAhLaMAxoAAAMAAABLag");
	var mask_graphics_63 = new cjs.Graphics().p("EgZyAlwMAAAhLgMAzlAAAMAAABLgg");
	var mask_graphics_64 = new cjs.Graphics().p("EgawAlzMAAAhLlMA1hAAAMAAABLlg");
	var mask_graphics_65 = new cjs.Graphics().p("EgbuAl2MAAAhLsMA3dAAAMAAABLsg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:292.25,y:-203.35}).wait(1).to({graphics:mask_graphics_1,x:292.25,y:-193.8}).wait(1).to({graphics:mask_graphics_2,x:292.25,y:-184.25}).wait(1).to({graphics:mask_graphics_3,x:292.25,y:-174.725}).wait(1).to({graphics:mask_graphics_4,x:292.25,y:-165.175}).wait(1).to({graphics:mask_graphics_5,x:292.25,y:-155.625}).wait(1).to({graphics:mask_graphics_6,x:292.25,y:-146.075}).wait(1).to({graphics:mask_graphics_7,x:292.25,y:-136.525}).wait(1).to({graphics:mask_graphics_8,x:292.25,y:-127}).wait(1).to({graphics:mask_graphics_9,x:292.25,y:-117.45}).wait(1).to({graphics:mask_graphics_10,x:292.25,y:-107.9}).wait(1).to({graphics:mask_graphics_11,x:292.25,y:-98.35}).wait(1).to({graphics:mask_graphics_12,x:292.25,y:-88.8}).wait(1).to({graphics:mask_graphics_13,x:292.25,y:-79.275}).wait(1).to({graphics:mask_graphics_14,x:292.25,y:-69.725}).wait(1).to({graphics:mask_graphics_15,x:292.25,y:-60.175}).wait(1).to({graphics:mask_graphics_16,x:292.25,y:-50.625}).wait(1).to({graphics:mask_graphics_17,x:292.25,y:-41.075}).wait(1).to({graphics:mask_graphics_18,x:292.25,y:-31.55}).wait(1).to({graphics:mask_graphics_19,x:292.25,y:-22}).wait(1).to({graphics:mask_graphics_20,x:292.25,y:-12.45}).wait(1).to({graphics:mask_graphics_21,x:292.25,y:-2.9}).wait(1).to({graphics:mask_graphics_22,x:292.25,y:6.675}).wait(1).to({graphics:mask_graphics_23,x:292.25,y:16.175}).wait(1).to({graphics:mask_graphics_24,x:292.25,y:25.75}).wait(1).to({graphics:mask_graphics_25,x:292.25,y:35.3}).wait(1).to({graphics:mask_graphics_26,x:292.25,y:44.85}).wait(1).to({graphics:mask_graphics_27,x:292.25,y:54.4}).wait(1).to({graphics:mask_graphics_28,x:292.25,y:63.925}).wait(1).to({graphics:mask_graphics_29,x:292.25,y:73.475}).wait(1).to({graphics:mask_graphics_30,x:292.25,y:83.025}).wait(1).to({graphics:mask_graphics_31,x:292.25,y:92.575}).wait(1).to({graphics:mask_graphics_32,x:292.25,y:102.125}).wait(1).to({graphics:mask_graphics_33,x:292.25,y:111.65}).wait(1).to({graphics:mask_graphics_34,x:292.25,y:121.2}).wait(1).to({graphics:mask_graphics_35,x:292.25,y:130.75}).wait(1).to({graphics:mask_graphics_36,x:292.25,y:140.3}).wait(1).to({graphics:mask_graphics_37,x:292.25,y:149.85}).wait(1).to({graphics:mask_graphics_38,x:292.25,y:159.375}).wait(1).to({graphics:mask_graphics_39,x:292.25,y:168.925}).wait(1).to({graphics:mask_graphics_40,x:292.25,y:178.475}).wait(1).to({graphics:mask_graphics_41,x:292.25,y:188.025}).wait(1).to({graphics:mask_graphics_42,x:292.25,y:197.575}).wait(1).to({graphics:mask_graphics_43,x:292.25,y:207.1}).wait(1).to({graphics:mask_graphics_44,x:292.25,y:216.65}).wait(1).to({graphics:mask_graphics_45,x:292.25,y:226.2}).wait(1).to({graphics:mask_graphics_46,x:286.05,y:225.9}).wait(1).to({graphics:mask_graphics_47,x:279.825,y:225.6}).wait(1).to({graphics:mask_graphics_48,x:273.625,y:225.3}).wait(1).to({graphics:mask_graphics_49,x:267.4,y:225}).wait(1).to({graphics:mask_graphics_50,x:261.2,y:224.7}).wait(1).to({graphics:mask_graphics_51,x:254.975,y:224.4}).wait(1).to({graphics:mask_graphics_52,x:248.775,y:224.1}).wait(1).to({graphics:mask_graphics_53,x:242.55,y:223.8}).wait(1).to({graphics:mask_graphics_54,x:236.35,y:223.5}).wait(1).to({graphics:mask_graphics_55,x:230.15,y:223.2}).wait(1).to({graphics:mask_graphics_56,x:223.925,y:222.9}).wait(1).to({graphics:mask_graphics_57,x:217.725,y:222.6}).wait(1).to({graphics:mask_graphics_58,x:211.5,y:222.3}).wait(1).to({graphics:mask_graphics_59,x:205.3,y:222}).wait(1).to({graphics:mask_graphics_60,x:199.075,y:221.7}).wait(1).to({graphics:mask_graphics_61,x:192.875,y:221.4}).wait(1).to({graphics:mask_graphics_62,x:186.65,y:221.1}).wait(1).to({graphics:mask_graphics_63,x:180.45,y:220.8}).wait(1).to({graphics:mask_graphics_64,x:174.225,y:220.5}).wait(1).to({graphics:mask_graphics_65,x:168.025,y:220.2}).wait(1));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgXfAjvIAAgGMAi0AAAQDOAACSiSQCSiSAAjOMAAAg4hQAAiTBOh6QBLh4B/g/IAAAGQh7A/hLB2QhMB5AACQMAAAA4hQAADRiUCTQiTCUjRAAg");
	this.shape.setTransform(150.35,228.7);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(66));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,300.7,457.4);


(lib.Symbol20 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Image();
	this.instance.setTransform(0,0,0.539,0.539);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol20, new cjs.Rectangle(0,0,262.5,187.1), null);


// stage content:
(lib.banner_cabecalho_728x90 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [269];
	// timeline functions:
	this.frame_269 = function() {
		if (myCounter++ >=3){
			this.stop();
		};
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(269).call(this.frame_269).wait(1));

	// Symbol 19
	this.instance = new lib.Symbol30();
	this.instance.setTransform(648.8,45,0.2806,0.2806,0,0,0,68,20.9);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(171).to({_off:false},0).to({regX:68.2,scaleX:1,scaleY:1,x:648.85,y:45.05,alpha:1},17,cjs.Ease.backOut).wait(82));

	// Symbol 18
	this.instance_1 = new lib.Symbol32();
	this.instance_1.setTransform(336.85,58.8,1,1,0,0,0,105.5,19.9);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(161).to({_off:false},0).to({x:316.85,alpha:1},17,cjs.Ease.backOut).wait(92));

	// Symbol 17
	this.instance_2 = new lib.Symbol31();
	this.instance_2.setTransform(325.35,21.4,1,1,0,0,0,94,6.2);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(154).to({_off:false},0).to({x:305.35,alpha:1},17,cjs.Ease.backOut).wait(99));

	// Layer_13
	this.instance_3 = new lib.Symbol20();
	this.instance_3.setTransform(502.55,45.6,0.4062,0.406,0,0,0,133.4,93.6);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(186).to({_off:false},0).to({scaleX:0.4912,scaleY:0.491,alpha:1},22,cjs.Ease.quadOut).wait(62));

	// Layer_12
	this.instance_4 = new lib.Symbol21();
	this.instance_4.setTransform(150.05,337.15,1,1,0,0,0,150.3,228.7);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(146).to({_off:false},0).wait(124));

	// cta copy
	this.instance_5 = new lib.Symbol28();
	this.instance_5.setTransform(582.2,45.05,0.3126,0.3126,0,0,0,73.8,22.6);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(35).to({_off:false},0).to({scaleX:1,scaleY:1,x:582.25,alpha:1},17,cjs.Ease.backOut).wait(82).to({alpha:0},11).to({_off:true},1).wait(124));

	// logo
	this.instance_6 = new lib.Symbol27();
	this.instance_6.setTransform(693.8,45.05,1,1,0,0,0,17.8,21.2);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({alpha:1},12).wait(122).to({alpha:0},11).to({_off:true},1).wait(124));

	// Layer_8
	this.instance_7 = new lib.Symbol26();
	this.instance_7.setTransform(373.95,72.8,1,1,0,0,0,133.6,8.1);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(22).to({_off:false},0).to({x:353.95,alpha:1},17,cjs.Ease.backOut).wait(95).to({alpha:0},11).to({_off:true},1).wait(124));

	// Symbol 10
	this.instance_8 = new lib.Symbol25();
	this.instance_8.setTransform(345.55,44,1,1,0,0,0,105.4,12.6);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(13).to({_off:false},0).to({x:325.55,alpha:1},17,cjs.Ease.backOut).wait(104).to({alpha:0},11).to({_off:true},1).wait(124));

	// Symbol 9
	this.instance_9 = new lib.Symbol24();
	this.instance_9.setTransform(284.75,20.4,1,1,0,0,0,44.6,6.2);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(8).to({_off:false},0).to({x:264.75,alpha:1},17,cjs.Ease.backOut).wait(109).to({alpha:0},11).to({_off:true},1).wait(124));

	// LOGO2
	this.instance_10 = new lib.Symbol23();
	this.instance_10.setTransform(105.4,45,1,1,0,0,0,92.5,32.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(270));

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00B859").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape.setTransform(22.4991,44.9982,0.15,0.15);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(270));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(363.3,-256.6,358.7,859);
// library properties:
lib.properties = {
	id: '4C67F3A136A92E4E81338A9018FE5B2A',
	width: 728,
	height: 90,
	fps: 30,
	color: "#00B859",
	opacity: 1.00,
	manifest: [
		{src:"images/Image.png?1669040123503", id:"Image"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['4C67F3A136A92E4E81338A9018FE5B2A'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;